### ISSUE TITLE
Rating severity of breathlessness

### ISSUE THREAD

**Issue by aparnacoronasafe** [ohcnetwork/care_fe#1001]
**Is your feature request related to a problem? Please describe.**
severity of Breathlessness experienced by a patient is important information to carry out shifting.

Currently, a doctor in the shifting team calls the patient to check the same and notes down the information in a separate sheet. we need to capture this in care.

**Describe the solution you'd like**
There must be an additional question in shifting form.

- Whether the patient suffers from breathlessness? YES/NO (this field can be filled/edited by anyone with access)
- If yes, is the breathlessness MILD (requiring less than 5 l/m of oxygen)
                                                   MODERATE (requiring 5-10 l/m of oxygen)
                                                   SEVERE (requiring more than 15 l/m of oxygen)
**The second field must be filled only by staff at the shifting centre or the district admin, NOT the facility**

This is a prerequisite for generating daily reports filed in the next issue

**Comment by bodhish** [comment]
@vigneshhari could you share the details of the API

**Comment by vigneshhari** [comment]
Check swagger
