### ISSUE TITLE
Reporting in CARE

### ISSUE THREAD

**Issue by aparnacoronasafe** [ohcnetwork/care_fe#1002]
There are 3 Reports needed by the District Administration

## Report 1: Dyspnoea Report (daily)

https://drive.google.com/file/d/1gwxk8klEqRQ4hAySCbxApXJB8Gk-hdAt/view?usp=sharing (Request for access, message Aparna on Slack)

Here the number of people with Dyspnoea (breathlessness) is collected, across different age groups. 

- **People under home care (under COVID MANAGEMENT CENTRES)** : 
- With MILD breathlessness:  
- With MODERATE breathlessness:
- With SEVERE breathlessness:

**People in COVID centres** (patients in first-line treatment centres, second-line treatment centres, and COVID-19 Domiciliary CARE centres)

**People is hospitals**
PVT. Hospitals
Govt. hospitals

**People that are vaccinated**
First dose only
Both doses

The bottom row must also have a total number. (sum of people in home care, covid centres and hospitals)

## Report 2: Bed occupancy in Pvt Hospitals

Issue 975 is a prerequisite 

https://drive.google.com/file/d/1wWcv8TCTxJGWtJYFPNG-RPPMljQB5tla/view?usp=sharing
(the totals and calculations in this report are all wrong, may lead to confusion)

Here normal beds are non oxygen ordinary beds in isolation wards and isolation rooms
O2 beds are oxygen beds
ICU beds are same
Invasive ventilators are the same
Non-invasive ventilators are number of BiPaPs and CPaPs in a facility 
TOTAL: sum of 1, 2, and 3 (4&5 are devices and not bed type)

<img width="1194" alt="Screenshot 2021-04-30 at 10 05 07 PM" src="https://user-images.githubusercontent.com/67050716/116726488-f90c8000-aa00-11eb-9f58-69f94da43549.png">

## Report 3: Bed occupancy in Govt Hospitals

https://drive.google.com/drive/folders/1tCTVusL9J7EWe6e4Ok6sMPPETxGiQyPQ

The facility name, Total Capacity, Occupied and available are shown here

**Comment by bodhish** [comment]
@gigincg could you followup on this

**Comment by bodhish** [comment]
@aparnacoronasafe metabse
