### ISSUE TITLE
Edit option on Inventory Management

### ISSUE THREAD

**Issue by aparnacoronasafe** [ohcnetwork/care_fe#1011]
The inventory management needs edit module. 

The numbers entered incorrectly may be evened out by adding more "Use/add stock" to correct the total sum.

However, such adjustments affect the Opening stock, closing stock, daily consumption etc. which needs to be reported to the state.

Hence an edit option is indespensible.

**Comment by vigneshhari** [comment]
This will not be implemented , closing issue.
