### ISSUE TITLE
Oxygen Suppliers

### ISSUE THREAD

**Issue by aparnacoronasafe** [ohcnetwork/care_fe#1014]
There must be a field in each hospital to mention suppliers:

2 Questions to identify 

1- Suppliers of liquid oxygen : (drop-down with multiple selections)
2- Suppliers of gaseous oxygen : (drop-down with multiple selections)

List of suppliers :
https://docs.google.com/spreadsheets/d/1-WrggQ-aEwgZWgX_R5dECsdvehhApboiOgqR33Lw7dI/edit?usp=sharing

THIS IS TO ALIGN THE SYSTEM WITH COVID JAGRATHA

**Comment by bodhish** [comment]
@aparnacoronasafe this could be an online data collection with a google form. 
This doesn't really have to part of the system

**Comment by amruthavijay88** [comment]
@bodhish - Do you still think it doesn't have to be part of the system? Maharashtra needs this right - just checking.

**Comment by bodhish** [comment]
No. This is not how should be captured.

**Comment by aparnacoronasafe** [comment]
@bodhish I was not encouraging this request. but you told Dr. Akhil this could be captured on CARE. honestly even I don't see a lot of value here at this point.

**Comment by bodhish** [comment]
Let's close this
