### ISSUE TITLE
Report for Oxygen

### ISSUE THREAD

**Issue by aparnacoronasafe** [ohcnetwork/care_fe#1015]
https://docs.google.com/spreadsheets/d/1YMCMf84EsDhGeT91D9I4x6gXVAkZswq3BCpzOrzVNvk/edit?usp=sharing

A daily report must be prepared with the following information. The daily data must appear in the above table.

an export as CSV option would suffice

@bodhish @vigneshhari

**Comment by aparnacoronasafe** [comment]
https://docs.google.com/spreadsheets/d/1YMCMf84EsDhGeT91D9I4x6gXVAkZswq3BCpzOrzVNvk/edit?usp=sharing

@vigneshhari is it possible to tweak the format of the report to match the excel sheet?

I have added the fields from the current report that i think will be useful.
But the headers in the current report is very confusing. Also, we donot need the current status and closing stock. It becomes very confusing.

What we primarily require is
- Opening stock
- Stock added today
- Closing stock
- Stock consumed
- Is stock low
- Burn rate
- Last updated on

Please keep the order of these entries, because this is the formate mandated by the state

**Comment by vigneshhari** [comment]
@bodhish can do that

**Comment by aparnacoronasafe** [comment]
@shaileshaanand 

Please do post your doubt here and tag me

**Comment by divyagar** [comment]
@vigneshhari Do the fields that needs to be added in csv already exist in database?

**Comment by vigneshhari** [comment]
@divyagar to my knowledge this was done by bodhi yesterday, closing this issue
