### ISSUE TITLE
Number of empty cylinders to be recorded

### ISSUE THREAD

**Issue by aparnacoronasafe** [ohcnetwork/care_fe#1019]
The report and dashboard should also have the number of empty oxygen cylinders in a facility.

These cylinders are of 3 types, Type D,C and B. Numbers for each of these types needs to be added

The input can be added as 3 questions (one for each cylinder type) in facility details form, next to the oxygen (tank) capacity

**Comment by divyagar** [comment]
@aparnacoronasafe the report here is [this](https://docs.google.com/spreadsheets/d/1YMCMf84EsDhGeT91D9I4x6gXVAkZswq3BCpzOrzVNvk/edit#gid=0) one right?

**Comment by aparnacoronasafe** [comment]
@divyagar @shaileshaanand I have edited the issue to bring more clarity

Please get in touch if you have any doubts.

This input info must appear in the UI of facility, Dashboard, and CSV download

**Comment by aparnacoronasafe** [comment]
> this

yes @divyagar 

Whats the upodate here?

**Comment by shaileshaanand** [comment]
@aparnacoronasafe  Pull Request #1022 solves this, waiting for @vigneshhari  to merge it
