### ISSUE TITLE
Bug in editing basic info

### ISSUE THREAD

**Issue by aparnacoronasafe** [ohcnetwork/care_fe#1021]
**Describe the bug**
Any user can edit their profile basic information by Clicking on Profile on the left panel of the screen. https://care.coronasafe.network/user/profile

When the user tries to edit age, the error message appears on the screen.

<img width="1021" alt="Screenshot 2021-05-04 at 12 03 28 PM" src="https://user-images.githubusercontent.com/67050716/116967793-c39db600-acd0-11eb-9de7-8f0a7b9ec1e3.png">

The user that reported this is devisha@care

**Comment by sam9111** [comment]
I believe this bug has been resolved in https://care.coronasafe.in/user/profile.

![Screenshot 2021-05-04 at 2 56 50 PM (2)](https://user-images.githubusercontent.com/60708693/116984609-0ff4f000-ace9-11eb-8f52-704c7610547c.png)
![Screenshot 2021-05-04 at 2 57 25 PM (2)](https://user-images.githubusercontent.com/60708693/116984641-17b49480-ace9-11eb-9190-38a75029e083.png)

**Comment by aparnacoronasafe** [comment]
bug resolved
