### ISSUE TITLE
Ventilator: Invasive/ non-invasive

### ISSUE THREAD

**Issue by aparnacoronasafe** [ohcnetwork/care_fe#1027]
https://care.coronasafe.in/facility/a3910fb7-db3d-4ddf-aa39-1f20e61d1453/bed

The bed type options appearing here:
there is Ventilator, KASP Ventilator, COVID Ventilator (the 3 types)

These need to be split into Invasive ventilator and non-invasive ventilator (all 3 types)

The change must reflect on the Capacity dashboard as well
https://dashboard.coronasafe.network/district/capacity

**Comment by aparnacoronasafe** [comment]
Additionally, also please split the ward beds to male/female

**Comment by Its-Aji** [comment]
Did you expecting like this.

How many ventilators, KASP Ventilators and COVID Ventilators under Invasive and non-invasive category?

**Comment by peeyush14goyal** [comment]
@vigneshhari Can I work on this with @shaileshaanand ?

**Comment by vigneshhari** [comment]
@peeyush14goyal this issue is closed for more research , will let you know when its done

**Comment by peeyush14goyal** [comment]
ok @vigneshhari
