### ISSUE TITLE
User Management Error while trying to access the details of linked facility

### ISSUE THREAD

**Issue by nihal467** [ohcnetwork/care_fe#1031]
![error](https://user-images.githubusercontent.com/57055998/117535976-38952680-b016-11eb-97c6-3f32e1172b49.JPG)

When we create a user with username ending  with '.' (dot) without assigning any facility to the user, the user is created successfully. But when we try to check the facilities by clicking the ' click here to show ' button in the user card, there is a pop-up alert that says "Something went wrong....!"

**Comment by divyagar** [comment]
@aparnacoronasafe @bodhish Is facilities field required while creating a user?

**Comment by divyagar** [comment]
The route to get facilities is `users/<username>/get_facilities/`
The issue here is that for a name ending with `.` (for example `name.`), django is not able to find the route. @bodhish Can I add constraint that a username cannot end with a `.` ?

**Comment by vigneshhari** [comment]
@divyagar go ahead with it. don't let it end with any special characters.
