### ISSUE TITLE
Expected demand for oxygen 

### ISSUE THREAD

**Issue by aparnacoronasafe** [ohcnetwork/care_fe#1034]
Please add the expected demand of oxygen in cylinders in 

- Jumbo D type cylinder
- C type cylinder
- B type cylinder.
- Rename expected oxygen requirement to expected `liquid medical oxygen `
This may be added in the facility form itself

**Comment by vigneshhari** [comment]
@aparnacoronasafe -_-

**Comment by aparnacoronasafe** [comment]
tested in staging
