### ISSUE TITLE
Allow shifting staff to approve destination

### ISSUE THREAD

**Issue by aparnacoronasafe** [ohcnetwork/care_fe#1035]
Allow shifting facility staff to approve destination on shifting.

A lot of times, the shifting staff called up the suggested destination hospital to ascertain whether they have a vacant bed. Once that is done, the shifting staff themselves approve the destination and carry out the shift. 

Currently, they use the district admin ID to do this.

But since shifting now happens at Taluk as well, we cannot give everyone district admin ID.

**Comment by vigneshhari** [comment]
The hospitals are supposed to do this, we have talked earlier about this step's repercussions.

**Comment by aparnacoronasafe** [comment]
@vigneshhari because our capacity dashboards are not 100% accurate the shifting team anyway calls the facility to figure out if they have vacant beds. So they get confirmation from the facility at that point over the phone. Having to wait for the facility to approve on care causes huge delay.

**Comment by bodhish** [comment]
@aparnacoronasafe let's not do this. 

In my understanding, the shifting team could move the patient to `TRANSPORTATION TO BE ARRANGED` without facility approval. 

If they are bypassing the facility let them move the cards to `TRANSPORTATION TO BE ARRANGED`

cc @vigneshhari

**Comment by vigneshhari** [comment]
Yes, this issue is a potential breaker for all access rights and can introduce access escalations, currently, a dist admin should be able to bypass this, let's keep it that way itself. @bodhish close this issue

**Comment by bodhish** [comment]
@aparnacoronasafe close this after review

**Comment by aparnacoronasafe** [comment]
I disagree with you. 

If you want to close, please go ahead and do it.

**Comment by aparnacoronasafe** [comment]
Test failed. The shifitng staff still cannot move card to "destination approved"
