### ISSUE TITLE
Making sense of the different bed types

### ISSUE THREAD

**Issue by aparnacoronasafe** [ohcnetwork/care_fe#1037]
**Problem Statement**

The bed types are not defined properly in the system
- **Normal Beds**- this may be read to include all beds or total beds in wards, including COVID and KASP beds
- **COVID beds**- This may include KAPS beds as well

Therefore, we see an overlapping in the different bed types. This causes an issue.

When there is overlapping in the bed types in Capacity, the occupancy levels don't match the percentage in reality. 

usually when hospitals enter the occupency, they treat the bed types as disjoint.
- **Normal bed occupancy** - is usually entered as patients that are non-covid, non-kasp
- **COVID beds**- is usually considered as covid patients, non KASP

This inconsistency leads to the percentage of occupancy always staying lower than real. 

Please define the bed type sets with more clarity

**Comment by aparnacoronasafe** [comment]
More clarity on bed types and reservations:

COVID Reservation: Currently 50 % of beds in all hospitals and reserved for COVID as per the direction of HC of kerala. This percentage is a variable.

KASP: earlier we had KASP reservation for a set number of beds in each hospital. Every private hospital was supposed to have 10 or so beds reserved for KASP. But currently, there is no such set number. KASP is no more reserved bed. Any number of poor can avail bed in a private hospital under KASP. Therefor KASP must be a tag on the patient and not the bed.

**Comment by bodhish** [comment]
So from what I read I assume 
1. We no longer have a use case to capture the total KASP beds in a hospital 
2. We don't really want to understand the number of KASP patients via the bed type rather we can get that data via consultation. (@vigneshhari thoughts) 
3. If 1 and 2 holds true, the KASP beds could be completely taken out (This would be super useful) 
4. If KASP is removed people could easily assume total is the total hospital utilisation and covid is covid specific numbers

**Comment by aparnacoronasafe** [comment]
1 and 2 are right.

I agree with 3

About 4, if we have normal beds and COVID beds, again the occupancy may not be noted as "total" patients and COVID patients. 

The hospitals tend to enter non- COVID occupancy in "normal". We need to define 

We still need to define the "normal" and "Covid" bed types more clearly

**Comment by divyagar** [comment]
@bodhish @vigneshhari Can i work on this issue?

**Comment by vigneshhari** [comment]
@divyagar this might require some more back and forth, i will build this out.

**Comment by bodhish** [comment]
@aparnacoronasafe create a new issue for `KASP` in patients and another issue in the dashboard to remove KASP from the dashboard summary

**Comment by aparnacoronasafe** [comment]
tested
