### ISSUE TITLE
Ordering of entries in inventory log

### ISSUE THREAD

**Issue by aparnacoronasafe** [ohcnetwork/care_fe#1038]
when you click on a particular inventory item to see the log, the log appear with the earliest coming first and the latest is usually hidden in the subsequent pages

page: https://care.coronasafe.in/facility/4a5cad7b-7681-48e0-a7a3-a4480fbbc4f4/inventory/5

Please reverse the order of these logs so that the latest entries appear on top

**Comment by smartclash** [comment]
Just a thought, but can this be done at https://github.com/coronasafe/care? We can just make the backend return data in descending order. Reduces workload at the client side.

**Comment by aparnacoronasafe** [comment]
@vigneshhari

**Comment by arpancodes** [comment]
I agree @smartclash

**Comment by aparnacoronasafe** [comment]
Tested in staging. Issue resolved
