### ISSUE TITLE
fixes for hospital view

### ISSUE THREAD

**Issue by dauntlessnomad** [ohcnetwork/care_fe#104]
**Bugs in create facility** 
- [x]  add hospital should not clear local state. (if i hit cancel, i should not go to loading)
- [x] Current utilization should not exceed Total capacity
- [x] Add bed type should go on loops. / show a form to all 4 bed types and send request.
- [x] Add doctor types should also should show a list / do loops
- [x] Latitude and lang should have a picker / instruction to add latitude and lang
- [x] Should not allow adding same bed type again (its safer to show all 4 bed types and ask for capacity and utilisation) (edited)

**Comment by injas-carcility** [comment]
- [x] Current utilization should not exceed Total capacity
- [x] Add bed type should go on loops. / show a form to all 4 bed types and send request.
- [x] Add doctor types should also should show a list / do loops

@tomahawk-pilot I'll work on these now

**Comment by AbhiramProbodhagan** [comment]
Taking up Lat/Long Picker task
