### ISSUE TITLE
SMS alert: Shifting

### ISSUE THREAD

**Issue by aparnacoronasafe** [ohcnetwork/care_fe#1040]
When a shifting staff is not assigned, The SMS simply says the shifting is approved but does not give the phone number of the shifting facility. 

![WhatsApp Image 2021-05-11 at 6 08 56 AM](https://user-images.githubusercontent.com/67050716/117805344-7bedd000-b276-11eb-96a7-3f66fa1f3834.jpeg)

**Comment by bodhish** [comment]
@aparnacoronasafe check if the shifting approving facility has a phone number
