### ISSUE TITLE
Remove Offset from paginated API's

### ISSUE THREAD

**Issue by bodhish** [ohcnetwork/care_fe#1045]
Remove the usage of `Offset` from paginated API's

**Comment by divyagar** [comment]
@bodhish @vigneshhari Instead of offset can we use page numbers here to fetch data?
For example `https://careapi.coronasafe.in/api/v1/patient/?page=1` will fetch first 15 records.

**Comment by vigneshhari** [comment]
The issue also states the same right ? Use only page numbers, remove the use of offsets everywhere.

**Comment by bodhish** [comment]
The usages of offset should be removed from frontend

**Comment by sam9111** [comment]
Should offset be replaced by page or just removed? @bodhish

**Comment by bodhish** [comment]
Removed @sam9111

**Comment by arihant-2310** [comment]
Is this issue still open? If so, I can pick it up.

**Comment by khavinshankar** [comment]
closing this as resolved
