### ISSUE TITLE
Add LSG details for the country. 

### ISSUE THREAD

**Issue by bodhish** [ohcnetwork/care_fe#1046]
Find and add the list of states, district, lsg and Wards in the country.

This will be a huge one time exercise.

**Comment by shrihari689** [comment]
😲😲😲😲!!! 
I am giving a hand and trying this 📍 But anyone please feel free to assign yourself 💙

**Comment by shrihari689** [comment]
Just extracted the LSG Bodies 📌 But couldn't find data for wards 😿 
If anyone works, this could be some reference: https://github.com/shrihari689/india-statewise-data/
Data: https://github.com/planemad/india-local-government-directory
💙

**Comment by amruthavijay88** [comment]
Samyuktha. Sandra had a call with Shri Hari on this. They're tagging along as well - on this request.

**Comment by sam9111** [comment]
> Samyuktha. Sandra had a call with Shri Hari on this. They're tagging along as well - on this request.

Yes! Will work together!
