### ISSUE TITLE
Create an option for Voice Recording in consultation updates

### ISSUE THREAD

**Issue by bodhish** [ohcnetwork/care_fe#1047]
This will help doctors taking daily rounds for covid patients to record observations faster and in depth.

**Comment by bodhish** [comment]
Voice recording can be a done with react libraries and for uploads we can use the upload api

**Comment by vigneshhari** [comment]
@bodhish do you want a flag in the file upload backend for voice recordings? can be used for easy filtering

**Comment by sam9111** [comment]
Can we start implementing the front end for this?

**Comment by bodhish** [comment]
That will be great @vigneshhari 

Go ahead @sam9111

**Comment by bodhish** [comment]
You can inspire from this https://codesandbox.io/s/m51n39wy38?file=/src/index.tsx

**Comment by vigneshhari** [comment]
@sam9111 @bodhish 
The backend has a concept of file categories now, you can filter by a category as well, defaults to unspecified. Currently, accepted categories are : UNSPECIFIED, XRAY, AUDIO, IDENTITY_PROOF
Check Swagger docs for more specs.

**Comment by sam9111** [comment]
We have doubts regarding the associating id because we need a way to link each audio file to a consultation update @vigneshhari @bodhish

**Comment by bodhish** [comment]
Once you record audio. You will have an audio file with you. Use the file upload flow to link it to the consultation

**Comment by sam9111** [comment]
shouldn't we be linking it to the consultation update of a consultation?

**Comment by sam9111** [comment]
Doubt resolved with @vigneshhari !

**Comment by bodhish** [comment]
status @sam9111

**Comment by sam9111** [comment]
> status @sam9111 

Almost finished. Ran into some issues with the uploading part but will get it done soon!

**Comment by amruthavijay88** [comment]
Tested, can't find the option to update audio files in 'update consultation'.

![image](https://user-images.githubusercontent.com/67979586/119168685-cc3b0e00-ba7e-11eb-894e-cd16094fca89.png)

**Comment by aparnacoronasafe** [comment]
test failed

Cannot know when the recorder turns on since the timer shows as 00:00
Once uploaded, the file doesn't play

Question: where is the file upload feature now? It is used in the field. please don't take it off!

**Comment by amruthavijay88** [comment]
Tested, shows error when tried over phone.

**Comment by amruthavijay88** [comment]
Tested, works very well on laptop. Shows error when tried over phone - both using Safari and Chrome browsers.

**Comment by aparnacoronasafe** [comment]
works fine on laptop. 

Error in phine, used in Safari and chrome

**Comment by sam9111** [comment]
What errors are you getting? @aparnacoronasafe @amruthavijay88 It's working for me on my mobile chrome browser!
