### ISSUE TITLE
Shifting form: field of facility/ shifting approving facility

### ISSUE THREAD

**Issue by aparnacoronasafe** [ohcnetwork/care_fe#1051]
Please Scope the dropdown menu appearing for 

- Destination Facility: facilities other than shifting centres must be visible

- Shifting approving facility: Only shifting centres to be visible in the drop-down

@amruthavijay88 : Priority 5/5

**Comment by bodhish** [comment]
The issue was only on update. It's now fixed. 

- [X] Shifting approving facility: Only shifting centers to be visible in the drop-down

not doing the other for now.

**Comment by aparnacoronasafe** [comment]
in the assigned facility, I can still see shifting g centres.

**Comment by aparnacoronasafe** [comment]
tested
