### ISSUE TITLE
Telemedicine

### ISSUE THREAD

**Issue by aparnacoronasafe** [ohcnetwork/care_fe#1052]
Even when the telemedicine question on consultation form is changed to no, the doc assigned remains. If that assignment is not separately cleared, the doc assigned stays

 ![image](https://user-images.githubusercontent.com/67050716/118180032-b5c7fd80-b453-11eb-8e9d-eddc4251e524.jpeg)![image](https://user-images.githubusercontent.com/67050716/118180037-b8c2ee00-b453-11eb-9a97-93c4becb3b7c.jpeg)

**Comment by divyagar** [comment]
@aparnacoronasafe @bodhish If `assigned to` depends on `telemedicine` we should show it only if telemedicine is selected to `Yes`. Should I do that?
