### ISSUE TITLE
KASP on patient

### ISSUE THREAD

**Issue by aparnacoronasafe** [ohcnetwork/care_fe#1054]
Please add a "KASP" flag on patient consultation. 

The date on which KASP is enabled must also be made visible.

**Comment by vigneshhari** [comment]
added an is_kasp flag for consultations and a field kasp_enabled_date that is automatically populated based on when kasp was turned on

**Comment by divyagar** [comment]
@bodhish @vigneshhari Should we add kasp fields in patient consultation creation form?

**Comment by bodhish** [comment]
Yes @divyagar
