### ISSUE TITLE
Authentication Failure in Safari

### ISSUE THREAD

**Issue by gigincg** [ohcnetwork/care_fe#1060]
Inventory Management does not fetch data in Safari

To Reproduce, open Inventory Screen in Safari

**Comment by bodhish** [comment]
This looks like an issue with local storage.

**Comment by amruthavijay88** [comment]
@gigincg, @bodhish  - Is this something CEFs could work on?

**Comment by abhinandanarya06** [comment]
I didn't understand when i login in case of chrome, and go to [`http://0.0.0.0:4000/api/v1/users/getcurrentuser/`](http://0.0.0.0:4000/api/v1/users/getcurrentuser/), same authentication failure issue comes.

**Comment by arpancodes** [comment]
Seems to be working for me... without any change.

**Comment by Ashesh3** [comment]
@arpancodes Hey, I tested it on Safari 15.3 and it was not working, on redirects, the Auth header is omitted which leads to some API calls failing.

Where did you test it? Are you sure you used a Safari browser? If so, which version?

![image](https://user-images.githubusercontent.com/3626859/168882769-6f1dd621-0944-4168-8340-b0daa005cc18.png)
![image](https://user-images.githubusercontent.com/3626859/168883039-307acfae-55bd-4846-96ee-17eac5ad14df.png)

**Comment by arpancodes** [comment]
@Ashesh3  tested on 15.4 works fine
![image](https://user-images.githubusercontent.com/42417893/168906614-ae6d7dde-7e58-47d9-ac39-29189eb4b4a9.png)

**Comment by Ashesh3** [comment]
> @Ashesh3 tested on 15.4 works fine ![image](https://user-images.githubusercontent.com/42417893/168906614-ae6d7dde-7e58-47d9-ac39-29189eb4b4a9.png)

That's helpful! I only have versions <=15.3 to test on, Guess it works with 15.4+ . I guess in either case the attached PR would be helpful not only to prevent the unnecessary redirects, but also to add support for <=15.3 Safari versions. Thanks for the additional info!
