### ISSUE TITLE
Bed types simplified

### ISSUE THREAD

**Issue by aparnacoronasafe** [ohcnetwork/care_fe#1061]
Icu: must be renamed to "ICU includes ventilators"

**Comment by amruthavijay88** [comment]
Tested. Comments - 

Dropdown shows -
1. COVID ICU ( ICU without ventilator)
2. COVID Ventilator (ICU with ventilator)

Just checking if # 2 should be COVID ICU(ICU with ventilator)

**Comment by amruthavijay88** [comment]
@bodhish
