### ISSUE TITLE
Consultation update: admitted to

### ISSUE THREAD

**Issue by aparnacoronasafe** [ohcnetwork/care_fe#1062]
In Consultation update , there is a field "admitted to" 

Add option "home isolation" there

**Comment by divyagar** [comment]
@aparnacoronasafe The option is already there.

![Screenshot (196)](https://user-images.githubusercontent.com/42246254/118236927-50582900-b4b4-11eb-92dd-22d51504452c.png)

**Comment by amruthavijay88** [comment]
Tested and verified.

In 'Consultation Updates' - 'Update details', if you click Admitted, the 'Admitted to' dropdown has 'home isolation'.
