### ISSUE TITLE
Listing bed types in order

### ISSUE THREAD

**Issue by aparnacoronasafe** [ohcnetwork/care_fe#1066]
https://care.coronasafe.in/facility/4a5cad7b-7681-48e0-a7a3-a4480fbbc4f4/bed

the form has a dropdown with bed types

The list must appear in the below order
- Non-COVID ordinary beds
- Non-COVID Oxygen bed
- Non-COVID ICU (icu without ventilator)
- Non- COVID ICU (icu with ventilator)
- COVID ordinary beds
- COVID Oxygen bed
- COVID ICU (icu without ventilator)
- COVID ICU (icu with ventilator)
- KASP ordinary beds
- KASP Oxygen bed
- KASP ICU (ICU without ventilator)
- KASP ICU (ICU with ventilator)

**Comment by amruthavijay88** [comment]
Tested - order is not as quoted above - yet.

**Comment by divyagar** [comment]
@aparnacoronasafe @amruthavijay88 Should I remove `hostel` and `single room with attached bathroom` options from `bed type`?

**Comment by aparnacoronasafe** [comment]
@divyagar no divya. lets not delete anything at this point. 

Tested

**Comment by amruthavijay88** [comment]
@aparnacoronasafe - I still see that list is not updated as per your request in this issue. 
Am I missing something?
