### ISSUE TITLE
rename COVID beds to COVID ordinary beds 

### ISSUE THREAD

**Issue by aparnacoronasafe** [ohcnetwork/care_fe#1068]
https://care.coronasafe.in/facility/4a5cad7b-7681-48e0-a7a3-a4480fbbc4f4/bed

https://care.coronasafe.in/facility/4a5cad7b-7681-48e0-a7a3-a4480fbbc4f4

Rename " COVID beds" as "covid ordinary beds"

**Comment by divyagar** [comment]
@aparnacoronasafe I think it's already done.

**Comment by amruthavijay88** [comment]
Tested. 
Requested change is reflecting in the dropdown for 'bed type'.

**Comment by aparnacoronasafe** [comment]
tested
