### ISSUE TITLE
Filter by time : advanced filter : patient list

### ISSUE THREAD

**Issue by aparnacoronasafe** [ohcnetwork/care_fe#1076]
Please add the time option with the Date range option on the advanced filter on the patient list.

Eg: in Created after/ created before/modified after- time 

The backend is already done.

**Comment by sam9111** [comment]
Can I take this up? @bodhish

**Comment by nihal467** [comment]
@aparnacoronasafe is this issue still relevant

**Comment by aparnacoronasafe** [comment]
Not relevant anymore
