### ISSUE TITLE
Cancel button on badge

### ISSUE THREAD

**Issue by divyagar** [ohcnetwork/care_fe#1082]
Create a cancel button on right hand side of filter badge to remove that filter easily.
Like this: 

![Screenshot (197)](https://user-images.githubusercontent.com/42246254/118345887-4b978180-b555-11eb-8d3d-396784d96397.png)

@bodhish Can I do that?

**Comment by amruthavijay88** [comment]
@Apurva-Nagar - Is this a work in progress?

**Comment by aparnacoronasafe** [comment]
@divyagar I think its a good idea

Please do it. 

Removing the "need review" tag
