### ISSUE TITLE
Badge shown even when there is no phone filter applied

### ISSUE THREAD

**Issue by divyagar** [ohcnetwork/care_fe#1083]
![Screenshot (199)_LI](https://user-images.githubusercontent.com/42246254/118346317-2a846000-b558-11eb-8e22-f8f1273707ce.jpg)

**To Reproduce**
1. Go to `patients` tab.
2. Click on cross button on right hand side of `Search by number` filter.

**Comment by khavinshankar** [comment]
@divyagar  are you working on this or can I take this up?

**Comment by divyagar** [comment]
@khavinshankar You can work on this.

**Comment by aparnacoronasafe** [comment]
tested
