### ISSUE TITLE
KASP flag : patient

### ISSUE THREAD

**Issue by aparnacoronasafe** [ohcnetwork/care_fe#1087]
Build a feature to flag KASP on patient.

@bodhish @vigneshhari please suggest if this flag must appear on the patient card/consultation?
- KASP is applied at the time of admission and may hold true for the interval of admission. Therefore it makes sense to have it on the consultation form

**Comment by vigneshhari** [comment]
The flag is currently in consultation, so technically the flag can be shown in both places as far as the backend is concerned.

**Comment by bodhish** [comment]
@aparnacoronasafe KASP is added to consultation

**Comment by aparnacoronasafe** [comment]
tested
