### ISSUE TITLE
Alert blink/ flash about hospitals with less than 5 hours of O2

### ISSUE THREAD

**Issue by Devisha87** [ohcnetwork/care_fe#1089]
**Is your feature request related to a problem? Please describe.**
Could you add a feature that alerts us about O2 quantity when it is 5 hours or less?

**Describe the solution you'd like**
An alert feature in the dashboard 
![Screen Shot 2021-05-15 at 9 06 04 PM](https://user-images.githubusercontent.com/84181195/118369799-6eac4a80-b5c2-11eb-8eea-a3c5bef9d832.png)

**Additional context**

**Comment by khavinshankar** [comment]
@bodhish @aparnacoronasafe can i take this one up?

**Comment by bodhish** [comment]
![image](https://user-images.githubusercontent.com/14979190/118641456-c8498a80-b7f7-11eb-9c3f-41c41af3f19f.png)

**Comment by bodhish** [comment]
missed you msg @khavinshankar

**Comment by bodhish** [comment]
@Devisha87 the issue is now resolved.

**Comment by Devisha87** [comment]
thanks... few more suggestion given.
