### ISSUE TITLE
Shifting outside the district

### ISSUE THREAD

**Issue by aparnacoronasafe** [ohcnetwork/care_fe#1091]
**Problem Statement**
- MOVING TO FACILITY OUTSIDE CARE NETWORK: We have a lot of patients moving out of the district. the operational process right now is, in the shifting request form, the shifting team will simply mark an INVALID FACILITY as the destination and process the shift. The issue is, the patient stays in the live list of the origin facility since no one pulled the card out. Also, currently, we have no data on how many such patients have chosen to move out of the district.
- MOVING TO FACILITY IN CARE NETWORK: In certain cases, the shift will be done to a facility outside the district/state, to a facility registered in CARE. Eg: in the case of Lakshadweep moving patients from their hospital to a hospital in Ernakulam. In this case, also, these shifts must be recognised separately so that the district administration can know how many such shifts have happed over time

**Proposed solution**
The shifting form should have separate flags for INTER-DISTRICT and INTER-STATE shifting. When this Is flagged, the destination field must be made non-mandatory. 

Also, in cases where the destination is not mentioned (where the shift happens to a hospital outside the CARE network), once the shift completes, the patient's card must automatically move to the discharge list of the facility.

**Comment by nihal467** [comment]
@aparnacoronasafe is this issue still relevant

**Comment by sainak** [comment]
This will be handled by https://github.com/coronasafe/care/issues/895
