### ISSUE TITLE
To track oxygen flow within the district

### ISSUE THREAD

**Issue by amruthavijay88** [ohcnetwork/care_fe#1092]
**Is your feature request related to a problem? Please describe.**
We need to be able to have a clear understanding of how Oxygen is divided from the Main suppliers/agencies who receive it within the district - to the lowest end where it's used. Right now, it's manually done and a lot of hoarding happens in between this flow. 

Right now, there're roughly 15 suppliers who get oxygen supply from the state - on an everyday basis. We do get the information on the quantity each supplier gets - from the state. These suppliers give out oxygen to the below categories, however, we do not have a system to capture where it exactly goes further down.
1. Other smaller suppliers
2. Directly to hospitals

They also may have own Oxygen production unit - from which **oxygen cylinders** are filled up, and given out to;
1. Other suppliers
2. Directly to hospitals

**Describe the solution you'd like**
We need to be able to track both liquid oxygen (LMO) and gaseous oxygen(in cylinders) at each main supplier station;
1. Amount received from the state
2. Amount produced
These need to be tracked each day

We need to log - each vehicle that fills (both liquid and gaseous) oxygen from suppliers here, entries are;
1. Quantity of oxygen filled - converted to cubic meter/metric tonne (for liquid oxygen)
2. If it's gaseous oxygen- 
    Fill out the number of cylinders filled up. Also mark the type of cylinder. 
Types of cylinders - 
There are generally 5 cylinder types that we see;
D cylinder - 7 cubic meter
C Cylinder - 2 cubic meter
B Cylinder - 1.5 cubic meter
A Cylinder - 0.71 cubic meter

Ultimately, we need to be able to tally the Oxygen inputted to the district in a day and where it ultimately reached/was used.

**Comment by Devisha87** [comment]
Can we add this to kutti.corona safe app?
