### ISSUE TITLE
Assigning staff for shifting

### ISSUE THREAD

**Issue by aparnacoronasafe** [ohcnetwork/care_fe#1094]
In shifting UI, when i access shifting request for patients and assign shifting staff for them, I see a different list in the drop down menu for patients in different list in shifting UI

Pending list:

<img width="1081" alt="Screenshot 2021-05-16 at 11 35 33 PM" src="https://user-images.githubusercontent.com/67050716/118407690-7b52a080-b69f-11eb-9f0c-27ef918818ae.png">

Awaiting destination approval

<img width="1148" alt="Screenshot 2021-05-16 at 11 36 10 PM" src="https://user-images.githubusercontent.com/67050716/118407720-91606100-b69f-11eb-8694-7d1662117037.png">

Destination approved

<img width="1107" alt="Screenshot 2021-05-16 at 11 36 48 PM" src="https://user-images.githubusercontent.com/67050716/118407739-a76e2180-b69f-11eb-834a-bf6c564b2ca8.png">

**Comment by khavinshankar** [comment]
@aparnacoronasafe  @bodhish 
this is an **expected behaviour,** the staff list is changing because **shifting approving facility** is different. 
The staff list is fetched based on shifting approving facility.

**Comment by aparnacoronasafe** [comment]
Khavin is right
