### ISSUE TITLE
No Limit for Pincode Input Column, during Facility Creation

### ISSUE THREAD

**Issue by nihal467** [ohcnetwork/care_fe#1096]
![error 1](https://user-images.githubusercontent.com/57055998/118408188-0cc31200-b6a2-11eb-82aa-27ef91d49b72.JPG)

When we are creating a facility, there is no limit set for Pincode in the input column. Hence, a facility is created with 8 digit pincodes without showing an error

**Comment by aparnacoronasafe** [comment]
tested
