### ISSUE TITLE
Mandatory Symbol missing in Multiple Field on the Patient Consultation Page

### ISSUE THREAD

**Issue by nihal467** [ohcnetwork/care_fe#1097]
![error 2](https://user-images.githubusercontent.com/57055998/118408765-9247c180-b6a4-11eb-8662-5e3e53b88d3e.JPG)

On the patient consultation page, the following fields: 
       1. Symptoms
       2. date on onset of symptoms
       3. Decision after consultation
are mandatory fields to be filled and it is missing a Mandatory symbol (*)

**Comment by aparnacoronasafe** [comment]
tested
