### ISSUE TITLE
SOS request management system 

### ISSUE THREAD

**Issue by bodhish** [ohcnetwork/care_fe#1105]
Create a system that can log SOS request per facility. All the requests should have multiple statues and updates should be visible to facility and district admins.

A Trello like flow should be super useful here.
Facility can create request
District admin approves / rejects / holds the request 
District admin processes the request
District admin marks the requests as completed
Comment option on thread
Category option 
Mark as emergency

**Comment by bodhish** [comment]
![image](https://user-images.githubusercontent.com/14979190/118437483-56dae080-b700-11eb-93dd-39f6a043b32e.png)

![Uploading image.png…]()

**Comment by aparnacoronasafe** [comment]
Comments are not getting saved. Cannot view it.

Please remove the "Approved facility"

SUGGESTIONS:

- Please make appear the user that updates each of the statuses
- It may be a good idea to add a field for quantity. also, the approved quantity may be different from the requested quantity. May be a good idea to capture that.

**Comment by vigneshhari** [comment]
Duplicate Issue of #1149 , Closing.
