### ISSUE TITLE
KASP not reflecting on dashboard

### ISSUE THREAD

**Issue by Devisha87** [ohcnetwork/care_fe#1108]
**Is your feature request related to a problem? Please describe.**
KASP occupancy is not reflected on the dashboard

**Describe the solution you'd like**
KASP occupancy has to reflect on the dashboard like covid and non-covid
![Screen Shot 2021-05-17 at 3 20 49 PM](https://user-images.githubusercontent.com/84181195/118469774-aaaaf100-b723-11eb-8663-f9455d215fd2.png)

**Comment by aparnacoronasafe** [comment]
@Devisha87 there was KASP visible there before.

then athul sir told us that KASP numbers in hospitals cannot be made public. so we took it off.

You get all this information in the Export on the capacity dashboard.

Please close this issue if you are satisfied with it

**Comment by Devisha87** [comment]
@aparnacoronasafe- Da, this was a requirement that Hema has raised. What you say makes total sense... still, I will confirm this tomorrow with Hema (as well as Dr. Athul) and get back.  Thank you!
