### ISSUE TITLE
Add list of urgent concerns

### ISSUE THREAD

**Issue by Devisha87** [ohcnetwork/care_fe#1117]
![Screen Shot 2021-05-15 at 9 06 04 PM](https://user-images.githubusercontent.com/84181195/118656137-dbfced00-b807-11eb-8471-1343cb034139.png)
Urgent list on the right side corner- say if you can show that 5 hospitals are having urgent concerns for LMO or Jumbo D cylinder... etc

**Comment by bodhish** [comment]
It will be hard to display that list on the right side, the detailed table has an option to filter that should work well 😅

**Comment by Devisha87** [comment]
...but we discussed this right.. we will be able to show the number of hospitals on high alert... alle?

**Comment by bodhish** [comment]
Fixed 

![image](https://user-images.githubusercontent.com/14979190/119883094-c34daf00-bf4c-11eb-9224-d40107c4894a.png)
