### ISSUE TITLE
Create Staff: hide local body field

### ISSUE THREAD

**Issue by aparnacoronasafe** [ohcnetwork/care_fe#1119]
While creating new staff user we do not need to capture the local body. Please hide the field

https://care.coronasafe.in/user/add

**Comment by khavinshankar** [comment]
@aparnacoronasafe 
There are about 9 user types,
- Volunteer
- Pharmacist
- Staff
- StaffReadOnly
- Doctor
- WardAdmin
- LocalBodyAdmin
- DistrictReadOnlyAdmin
- DistrictAdmin

So we need to hide it for user types, Staff and StaffReadOnly right?

**Comment by amruthavijay88** [comment]
Tested, verified that when a new staff is created - local body isn't mandatory now.

**Comment by aparnacoronasafe** [comment]
tested
