### ISSUE TITLE
Add location picker to Facility Add

### ISSUE THREAD

**Issue by dauntlessnomad** [ohcnetwork/care_fe#112]
add a location picker using leaflet to populate latitude and longitude text fields

**Comment by AbhiramProbodhagan** [comment]
I took this

**Comment by dauntlessnomad** [comment]
#104

**Comment by SandeepThomas** [comment]
Can we have a feature to search by location within the map? In the current implementation, it is difficult to select the accurate lattitude/longitude. @AbhiramProbodhagan

**Comment by SandeepThomas** [comment]
few bugs in this now

- map not visible in mobile
- after search and select or clicking on map - no pointer shown on map
