### ISSUE TITLE
Vaccination: patient list: advanced filter

### ISSUE THREAD

**Issue by aparnacoronasafe** [ohcnetwork/care_fe#1121]
In the Vaccination advanced filter for the patient list, the options are vaccinated/ unvaccinated.

Please change the options to
- Unvaccinated
- 1st dose only
- both doses

**Comment by Sandra3657** [comment]
Is it possible to pass number of doses as a parameter for the patients list api? @vigneshhari

**Comment by amruthavijay88** [comment]
Tested, failed. In the vaccination advanced filter for the patient list, the options are still - vaccinated/ unvaccinated. Requested options is not reflected.

**Comment by aparnacoronasafe** [comment]
tested

**Comment by amruthavijay88** [comment]
Tested, verified

**Comment by bodhish** [comment]
@aparnacoronasafe this looks working for me

**Comment by aparnacoronasafe** [comment]
tested
