### ISSUE TITLE
ERROR_Showing high LMO in the district

### ISSUE THREAD

**Issue by Devisha87** [ohcnetwork/care_fe#1124]
![PHOTO-2021-05-20-11-54-27](https://user-images.githubusercontent.com/84181195/118929851-aae4ff80-b962-11eb-8bed-2ae76233d8cc.jpg)

The issue is that the dashboard shows LMO level to be extremely high...  the issue is due to the calculation error found with little flower hospital.  The total add stock is 2648 and the total use stock is 2194 and so the current stock is 454.

When we export the dashboard the value comes as 771800.

**Comment by bodhish** [comment]
Fixed
