### ISSUE TITLE
preview for file upload

### ISSUE THREAD

**Issue by aparnacoronasafe** [ohcnetwork/care_fe#1135]
Now for file upload on patient card and consultation, the user must download it to view it.

Can we have a preview option to view it, even a low resolution preview should do

**Comment by peeyush14goyal** [comment]
@bodhish @aparnacoronasafe @vigneshhari 
![image](https://user-images.githubusercontent.com/42883572/119256117-adeb2480-bbdc-11eb-8774-bd7ec5180341.png)
![image](https://user-images.githubusercontent.com/42883572/119256130-be030400-bbdc-11eb-9d5f-0557991616f1.png)
![image](https://user-images.githubusercontent.com/42883572/119256137-c9eec600-bbdc-11eb-8226-48acae51c97b.png)
![image](https://user-images.githubusercontent.com/42883572/119256143-d410c480-bbdc-11eb-91a2-e858579097f1.png)
![image](https://user-images.githubusercontent.com/42883572/119256149-decb5980-bbdc-11eb-8450-d7ade38f1c11.png)

**Comment by peeyush14goyal** [comment]
Txt, pdf, image, video, files are all visible in browser. Above are some snapshots. Is this good?

**Comment by peeyush14goyal** [comment]
Files like excel, .doc, .docx extension are downloaded only.

**Comment by amruthavijay88** [comment]
tested - it says the content is blocked, contact site owner to fix the issue.

**Comment by peeyush14goyal** [comment]
Have you tried with the new file? Coz it will work for newly uploaded files only. The files uploaded after this code merging

**Comment by peeyush14goyal** [comment]
Yes this is the error coming up 
![image](https://user-images.githubusercontent.com/42883572/119296574-d889bb80-bc76-11eb-91e7-147f48166040.png)
@bodhish

**Comment by bodhish** [comment]
@peeyush14goyal can you add a download file button along with the preview.

**Comment by peeyush14goyal** [comment]
@bodhish I'll check about download button. Can you please review and merge #1176 ?

**Comment by dauntlessnomad** [comment]
> 
> 
> Yes this is the error coming up
> ![image](https://user-images.githubusercontent.com/42883572/119296574-d889bb80-bc76-11eb-91e7-147f48166040.png)
> @bodhish

this is fixed

**Comment by dauntlessnomad** [comment]
@peeyush14goyal blocked by client error is some browser addon blocking the tracking beacons

**Comment by bodhish** [comment]
@peeyush14goyal #1176 may not be required

We set our CORS policy at nginx level

**Comment by peeyush14goyal** [comment]
@bodhish @tomahawk-pilot Ok.  I just checked in staging its working.  ✅. 




> @peeyush14goyal blocked by client error is some browser addon blocking the tracking beacons

Can you tell me more about this ?

**Comment by amruthavijay88** [comment]
@bodhish @tomahawk-pilot - please could you address Peeyush's doubt.

**Comment by aparnacoronasafe** [comment]
tested
