### ISSUE TITLE
Show error messages in the notfication.

### ISSUE THREAD

**Issue by bodhish** [ohcnetwork/care_fe#114]
Parse and show error messages from the notification response.

1. 400 Bad Request - show fields 
2. Other 4xx errors - Show the message from response (detail key in response)
3. 5xx errors - Show static error message

400 Bad Request format
```
{
  field1: [
      "error msg 1",
      "error msg 2"
   ],
  field2: [
    "error 3"
   ]
}
```

Other 4xx error response format
```
{
    "detail": "Given token not valid for any token type",
    "code": "token_not_valid",
    "messages": [{
        "token_class": "AccessToken",
        "token_type": "access",
        "message": "Token is invalid or expired"
    }]
}
```
Add Pnotiy to manage notification and replace all usages of AppMessage with pnotify.
https://sciactive.com/pnotify/

Handle all errors in fireRequest.tsx

**Comment by lijujohn13** [comment]
@bodhish Please add more details into this issue.I couldnot find which notification component needs the change.

**Comment by bodhish** [comment]
Hey @lijujohn13. 
example: Check the ambulance regestraion form. 

If an ambulance is registered, the server will responsd wiht error message. 
We are ignoring that error message which says the reason for the error message. 

This should be shown to the user. 

You can add Pnotiy to manage notification
https://sciactive.com/pnotify/

Ideally replace all usages of `AppMessage` with `pnotify`

**Comment by lijujohn13** [comment]
But for this to be implemented across the application, we need to have consistent api responses..
This is the error response for ambulance creation.
> {"vehicle_number":["ambulance with this vehicle number already exists."]}

If we have a consistent format for errors across the api's , we can have a parser to capture errors and show the notifications at application root level.Currently, the Appmessage component is being used in multiple components to show error, which isn't ideal.

**Comment by bodhish** [comment]
@vigneshhari @biswaz @tomahawk-pilot 

Can we unify the error response?

**Comment by melvin2016** [comment]
Pnotify has been added in a previous PR.

**Comment by SandeepThomas** [comment]
@melvin2016 will you be working on the error handling part?

**Comment by melvin2016** [comment]
@SandeepThomas Yes, I'm working on this. I will make a PR soon.
