### ISSUE TITLE
Total capacity - bed category arrangement

### ISSUE THREAD

**Issue by amruthavijay88** [ohcnetwork/care_fe#1141]
**Describe the bug**
Currently - the way bed categories are displayed within a facility dashboard is like below - 

![image](https://user-images.githubusercontent.com/67979586/119141068-76f10380-ba62-11eb-8f1d-5acfd187e686.png)

**Expected behavior**
Please display bed types in the below order;

First Row: Non-Covid Ordinary beds, Non-Covid Oxygen beds, Non-Covid ICU, Non-Covid Invasive Ventilator, Non-Covid Non invasive ventilator

Second Row: Covid Ordinary beds, Covid Oxygen beds, Covid ICU, Covid Invasive Ventilator, Covid Non-invasive ventilator

Third Row: KASP Ordinary beds, KASP Oxygen beds, KASP ICU, KASP Invasive Ventilator, KASP Non-invasive ventilator

The additional bed types can come in the fourth row. By this change - field staff will be able to take note of relevant information on beds easily.

**Comment by Sandra3657** [comment]
Can me and @sam9111 take it up? @amruthavijay88

**Comment by amruthavijay88** [comment]
Yes please.

**Comment by amruthavijay88** [comment]
Tested, failed. 

Order still seems to be off - 

![image](https://user-images.githubusercontent.com/67979586/119171716-91d37000-ba82-11eb-853f-682eed5eba33.png)

**Comment by peeyush14goyal** [comment]
@amruthavijay88 Have you checked in staging? The PR is not merged yet so changes won't be there now

**Comment by amruthavijay88** [comment]
Please don't update 'need review' until PR is merged, yeah checked in staging. I didn't check if it was merged or not @peeyush14goyal

**Comment by peeyush14goyal** [comment]
Ok

**Comment by aparnacoronasafe** [comment]
test failed

**Comment by amruthavijay88** [comment]
Test failed - order is still mixed up.

**Comment by peeyush14goyal** [comment]
@bodhish PR is not merged yet. @gigincg  has not replied yet in PR

**Comment by amruthavijay88** [comment]
Tested, verified.

**Comment by aparnacoronasafe** [comment]
tested
