### ISSUE TITLE
Unit of oxygen capacity in a facility

### ISSUE THREAD

**Issue by amruthavijay88** [ohcnetwork/care_fe#1142]
As liquid oxygen capacity is usually communicated in Kilo Liters by the field staffs, it would be ideal to have its capacity in KL - in facility's info. Otherwise it creates confusion for them.

![image](https://user-images.githubusercontent.com/67979586/119143332-1e6f3580-ba65-11eb-9e12-e3194897bf27.png)

**Comment by sam9111** [comment]
Does the liquid oxygen capacity get recorded as KL or L in the backend or should we be doing that?

**Comment by amruthavijay88** [comment]
As discussed, operationally this may create an issue in older data - even if field team promises to correct that. Closing cos of this..
