### ISSUE TITLE
Error when creating a user ID

### ISSUE THREAD

**Issue by nihal467** [ohcnetwork/care_fe#1143]
![aaa](https://user-images.githubusercontent.com/57055998/119145584-698a4800-ba67-11eb-8a5d-99f33e82c685.JPG)

A user ID ending in digits cannot be created. But, this is not specified in the conditions given under the field.

**Comment by amruthavijay88** [comment]
Tested, failed. Error message still doesn't include mentioning - should not end with 'numeric digit'

![image](https://user-images.githubusercontent.com/67979586/119172346-75840300-ba83-11eb-941a-9fcb0a4339f6.png)

**Comment by aparnacoronasafe** [comment]
test failed

**Comment by gigincg** [comment]
This should be working when @vigneshhari merges the change

**Comment by aparnacoronasafe** [comment]
tested

**Comment by amruthavijay88** [comment]
tested, verified.
