### ISSUE TITLE
Alarm turned on - when there's no cylinder capacity

### ISSUE THREAD

**Issue by amruthavijay88** [ohcnetwork/care_fe#1146]
In dashboard, when we look at each facility - for oxygen, when the time to empty is nearing, there is a red circle alarm. This is turned on even when the cylinder capacities are zero.

![image](https://user-images.githubusercontent.com/67979586/119157332-b6275080-ba72-11eb-9fcf-9e9547bdae3c.png)

**Comment by sam9111** [comment]
Should the alarm also be switched off when it is 0/n cylinders? @amruthavijay88

**Comment by sam9111** [comment]
Created a PR in the dashboard repo which for now ensures that if cylinder capacity is 0 there is no alarm

**Comment by bodhish** [comment]
Fixed
