### ISSUE TITLE
Death Report

### ISSUE THREAD

**Issue by aparnacoronasafe** [ohcnetwork/care_fe#1147]
The patients that are marked as expired must have a death report. this report may be shared with the user over email (like discharge summary) or as a file that can be downloaded (life the shifting referral form).

PLEASE ALLOW THE USER TO DOWNLOAD THE REPORT AND THEN EDIT IT. 
Since usually, authorities require the signature of the authorised staff, the staff must be able to make changes (edit or add more information) 

since a few fields are not there in the systems, the user must be able to fill them in the file. 

Please find the format of the death report in the coronasafe drive at https://drive.google.com/drive/folders/1TUqwkPtdm5VvQDZlvFgLzN9dvpkA8HeT?usp=sharing

(please get in touch with @aparnacoronasafe for access)

**Comment by aparnacoronasafe** [comment]
@bodhish question.

There are a few fields on page 2 not captured. Should we add a pop-up window, like for Patient status "negative" and capture all info on care.

suggest the best way forward

**Comment by amruthavijay88** [comment]
@Apurva-Nagar - could you please update us on the status of this request.

**Comment by Apurva-Nagar** [comment]
> 
> 
> @Apurva-Nagar - could you please update us on the status of this request.

The basic functionality is now complete.

**Comment by amruthavijay88** [comment]
Tested - looks okay to me.

**Comment by aparnacoronasafe** [comment]
tested
