### ISSUE TITLE
assigning volunteer to patient

### ISSUE THREAD

**Issue by aparnacoronasafe** [ohcnetwork/care_fe#1148]
Any volunteer in the facility may be assigned to a patient. 

This can be done by any staff or the district administrator. Have the option on the patient dashboard.

once a volunteer is assigned to a patient, he should be able to assign a doctor to the patient or edit the patient details.

The volunteer must also be able to filter out only the patients assigned to him in the patient list

**Comment by vigneshhari** [comment]
@bodhish backend is done, permission scopes are not yet built but the API fields are done, build this out in the front end and i will add the required Permissions scopes on the fly.

**Comment by divyagar** [comment]
@aparnacoronasafe Do you want this option in patient dashboard or in patient form?
If this option will be in patient dashboard then a popup will appear where user can search and select volunteer to be assigned.
And if this is in form, there will be no popup. They can enter directly.

**Comment by aparnacoronasafe** [comment]
I think it would be better on the dashboard

**Comment by bodhish** [comment]
It should be in the dashboard
