### ISSUE TITLE
Resources Module

### ISSUE THREAD

**Issue by aparnacoronasafe** [ohcnetwork/care_fe#1149]
- it is important to record the type of oxygen required. Therefore, in the category, instead of just "Oxygen" can we specify the type of oxygen?

- there must be a field to note quantity.

- Once the request is approved, while approving the user must be able to input the quantity approved, which may be different from the quantity requested. 

- also a new facility type for "resource managers" like shifting centre needs to be added. two staff type for "resource approving staff" and "resource acquisition staff"

@bodhish

**Comment by aparnacoronasafe** [comment]
related issue 1105

**Comment by aparnacoronasafe** [comment]
@vigneshhari the resource fulfilling facility has no permission to change status

**Comment by vigneshhari** [comment]
@aparnacoronasafe what all status should they have permission for?

**Comment by aparnacoronasafe** [comment]
List of permission already shared. 

Unresolved issues are taken out in separate issues

closing this issue
