### ISSUE TITLE
District admin (read only)- URGENT!!!

### ISSUE THREAD

**Issue by aparnacoronasafe** [ohcnetwork/care_fe#1152]
The district read-only user is unable to see the data in the inventory module and data on facility info capacity etc. Needs to be corrected ASAP

**Comment by bodhish** [comment]
@vigneshhari

**Comment by amruthavijay88** [comment]
Tested, failed. The District read only admin cannot view inventory details, capacity etc.

**Comment by aparnacoronasafe** [comment]
tested in staging
