### ISSUE TITLE
medicines list: addition: prescription module

### ISSUE THREAD

**Issue by aparnacoronasafe** [ohcnetwork/care_fe#1153]
Please add the following medicines as options to the prescription module

[MED INVOICE.docx](https://github.com/coronasafe/care_fe/files/6524984/MED.INVOICE.docx)

(Please ignore the headings. Only the medicines in the list needs to be added)

**Comment by khavinshankar** [comment]
@bodhish please do review this pr (https://github.com/coronasafe/prescription-builder/pull/20)

**Comment by khavinshankar** [comment]
@bodhish Is the recent changes in the prescription_builder published to npm?

**Comment by bodhish** [comment]
Fixed
