### ISSUE TITLE
Date of admission on KASP referral form

### ISSUE THREAD

**Issue by aparnacoronasafe** [ohcnetwork/care_fe#1157]
The date of admission shown on KASP referral form must be the admission date recorded on the consultation form.

The date that appears now is the date that the consultation was filed on

**Comment by peeyush14goyal** [comment]
@aparnacoronasafe Can you give some patient names where it is wrong? The ones I checked had the correct date and also there are some patients whose referral letter is there but patient details are not found

**Comment by amruthavijay88** [comment]
Tested, verified that the admission date in consultation form is reflected in the referral letter.

**Comment by aparnacoronasafe** [comment]
tested
