### ISSUE TITLE
Resource: for inter-district oxygen request

### ISSUE THREAD

**Issue by aparnacoronasafe** [ohcnetwork/care_fe#1158]
- Create a new facility type: "District war room"

@bodhish

**Comment by aparnacoronasafe** [comment]
tested. approved

**Comment by amruthavijay88** [comment]
tested - but do we need to take off options to choose bed types, oxygen etc for this category ? @bodhish

**Comment by bodhish** [comment]
Ignore

**Comment by amruthavijay88** [comment]
okay..
