### ISSUE TITLE
Treatment based on symptom

### ISSUE THREAD

**Issue by aparnacoronasafe** [ohcnetwork/care_fe#1159]
Must be able to filter patients by "Date of Onset of symptoms". This date is DAY 1- symptoms must be captured accurately

DAY 6/7: Review must be done at least once. 

need to fetch a list of patients where review has not happened in day 6/7.

If symptomatic on the 7th day or after, the medication that must be prescribed are:
- Dexamethesone
- Methylprednisolone (to add to list of medicines)
- Prednisolone
- Buxinside (to add to list of medicines)

plus/minus

- apixaban (to add to list of medicines)
- rivaroxaban (to add to list of medicines)
- low molecular weight heparan (to add to list of medicines)
- Heparan (to add to list of medicines)
- Dabigatran (to add to list of medicines)

**Comment by nihal467** [comment]
@aparnacoronasafe is this issue still relevant

**Comment by bodhish** [comment]
This is very specific to covid, closing the issue
