### ISSUE TITLE
facility can see shift that they are not tagged in

### ISSUE THREAD

**Issue by aparnacoronasafe** [ohcnetwork/care_fe#1160]
<img width="1134" alt="Screenshot 2021-05-22 at 7 27 19 PM" src="https://user-images.githubusercontent.com/67050716/119229095-e1be3f80-bb33-11eb-8a0c-c49d07513e84.png">

This is the shifting board of AGCH - ASTER MEDCITY

They can see the shifts that they are not a party to. 

NOTE: These patients whose card are seem here eventually landed in  AGCH - ASTER MEDCITY, but not through shifting. There cards were imported by entering the phone number and date of birth

**Comment by vigneshhari** [comment]
They have access to the patient thats why they can see their shifting records. This is not a bug, its a feature.

**Comment by aparnacoronasafe** [comment]
@vigneshhari tested. you are right. But i don't understand relevance of it
