### ISSUE TITLE
Staff user can create staff without linking any facility

### ISSUE THREAD

**Issue by aparnacoronasafe** [ohcnetwork/care_fe#1161]
Staff can now create a new staff with no facility attached. This leads to a lot of new duplicate facilities being registered.

Please allow staff to only create staff linked to at least one of the facility he/she is linked to.

**Comment by sam9111** [comment]
Can this be implemented in the front end? @bodhish

**Comment by bodhish** [comment]
@sam9111 yes. If the current user is staff they should specify a facility

**Comment by sam9111** [comment]
So the staff user being created should belong to **at least** one of the facilities the current staff user belongs to right? @aparnacoronasafe @bodhish

**Comment by aparnacoronasafe** [comment]
@sam9111 . yes correct
