### ISSUE TITLE
Allow facilities to set breathlessness level

### ISSUE THREAD

**Issue by bodhish** [ohcnetwork/care_fe#1163]
Allow facilities to set breathlessness_level in shifting board

**Comment by aparnacoronasafe** [comment]
origin facility can now enter breathlessness level. However, they cannot edit it. 

@bodhish

**Comment by amruthavijay88** [comment]
Tested, origin facility can update breathlessness level. However, when you try to save without updating breathlessness, it doesn't let you save - but no warning is displayed.

**Comment by aparnacoronasafe** [comment]
@bodhish

**Comment by amruthavijay88** [comment]
tested, verified -
1. Warning appears
2. Base facility can edit breathlessness status.

**Comment by aparnacoronasafe** [comment]
tested
