### ISSUE TITLE
Alert missing in investigation report

### ISSUE THREAD

**Issue by nihal467** [ohcnetwork/care_fe#1166]
![error 1](https://user-images.githubusercontent.com/57055998/119256642-44b8e080-bbdf-11eb-9b6e-8dd5b39d1f23.JPG)

Even if a user has not added anything in the investigation report, there isn't an alert that says no data is available.

**Comment by amruthavijay88** [comment]
Tested, verified that alert comes up saying 'no data available'

**Comment by aparnacoronasafe** [comment]
tested
