### ISSUE TITLE
Error in Updating test results

### ISSUE THREAD

**Issue by nihal467** [ohcnetwork/care_fe#1167]
![error 2](https://user-images.githubusercontent.com/57055998/119256778-f7893e80-bbdf-11eb-8d35-1c16a3d81b52.JPG)

When you update a patient's test result as 'awaiting' and then save it, there isn't a way to update it as 'positive' or 'negative' later on.

**Comment by Sandra3657** [comment]
Completed the FE. But there is some issue with sending the request. It is probably a backend issue. Looking into it.

**Comment by vigneshhari** [comment]
What exactly is the issue. need more specifics

**Comment by Sandra3657** [comment]
When the current status is TEST COMPLETED and result is AWAITING, the api request for updating the result from AWAITING to POSITIVE/NEGATIVE is not allowed. @vigneshhari

**Comment by nihal467** [comment]
when we receive a sample test request

Step 1: On Sample test, Click 'Update Sample test status', and Set New Status as 'Approved for Sample Collection'
Step 2: Click 'Update Sample test status', and Set New Status as 'Test Completed' and Result as 'Await'.

Once we save the result as Await, the final report is generated. Which, lead to a situation where we can't update the patient test result from 'Await' to Positive or negative

@vigneshhari

**Comment by vigneshhari** [comment]
@Sandra3657 this is a UI issue, the backend allows editing values from awaiting to positive/negative, i just cross confirmed it with postman, if you are still getting the error, post the curl request that fails and i can take a look.

**Comment by amruthavijay88** [comment]
When we select 'test completed' and click 'awaiting' - there is no option to update it as positive/negative later.
