### ISSUE TITLE
Assigning doctors : dropdown URGENT!!!

### ISSUE THREAD

**Issue by aparnacoronasafe** [ohcnetwork/care_fe#1168]
The dropdown for assigning doctors only shows 15 Items in the drop-down.

please fix the same. 

@vigneshhari

**Comment by khavinshankar** [comment]
@aparnacoronasafe there are only 15 doctors registered in dev deployment (testing)...

**Comment by amruthavijay88** [comment]
Tested adding a new doctor, shows up in the existing list. However, searching by name is tough @aparnacoronasafe - your thoughts?

**Comment by aparnacoronasafe** [comment]
@amruthavijay88 file it as a separate issue and close this one please

**Comment by amruthavijay88** [comment]
Okay @aparnacoronasafe .
Tested, verified.
