### ISSUE TITLE
UGRENT: Inventory management_ editing option required for district admin 

### ISSUE THREAD

**Issue by Devisha87** [ohcnetwork/care_fe#1178]
There is an editing option in the inventory log for district admin whether it be: Add stock or used stock. Incorrect addition and changes made to adjust the same are creating issues to get the correct burn rate. 

![WhatsApp Image 2021-05-24 at 3 55 12 PM](https://user-images.githubusercontent.com/84181195/119334335-a1340280-bca8-11eb-8d46-630c3d093a3f.jpeg)

![apolo](https://user-images.githubusercontent.com/84181195/119333380-6bdae500-bca7-11eb-9c77-fac671ed2ce7.jpg)
![WhatsApp Image 2021-05-24 at 3 53 24 PM](https://user-images.githubusercontent.com/84181195/119334322-9da07b80-bca8-11eb-8e58-5882e95b249e.jpeg)

There should be an editing module in log.

**Comment by sam9111** [comment]
@aparnacoronasafe Can I take this up?

**Comment by aparnacoronasafe** [comment]
@sam9111 this is already resolved by adding a "mark as mistake" option on the inventory log.
