### ISSUE TITLE
Create dashboard for district admin

### ISSUE THREAD

**Issue by bodhish** [ohcnetwork/care_fe#119]
The district admin should be able to view all the facilities listed in a district

**Comment by bodhish** [comment]
District admin should be able to see all facilities and allow allow all other actions 

Should be able to approve samples (separate dash)

Dashboard should have summary of facilities

**Comment by dauntlessnomad** [comment]
the summary thing is a table enough with data from all the facilities in the district ? @anroopak @afzalIbnSH do you have a api for this . refer https://github.com/coronasafe/care/issues/127

**Comment by dauntlessnomad** [comment]
#143
