### ISSUE TITLE
Add a form to onboard ambulance

### ISSUE THREAD

**Issue by bodhish** [ohcnetwork/care_fe#12]
# Vehicle Details 
- Vehicle Registration Number: string (validation: A-Z and 0-9 (Alpha numeric only))
- Insurance Valid till: date (validation- year should one of 2020 / 2021 / 2022)
- Name of Owner: string
- Cell Number of Owner: number (10 digit mobile number)
- Smart Phone: bool  
- Primary District Served: District.id
- Secondary District Served: District.id
- Third District Served: District.id
- Oxygen Yes / No
- Ventilator Yes / No
- Suction Machine Yes / No
- Defibrillator Yes / No

## Driver Details
Name of Driver 1
Cell Number of Driver 1
Smart Phone Yes / No

## Driver Details
Name of Driver 2
Cell Number of Driver 2
Smart Phone Yes / No

Related Backend Issue https://github.com/coronasafe/care/issues/63

**Comment by dauntlessnomad** [comment]
- [x]  Stepper Component - Common Componet -> @GodlyCeegees 

- [x] Vehicle Comoponent -> @aravindjr 

- [x]  Driver Component -> @akshaykumar-m-s
