### ISSUE TITLE
Patient: stale consultation is open

### ISSUE THREAD

**Issue by aparnacoronasafe** [ohcnetwork/care_fe#1202]
https://care.coronasafe.in/facility/4a5cad7b-7681-48e0-a7a3-a4480fbbc4f4/patient/b9dcd3f7-b31c-4dfb-936b-b62b5cfcc4cd

The patient moved to a new hospital, but somehow his old consultation is still open. So the new hospital is unable to file new consultation because the error " consultation alteady exists, please update the same" comes

**Comment by divyagar** [comment]
@aparnacoronasafe Is this patient shifted? Because there is no shifting details in `Shifting` section.
![image](https://user-images.githubusercontent.com/42246254/119592485-3264bf80-bdf6-11eb-81a1-f1074706fcce.png)
