### ISSUE TITLE
Resource request_few additions

### ISSUE THREAD

**Issue by Devisha87** [ohcnetwork/care_fe#1204]
![IMG-20210525-WA0069](https://user-images.githubusercontent.com/84181195/119448484-07736080-bd4f-11eb-82d6-5173ddbbecd9.jpg)

-Didn't understand what is request title...

-Multiple requests come in usually... cant we capture that in one single request.
Quantity cannot be mentioned now- on the side of the subcategory we require the quantity with unit option. 
Approval- require us to mention what all we can provide. So, a comment box to fill in what is approved will be helpful. If this option is already there, then it is okay.

**Comment by aparnacoronasafe** [comment]
@Devisha87 adding quantity to the form.  there will be a requested quantity and an approved quantity

Let us first get the minimum viable version out.
