### ISSUE TITLE
Add Resource Quantity in request form

### ISSUE THREAD

**Issue by dauntlessnomad** [ohcnetwork/care_fe#1207]
Add required oxygen in the resource form so that we can collect the oxygen requirement from the hospitals accuratly. 
also display this in a highlighted view.

**Comment by dauntlessnomad** [comment]
there is a priority object in the api. 
please add an option to assign it in the ui.

**Comment by dauntlessnomad** [comment]
Please add the resource approving user as well. to show log

**Comment by vigneshhari** [comment]
The backend already supports requested amounts and assigned amounts in the API, currently, there is no access scoping can build that later on

**Comment by Sandra3657** [comment]
What values can priority take? I see that it is an integer in the API. @bodhish

**Comment by Sandra3657** [comment]
There are no data for resource approving users, right? In the API, only details for resource approving facilities can be seen. @vigneshhari
