### ISSUE TITLE
Treatment summary 

### ISSUE THREAD

**Issue by aparnacoronasafe** [ohcnetwork/care_fe#1212]
[interim treatment summary.pdf](https://github.com/coronasafe/care_fe/files/6546104/interim.treatment.summary.pdf)

An option to download a treatment summary must appear on the live consultation

The format must be strict as the attached doc. 

Most field there are self-explanatory. A few are explained below:
- Date of admission, must be the date of admission in that facility, i,e, in that consultation
- Date of positive must be the date the patient turned positive which could be before the admission
- Date of negativity may be left blank if the patient has not turned negative yet
- Comorbidities is captured in "Any medical history" in patient registration form
- Diagnosis, must include "History of present illness", "Examination details and Clinical conditions" and "Diagnosis" from the consultation form. It must also include "Physical Examination Info" from the consultation update. 
- Treatment summary includes 
                                 - table of "date and SPO2, temperature from consultation update
                                 - treatment summary from the consultation page. 

This interim treatment summary must preview on the system like the KASP referral letter in shifting and must be available to download as PDF

**Comment by divyagar** [comment]
@aparnacoronasafe @bodhish  Last consultation is the live consultation right?

**Comment by aparnacoronasafe** [comment]
@divyagar yes

**Comment by amruthavijay88** [comment]
Tested. 'Examination details and Clinical conditions' were missing in the print out version - though it was updated.
