### ISSUE TITLE
"Something went wrong" User

### ISSUE THREAD

**Issue by aparnacoronasafe** [ohcnetwork/care_fe#1215]
https://care.coronasafe.network/users#

<img width="1397" alt="Screenshot 2021-05-26 at 4 54 13 PM" src="https://user-images.githubusercontent.com/67050716/119651821-03c10600-be43-11eb-86d1-6ad681984f60.png">

When clicking on "Click here to show facility" "something went wrong" comes up

**Comment by vigneshhari** [comment]
Please provide more context for issues like this, which user type, why this is being used, can you replicate it on staging, and so on without that we cant really do anything.

**Comment by samholics** [comment]
@vigneshhari 

I used district admin login

The issue is not found in all user but only random ones.

**Comment by vigneshhari** [comment]
The user has the (dot) in the username, kindly create a new user whenever they have dots "." in their username.
