### ISSUE TITLE
filter in shifting

### ISSUE THREAD

**Issue by aparnacoronasafe** [ohcnetwork/care_fe#1216]
To recreate:

1) A filter in shifting is applied, eg: KASP yes, the result comes up and the flag for filter appears on top of the list 
2) Another tab, eg: user tab is accessed
3) user comes back to the shifting tab, the filter is gone and the user can see all the data available.
4) The user wants to apply another filter like Upshift/downshift. However, when the advanced filter panel is taken, the last filter i.e KASP is already auto-populated. when the user clicks apply, both the filters are applied while the user wanted only one filter (upshift/downshift).

**Comment by divyagar** [comment]
@aparnacoronasafe There can be 2 things that can happen when user move back to the shifting tab :
1. The filters applied earlier should remain and their respective badge should appear.
2. All the filters applied earlier should be removed.

Which one do you want?

**Comment by aparnacoronasafe** [comment]
option 2 would be better @divyagar

**Comment by divyagar** [comment]
@bodhish If we want to keep localstorage then I think first option is the only option we have. should I go with first option then? Or is there any other solution?
