### ISSUE TITLE
KASP approving authority

### ISSUE THREAD

**Issue by aparnacoronasafe** [ohcnetwork/care_fe#1217]
In the KASP referral letter, the bottom right of the document has

"Signature of doctor
Name and designation "

Please replace this with "Approved by District COVID Control Room"

**Comment by Apurva-Nagar** [comment]
@aparnacoronasafe Is the KASP referral letter the same as the referral letter we get for shifting?

**Comment by aparnacoronasafe** [comment]
@Apurva-Nagar yes you are right
