### ISSUE TITLE
Missing fields in Death Form.

### ISSUE THREAD

**Issue by Apurva-Nagar** [ohcnetwork/care_fe#1224]
The death form currently has the following fields missing:

- Date of death
- Cause of death
- Whether brought dead
- Brought from home/CFLTC
- NIV/IUBCR sent
- NIV/IUBCR date
- Date of admission
- Hospital in which tested positive
- History and clinical course in the hospital

**Comment by smartclash** [comment]
Hey @Apurva-Nagar, did you fix this issue at PR #1188 ?

**Comment by Apurva-Nagar** [comment]
> 
> 
> Hey @Apurva-Nagar, did you fix this issue at PR #1188 ?

We don't have this data. These fields need to be added on the backend, we can then create a form to take in these information and populate the death report.

**Comment by smartclash** [comment]
Added appropriate labels to indicate this issue. Thanks @Apurva-Nagar :)

**Comment by vigneshhari** [comment]
This does not involve the backend, the data is not stored in the backend, the data just needs to be rendered into the file.
