### ISSUE TITLE
Indian Languages Translation Status

### ISSUE THREAD

**Issue by shrihari689** [ohcnetwork/care_fe#1226]
From #232 📍 we now have Localization for our project 🎉

Let's keep this issue to track all of our existing modules to be translated 🏀

Currently, there are only some modules in which the string are extracted and put into i18n 🚀

📜 Docs:  https://github.com/coronasafe/care_fe/wiki

We have to extract all strings and put into i18n, so that it can be translated by the community easily without touching the code 😁 🚀

**Comment by rithviknishad** [comment]
@gigincg @shrihari689 closing this as an EPIC for the same is being tracked in #4467
