### ISSUE TITLE
Enhancement of file preview

### ISSUE THREAD

**Issue by aparnacoronasafe** [ohcnetwork/care_fe#1232]
https://care.coronasafe.in/facility/c2d37a3e-3b82-4a12-881f-5faca5a44134/patient/18c2290d-4084-4bab-bef1-17526a2ce1be/consultation/36ca2fad-f80a-4aee-93a1-972d4a7a2a76/files/

When an image file of a very large size is previewed, only a portion of it is visible first.

is it possible to make the image fit the frame, and give the option to the user to zoom in. 

@peeyush14goyal would you like to continue working on the preview?

**Comment by peeyush14goyal** [comment]
Yes

**Comment by peeyush14goyal** [comment]
@aparnacoronasafe Zoom feature is required for image files only. Right? PDF files or videos have built-in full screen option

**Comment by aparnacoronasafe** [comment]
the zoom in/out button appears in staging. However, unable to see the image preview 

https://care.coronasafe.in/facility/c2d37a3e-3b82-4a12-881f-5faca5a44134/patient/18c2290d-4084-4bab-bef1-17526a2ce1be/consultation/36ca2fad-f80a-4aee-93a1-972d4a7a2a76/files/

@peeyush14goyal

**Comment by peeyush14goyal** [comment]
It's happening for images only. @aparnacoronasafe Locally its working fine

**Comment by peeyush14goyal** [comment]
@vigneshhari Is there any change in backend?

**Comment by peeyush14goyal** [comment]
#1239 Merged
