### ISSUE TITLE
Update dependency

### ISSUE THREAD

**Issue by bodhish** [ohcnetwork/care_fe#1233]
Update all the packages that used to the latest version. 
You can ignore tailwind on this as we have another issue for the same.

**Comment by ghost** [comment]
Is it fine to update only one package?

When i run `yarn upgrade` , only one package updated i.e. `react-dates`. 
For other packages, it shows peer dependencies problem. 

Now i am trying `ncu -u` to update `package.json` then trying to fix the errors. Some of the error seems like because of upgrading typescript because the errors are thrown of source itself rather than packages 😅 

```bash
ERROR in /home/abhinandan/github/care_fe/src/Components/ExternalResult/ResultList.tsx
./src/Components/ExternalResult/ResultList.tsx 112:28-32
[tsl] ERROR in /home/abhinandan/github/care_fe/src/Components/ExternalResult/ResultList.tsx(112,29)
      TS2345: Argument of type 'true' is not assignable to parameter of type 'setQueryParamsOptions | undefined'.
 @ ./src/Router/AppRouter.tsx 40:0-65 237:66-76
 @ ./src/App.tsx 5:0-43 59:35-44
 @ ./src/index.tsx 5:0-24 26:28-31
```

All changes are done on [my forked version](https://github.com/abhinandanarya06/care_fe/commits/develop)

**Comment by ghost** [comment]
Oh project is working even after these errors. Let me fix these errors. Seems easy

**Comment by ghost** [comment]
https://github.com/ProCode2/care_fe/commit/f5da7e803472779e8a6b2f61667ab55afdfa04aa#r51463731

node-sass and sass-loader upgraded but we have to keep sass-loader version upto v10.0 because https://stackoverflow.com/questions/66082397/typeerror-this-getoptions-is-not-a-function I think😅

**Comment by ghost** [comment]
`node-sass` and `sass-loader` removed 👍🏻  [Commit](https://github.com/ProCode2/care_fe/commit/55938752709c1ceb50ccc77dc654d5b3e255699e)

**Comment by ghost** [comment]
Do we need to update `webpack-dev-server` ? 
because after update, `webpack-dev-server` becomes `webpack serve`. 😅 
Hence need to modify script `npm start` in package.json

**Comment by ProCode2** [comment]
Should that be a problem?

**Comment by ghost** [comment]
Need to create a separate issue for webpack upgradation. It has many issue after upgrading from v4 to v5. followed the [guide](https://webpack.js.org/migrate/5/) but still stuck. Also indirectly webpack can affect tailwind upgradation i think. Hence we should wait for upgrading tailwind then webpack 😅 . 

Also many other packages couldn't be upgraded until webpack such as `ts-loader`, `html-webpack-plugin` and other plugin as per [the PR](https://github.com/coronasafe/care_fe/pull/1281)
