### ISSUE TITLE
"Mark as accident" in Inventory Log

### ISSUE THREAD

**Issue by aparnacoronasafe** [ohcnetwork/care_fe#1242]
When an older log entry of a facility (in page 2 of the inventory log) is marked as an accident, the page automatically refreshes and goes to the page with the latest log (Page 1)

**Comment by khavinshankar** [comment]
@aparnacoronasafe can you please add steps to replicate the issue, if possible also add a link, that will be very useful.

**Comment by bodhish** [comment]
@khavinshankar fix would be to add the pagination of inventory objects in the url
