### ISSUE TITLE
Review time: consultation update

### ISSUE THREAD

**Issue by aparnacoronasafe** [ohcnetwork/care_fe#1255]
The review set on consultation update does not get saved

Also, a badge for saved consultation update for review set must be added

**Comment by peeyush14goyal** [comment]
@bodhish Data rendered does not contain review_time field
![image](https://user-images.githubusercontent.com/42883572/120068473-809bec00-c09e-11eb-9c1f-55224c7ecf81.png)

**Comment by vigneshhari** [comment]
review_time is part of the patient, not the consultation. ( although it saved in consultation the backend moves it to the patient )
the patient API should have it.

**Comment by peeyush14goyal** [comment]
@aparnacoronasafe As @vigneshhari mentioned that Review Time is stored in Patient Details. So next do you want to show this value somewhere?

**Comment by peeyush14goyal** [comment]
In Patient Data its here
![image](https://user-images.githubusercontent.com/42883572/121845710-78c98200-cd03-11eb-8b30-34d4dde0ccb1.png)

**Comment by aparnacoronasafe** [comment]
@peeyush14goyal 

The issue is the saved review time doesn't appear in any of the forms.

So what happens is, once you set review, You have no way of deleting the review alerts

If the saved reviews appear somewhere, Like on the patient dashboard, with an option to stop/edit it.

**Comment by peeyush14goyal** [comment]
@vigneshhari 
![image](https://user-images.githubusercontent.com/42883572/121897467-0a56e500-cd40-11eb-86d4-cd0e87e8b793.png)

![image](https://user-images.githubusercontent.com/42883572/121896974-856bcb80-cd3f-11eb-862e-52a092ea626b.png)

If review_time field is left blank then 0 is sent in request.
Are we adding the review_time value in the current time in the backend?. If so, then please Can you please update that if review_time field is 0 then make review_time "null"?

**Comment by aparnacoronasafe** [comment]
Clarification on the Issue:

**How the Review Feature should work:**
- The user must be able to set a review time in the consultation/edit consultation form. Or later on in a log update form.
- Once the review time is set, then within that time if a Log Update is not filed for the patient, then the "Review Missed" Badge must appear on the patient card.
- When a log update is filed for the patient, the preselected review time must come pre-filled in the 'review after' field in log update.
- With every log update filed, the review clock must reset.
- If the user, the the log update doesnt edit the 'review after' field, the same interval will continue for review, with the review call resetting with every log update.

Eg: I file a 1 hr review in consultation form. I file a log update in half an hr. The log update form will come prefilled with 1hr in review after field. I can choose to edit it to 2 hrs. Then once i save the log update, the clock for review must reset. If no logupdate is filed in another 2 hrs, the "review missed" label must appear on the patient grid in patient list. Then once i file a log update, the clock must be reset again with whatever time is mentioned for review in the latest log update.

**Issues in CARE now - to be resolved**

- [ ] When I select a review after time in consultation form, and later open the edit consultation form, I see the review after field as blank. I must be able to see the review time i had set previously and also have the option to edit it.
- [ ] When i edit the consultation form to add/edit review time, such time must be considered from the time I edited the consultation, and not the time the original consultation was filed.
- [ ] When a review is missed, an a "review Missed" flag appears on patient card, the flag must dissappear once I file a log update. 
- [ ] The log update form must come pre-filled with the previoud review time set (either on the consultation form, or on the previous log update)- the user must have option to edit it. 
- [ ] The "review missed" flag must come right below the patients name on the patient dashboard as well (https://care.coronasafe.in/facility/7ab27974-32c8-4e36-bdf9-dbf102524718/patient/cc52390c-ac8a-4af5-9806-f3df7ee1795a/consultation/7037609e-3c25-45ed-bfd8-e01c346cbd45)
