### ISSUE TITLE
Staff (read only) creating new user

### ISSUE THREAD

**Issue by aparnacoronasafe** [ohcnetwork/care_fe#1259]
When a staff read-only creates a new staff, In the user-type he can see the option to create "Staff" as well.

The user cannot create staff ID, but seeing it as an option in the dropdown will confuse the user

**Comment by sam9111** [comment]
Can a staff create a staff read-only user? @aparnacoronasafe

**Comment by aparnacoronasafe** [comment]
@sam9111 yes. a staff can create a staff read-only because it is a lower access level.
