### ISSUE TITLE
Staff (Read-only) can create another user with no linked facility

### ISSUE THREAD

**Issue by aparnacoronasafe** [ohcnetwork/care_fe#1261]
Staff (Read-only) must only be able to create another user linking at least one of the facility he is linked to. 

The field for "Facility" must only show the linked facilities as an option

**Comment by aparnacoronasafe** [comment]
@sam9111 because you worked on a similar issue for Staff user, I am assigning this to you. Hope that is okey

**Comment by vigneshhari** [comment]
@aparnacoronasafe this wont be done

**Comment by vigneshhari** [comment]
If a read-only staff admin can create a user with write permissions they what is the point of a read-only admin?

**Comment by aparnacoronasafe** [comment]
> If a read-only staff admin can create a user with write permissions they what is the point of a read-only admin?

@vigneshhari please read the issue properly.

**Comment by vigneshhari** [comment]
> @sam9111 because you worked on a similar issue for Staff user, I am assigning this to you. Hope that is okey 

Staff user cant be created , staffreadonly can be created.

**Comment by aparnacoronasafe** [comment]
I am not asking for staff user to be created Vignesh! I am concerned about the facility that is linked! 

@vigneshhari earlier, even staff user could create another staff user with no facility linked:other facility linked. That is the issue Samyukta had worked on. So the same access limit must be brought here for staff read only user

**Comment by vigneshhari** [comment]
I know that, this is not made in the backend is what i'm saying, patching this in the frontend is still going to leave a security vulnerability.

**Comment by amruthavijay88** [comment]
@vigneshhari, @aparnacoronasafe, @bodhish - Please share your thoughts on what to action next.

**Comment by vigneshhari** [comment]
I have added a filter that raises an error when a read-only user tries to create a non-read-only user. This should be fine now

**Comment by amruthavijay88** [comment]
Makes sense, thanks @vigneshhari. @sam9111 - will you restart on this.
