### ISSUE TITLE
Unable to update patient category in Consultation form

### ISSUE THREAD

**Issue by peeyush14goyal** [ohcnetwork/care_fe#1263]
**Describe the bug**
While updating the consultation form, the Category field dropdown is not working

**To Reproduce**
1. Go to any patient's 'Consultation Update'
2. Click on 'View Consultation Update Details' then 'Update Details'
3. Scroll down to 'Category'
4. Try updating the category

**Expected behavior**
The category should get updated

**Comment by aparnacoronasafe** [comment]
the category is getting updated. I am unable to reproduce the issue. Tested in production

**Comment by peeyush14goyal** [comment]
The code that I pulled from develop 2 days ago had that issue. But now it looks good.
