### ISSUE TITLE
approved quantity: Resources

### ISSUE THREAD

**Issue by aparnacoronasafe** [ohcnetwork/care_fe#1267]
While a resource request is approved, the user must be able to enter "Approved Quantity"

A new field for the same must be added.

This approved quantity may be different from the requested quantity.

**Comment by Sandra3657** [comment]
The approved quantity can be added in only when the status is approved? The quantity can't be changed in any other status? @aparnacoronasafe

**Comment by aparnacoronasafe** [comment]
correct. it should be added when request is in pending list @Sandra3657
