### ISSUE TITLE
Approval Letter in Resources

### ISSUE THREAD

**Issue by aparnacoronasafe** [ohcnetwork/care_fe#1270]
Just like the referral letter in shifting, we need an approval letter in Resources.

The approval letter must have the following

https://docs.google.com/document/d/1YfS7FlDzvTE2YaW4YIYhsFdXIBLvZu4aWDtyoKv0i3k/edit?usp=sharing

PLEASE CHECK OUT THE SHIFTING REFERRAL FORM AS AN EXAMPLE

**Comment by peeyush14goyal** [comment]
@aparnacoronasafe @bodhish Suggesstions please
![image](https://user-images.githubusercontent.com/42883572/120178315-0480e000-c227-11eb-972e-cca01171b83f.png)


Print View
![image](https://user-images.githubusercontent.com/42883572/120178413-1bbfcd80-c227-11eb-8d6c-b3189e78c303.png)

**Comment by aparnacoronasafe** [comment]
@peeyush14goyal looks great
