### ISSUE TITLE
Speciality for doctors

### ISSUE THREAD

**Issue by aparnacoronasafe** [ohcnetwork/care_fe#1271]
doctors to be grouped and identified for different soecialities

**Comment by bodhish** [comment]
Can we use skills here? @vigneshhari

**Comment by vigneshhari** [comment]
Yeap That is possible

**Comment by vigneshhari** [comment]
API's are done and pushed, awaiting frontend Dev

**Comment by Sandra3657** [comment]
What should be done in the frontend? Can you explain more about the issue? @aparnacoronasafe

**Comment by bodhish** [comment]
@coronasafe/cef do pick-up

**Comment by arpancodes** [comment]
need more info on frontend, @bodhish where should this go?

**Comment by bodhish** [comment]
Add skill for users.
Use skill to filter doctors in telemedicine

**Comment by smartclash** [comment]
- Account owner can add skills on their profile
- User create page should have the field to add skills

**Comment by Sandra3657** [comment]
These are the skills in the API. @bodhish 

![image](https://user-images.githubusercontent.com/62461536/124490037-46291b80-ddcf-11eb-96f2-adf84b0da94a.png)

**Comment by aparnacoronasafe** [comment]
1) add a button in profiles page for the user to update their own skills.

2) for district admins, the user list will also have the button to add skills. Scoping of this button will be same as the "delete" button that is only available to district admins. This is so that district admins can edit skills of users 

@Sandra3657

**Comment by Sandra3657** [comment]
Is it possible to add skill field to the Users List API to filter doctors based on their skills? @vigneshhari

**Comment by nihal467** [comment]
the issue is resolved in the PR #4455
