### ISSUE TITLE
Chat support on CARE

### ISSUE THREAD

**Issue by aparnacoronasafe** [ohcnetwork/care_fe#1278]
bring back the chat support

**Comment by bodhish** [comment]
Use fresh desk and their ticketing system.

**Comment by aparnacoronasafe** [comment]
Using Freshdesk ticketing system

**Comment by bodhish** [comment]
@aparnacoronasafe status?

**Comment by samholics** [comment]
@tomahawk-pilot is there any updates  about this ?

**Comment by Pragati1610** [comment]
Freshdesk ticketing system provides its own dashboard and mailing to the email address generated by them creates the ticket.
So what all features is expected from this issue? [any changes in the frontend?]

**Comment by nihal467** [comment]
@aparnacoronasafe @gigincg is this issue still wishlist or close it
