### ISSUE TITLE
Not able to create patient when current address is same as permanent address

### ISSUE THREAD

**Issue by divyagar** [ohcnetwork/care_fe#1285]
**Describe the bug**
When `same as current address` checkbox is checked I am not able to create new patient.

**To Reproduce**
1. Go to patient creating form.
2. Fill all necessary details but check `Same as current address` checkbox.
3. Click on submit.

**Comment by bodhish** [comment]
@divyagar don't assign issues. Keep it open for others to pick up.

**Comment by arpancodes** [comment]
I believe the PR fixed the issue, closing.
