### ISSUE TITLE
Unable to clear SRF ID: discharge

### ISSUE THREAD

**Issue by aparnacoronasafe** [ohcnetwork/care_fe#1287]
When discharging a patient from CARE, in the pop-up window, user is unable to clear SRF ID:

<img width="583" alt="Screenshot 2021-05-31 at 2 40 15 PM" src="https://user-images.githubusercontent.com/67050716/120169989-21fd7c00-c21e-11eb-9399-75414c1f5bab.png">

NOTE: user can enter another SFR ID, but in cases where the SRF is not available, the user is unable to clear the field

**Comment by sam9111** [comment]
Can the field just be made blank? I feel its better that way. If the field was prefilled with the present srf id and no changes were made to it,on submitting, the srf id would update again with the same one as before. Since it is an optional field, it can be blank right? @aparnacoronasafe @bodhish

**Comment by aparnacoronasafe** [comment]
@sam9111 yes Samyukta. You are right. Lets keep it blank
