### ISSUE TITLE
Pharmacist user: Creating volunteer

### ISSUE THREAD

**Issue by aparnacoronasafe** [ohcnetwork/care_fe#1293]
A pharmacist can only create another pharmacist and not a volunteer. 

However, when logged in as a pharmacist, the user can see the option to create a volunteer in the dropdown for usertypes. 

The system doesn't allow for the generation of a volunteer user ce=redential. But having it as an option in the dropdown may lead to confusion.

**Comment by sam9111** [comment]
Can I take this up? @bodhish

**Comment by bodhish** [comment]
Sure @sam9111
