### ISSUE TITLE
Date of vaccination

### ISSUE THREAD

**Issue by aparnacoronasafe** [ohcnetwork/care_fe#1297]
Add a field to the patient basic information form, to capture the date of the last dose of vaccination.

This date may be very useful to study infections post vaccination.

There must also be a filter in the advanced filter in patient list to filter by date of vaccination. Once the field on vaccination is added, Please raise this as another feature request.

**Comment by amruthavijay88** [comment]
Tested, system automatically assumes current date as the last vaccination date for already existing patients who do not have this data earlier.

**Comment by shaileshaanand** [comment]
@bodhish I have fixed the issue and created a new PR
@amruthavijay88 Please test #1348

**Comment by amruthavijay88** [comment]
Tested.

@shaileshaanand - where is the vaccination date?

![image](https://user-images.githubusercontent.com/67979586/121397922-6ef5f680-c972-11eb-8063-a99fd3c4f10a.png)
