### ISSUE TITLE
Hospital Onboarding

### ISSUE THREAD

**Issue by dauntlessnomad** [ohcnetwork/care_fe#13]
- [x]  Add Hospital Form -> @injas427 
- [x] View for Hospital Admin -> @cristomathew 
- [x]  Add Hospital Capacity Form  -> @injas427  
- [x] add Doctors capacity Form -> @Kuncheria-Kuruvilla 
- [x] edit BED Capacity -> @kuncheria-Kuruvilla
- [x]  edit Doctor Capacity -> @anandsimmy
- [x] #1 Facility Admin Dashboard - >

**Comment by Kuncheria-Kuruvilla** [comment]
I can take up edit BED Capacity.

**Comment by anandsimmy** [comment]
I can take up edit doctor capacity

**Comment by dauntlessnomad** [comment]
ok

**Comment by dauntlessnomad** [comment]
Completed
