### ISSUE TITLE
Supplier details are needed in resource request

### ISSUE THREAD

**Issue by amruthavijay88** [ohcnetwork/care_fe#1300]
We need a field for updating supplier's name in resource request raised by both facilities and other war rooms. They generally take in oxygen from their usual suppliers, that way - it's easier to fix their demand request quickly.

**Supplier's list below;**

Cochin   Shipyard Limited
Inox Air   Products P Ltd
Manorama   Oxygen Pvt Ltd
Menachery   Industries
M/S   Southern Air Products
Narayana   Industrial Gases
Praxair   India Pvt Ltd
Southern   Air Products
Sterling   Gases Ltd
The   Southern Gas Ltd
Vigneswara   Oxygen Pvt Ltd

**Comment by Sandra3657** [comment]
What about the case where the supplier is not the one in the given list? Should it be manually filled in or not filled in at all? @amruthavijay88
