### ISSUE TITLE
A field to add 'note for patient's family' in consultation update

### ISSUE THREAD

**Issue by amruthavijay88** [ohcnetwork/care_fe#1301]
A new feature for patient's family to login to the system and view the below details of the patient (available at consultation/consultation updates);

1. Investigations
2. Prescription
3. Current health
4. Admitted to
5. Admission date
6. A new field 'Note for patient's family' in consultation updates.

This way patient's family can log in and view essential details on patient's current condition.

**Comment by amruthavijay88** [comment]
@bodhish

**Comment by amruthavijay88** [comment]
@bodhish - could we have these fields & please confirm if CEFs can work on this?

**Comment by bodhish** [comment]
@vigneshhari

**Comment by vigneshhari** [comment]
After considerations, the patient notes are to be reused. Closing Issue.
