### ISSUE TITLE
Add an option to delete users

### ISSUE THREAD

**Issue by bodhish** [ohcnetwork/care_fe#1309]
District admin should be able to delete others users

**Comment by Sandra3657** [comment]
Is there any API which can be used to delete users? @vigneshhari

**Comment by vigneshhari** [comment]
DELETE endpoint is added in Users , Note that this is a soft delete only.

**Comment by Sandra3657** [comment]
The district admin should only be able to delete users of usertypes, that he is able to create , right? @bodhish

**Comment by amruthavijay88** [comment]
Tested, unable to delete someone of staff user type. Warning comes - which says 'Not found' and then the user seems to exist after deletion.
