### ISSUE TITLE
SMS alert on shifting is not working

### ISSUE THREAD

**Issue by samholics** [ohcnetwork/care_fe#1313]
SMS ALERT ON SHIFTING MODULE IS NOT WORKING

1) shifting initiated from a facility
2) approved and moved card to destination approved from district admin id
3) but not get ny sms alert on patient num 

https://care.coronasafe.in/shifting/5b2d891d-60a5-4900-9594-ce5572dc7d32

**Comment by vigneshhari** [comment]
The SMS api is down for some requests, this is an ops issue tagging syam.

**Comment by bodhish** [comment]
@tomahawk-pilot
