### ISSUE TITLE
Shifting form: edit 

### ISSUE THREAD

**Issue by aparnacoronasafe** [ohcnetwork/care_fe#1316]
The origin facility must be able to edit the shifting form.

NOTE: However, they must not edit the KASP Question.

Only the fields available in the "Shift Request form" must be editable in the shifting form

**Comment by vigneshhari** [comment]
please provide the list of fields the origin facility DO NOT have access to.

**Comment by aparnacoronasafe** [comment]
@vigneshhari only the KASP question is what the origin facility does NOT have access to

**Comment by vigneshhari** [comment]
The shifting form's kasp option was always designed to be noneditable to the origin or the receiving facility. Can you show me a screenshot of this happening in staging? i could not reproduce it.

**Comment by aparnacoronasafe** [comment]
@vigneshhari please read the issue properly

**Comment by vigneshhari** [comment]
The backend already supports all field edits apart from kasp and shifting status, i cant see how i can help with anything else here.

**Comment by bodhish** [comment]
This should be working now. I remember making this change. Do test and close @amruthavijay88 @aparnacoronasafe
