### ISSUE TITLE
Missing parameters in response for Patient dashboard

### ISSUE THREAD

**Issue by arpancodes** [ohcnetwork/care_fe#1323]
Need to show these in patient dashboard, but I can't seem to find these in response. 
![image](https://user-images.githubusercontent.com/42417893/120661117-9eee5700-c4a5-11eb-820d-f4ed99b23a26.png)

**Comment by vigneshhari** [comment]
@bodhish are these stats really required? metabase solves most of these issues right?

**Comment by bodhish** [comment]
It's avilable via metabase

**Comment by vigneshhari** [comment]
Okay, blocking this issue then.
