### ISSUE TITLE
Tele-Help caller's access to update information

### ISSUE THREAD

**Issue by amruthavijay88** [ohcnetwork/care_fe#1326]
A tele-help caller needs to have only read access to the patient's card, as he needs to just see and update patient's current health status to family. There needs to be an option for this caller to write down on updates/status/notes - post call.

**Comment by bodhish** [comment]
@vigneshhari can this be done with volunteers

**Comment by vigneshhari** [comment]
a staffreadonly user is already present , use it instead , edge cases will be present , identify them to fix them.

**Comment by vigneshhari** [comment]
@amruthavijay88 do you know what has to be built here? Everything required to solve this issue already exists in the backend and in the UI.
