### ISSUE TITLE
Improve the date time listing in Inventory log

### ISSUE THREAD

**Issue by bodhish** [ohcnetwork/care_fe#1329]
The created date time on the inventory log is currently displayed in 12hrs format without showing `am/pm` 
![WhatsApp Image 2021-06-03 at 7 41 31 PM (1)](https://user-images.githubusercontent.com/14979190/120703840-73826100-c4d3-11eb-898a-acfafe31bd38.jpeg)

Include  `am/pm` along with the date-time

**Comment by smartclash** [comment]
Issue fixed by #1330
