### ISSUE TITLE
"BLANK SCREEN COMES" UP WHEN TYPE DATE OF BIRTH of a patient

### ISSUE THREAD

**Issue by samholics** [ohcnetwork/care_fe#1344]
when creating a new patient card, if we put DOB then the screen turns white

. in staging logged in as district admin, tried to create a new patient card
. when type the DOB  screen became white 
 

https://care.coronasafe.in/facility/2fa3fceb-d54d-455d-949c-e64dde945168/patient

**Comment by ghost** [comment]
Fixed in d863d46e1e7a460fc29522ce89c9978e16ee5cab
