### ISSUE TITLE
Screen goes blank when we try to create a patient from external results

### ISSUE THREAD

**Issue by amruthavijay88** [ohcnetwork/care_fe#1345]
Go to external results - select a patient with tested positive results - click 'create' on RHS - Assign a facility. Once a facility is assigned - screen goes blank.

**Comment by smartclash** [comment]
This is fixed, https://github.com/coronasafe/care_fe/pull/1347#issuecomment-855436124?

**Comment by bodhish** [comment]
Unable to reproduce the issue
