### ISSUE TITLE
revoke permission of localbody admin to delete external results record

### ISSUE THREAD

**Issue by aparnacoronasafe** [ohcnetwork/care_fe#1346]
Only the district admin must have permission to delete the external result record. 

The local body admin currently can delete external result records. This must not be allowed, because with this, a local body admin, instead of registering the p[atient card could simply just delete the record. 

@bodhish please review

**Comment by gigincg** [comment]
@aparnacoronasafe Can we close this? Looks like the backend changes are done.

**Comment by nihal467** [comment]
the issue is resolved
