### ISSUE TITLE
Font size is super small when language is anything other than English

### ISSUE THREAD

**Issue by smartclash** [ohcnetwork/care_fe#1350]
Font size is super small when language is anything other than English. It's highly unreadable.

![super_small_translation_font](https://user-images.githubusercontent.com/16922883/120925751-90977980-c6f7-11eb-9a52-62c2fe25c89a.gif)

 - OS: Ubuntu 20.04 LTS GNOME (vanilla)
 - Browser Firefox
 - Version 89.0

**Comment by ghost** [comment]
## 2nd Observation
When i modify `lang` attribute of `html` tag, it shows font size correctly as follows

### Previous
![image](https://user-images.githubusercontent.com/52771399/121310026-86a48f00-c920-11eb-8d53-3c71c1e0b060.png)

### After change
![image](https://user-images.githubusercontent.com/52771399/121309912-61b01c00-c920-11eb-94ec-ad0e94045a7d.png)

I think there is only change in font family. Don't know why it changes font family in this case.

**Comment by ghost** [comment]
Hmm only font-size of english letter has changed, it means it whether need a full translation for consistency or don't use `lang` attribute in this case 😅

**Comment by nihal467** [comment]
the issue in current staging is resolved
