### ISSUE TITLE
selected doctors not showing in Edit Consultation form

### ISSUE THREAD

**Issue by khavinshankar** [ohcnetwork/care_fe#1366]
**Describe the bug**
In edit consultation form, even though a doctor is selected in telemedicine, it shows assign a doctor

**To Reproduce**
1. Go to https://care.coronasafe.in/facility/fdad4400-bd11-49dd-9da1-5be0e79fa14e/patient/c1f4c2a6-a8e7-494a-a2e0-00749c3f8c1f/consultation/eb8c694a-36a8-4b4f-9fd0-46c098d47f8a/update
2. Scroll down to Telemedicine section

**Expected behavior**
In assigned to a doctor's name should be showing instead of 'Assign a doctor'

**Screenshots**
![image](https://user-images.githubusercontent.com/29787772/121294819-a54c5b00-c90b-11eb-9221-262c7f9c9055.png)

**Comment by smartclash** [comment]
Issue has been fixed with this PR https://github.com/coronasafe/care_fe/pull/1378.
