### ISSUE TITLE
Asset list for facility

### ISSUE THREAD

**Issue by bodhish** [ohcnetwork/care_fe#1367]
Create a new feature for facilities to manage their assets. 

Facilities should be able to register their assets.
It should have an option to print QR codes for all the assets. (The external id for the asset should be listed below the qr code)

Fields 
- Titile 
- Description 
- warranty details 
- photos 
- working - yes / no
- serial number

**Comment by vigneshhari** [comment]
I will build the backend, @bodhish needs more discussions before this is built, adding the blocked label.

**Comment by bodhish** [comment]
@vigneshhari can we talk?

**Comment by vigneshhari** [comment]
Backend Requirements Summary : 
Facility Asset --> 
- [x] Can be an Internal Asset or an External Asset
- [x] Each Asset has an ID
- [x] Each Asset can have its own attributes
- [x] Each Facility can have locations that the asset can be located at
- [x] Each Asset will have a history of locations and the current location
- [x] Users can have default locations so they don't have to select a location every time 
- [ ] External Assets can be transferred into Other Facilities Default Locations
- [ ] Dist Admins can track all External Assets
