### ISSUE TITLE
Flag : No consultation filed

### ISSUE THREAD

**Issue by aparnacoronasafe** [ohcnetwork/care_fe#1368]
In the patient tab, When the user views the list of patients flag the patients for whom consultation has not been filed in the said facility

This will allow the administrators to quickly identify the patient cards where consultation needs to be filed.

**Comment by Sandra3657** [comment]
Is it possible to add in this field in the API? @vigneshhari

**Comment by vigneshhari** [comment]
The api already supports this , check if the last consultation is discharged or not .

**Comment by Sandra3657** [comment]
The last_consultation field in the API has just an integer, right? There is no discharge info in the API.  @vigneshhari

**Comment by vigneshhari** [comment]
Nope, there is an entire object there, i update the swagger documentation as well.
