### ISSUE TITLE
Revamping the Sample Management: Request form

### ISSUE THREAD

**Issue by aparnacoronasafe** [ohcnetwork/care_fe#1380]
The sample management tool is to be used to the following tests:

- Biopsy
- AMR
- CD

To make this operational, the following changes must be made:

In the sample request form
https://care.coronasafe.in/facility/fdad4400-bd11-49dd-9da1-5be0e79fa14e/patient/4f649c00-1bf7-486f-8527-22cf62234a52/sample-test

1) "SAMPLE TEST TYPE" to have the following option
- Biopsy
- AMR
- Communicable Diseases

2) ICMR Category to be renamed "ICMR Category (for COVID Test)- to be made a non-mandatory field

**Comment by ghost** [comment]
@aparnacoronasafe 
Is making ICMR Category field non mandatory means adding `None` or Empty value by default ? 
Currently if user doesn't select ICMR field, value will be `Cat 0` by default(configured in backend itself). Is it okay?
