### ISSUE TITLE
Revamping Sample Management : Result: File Upload

### ISSUE THREAD

**Issue by aparnacoronasafe** [ohcnetwork/care_fe#1382]
When the Staff at the Lab Updates the result, Marking the status as test complete, There must be an option to upload file.

This is where the detailed report will be scanned and uploaded.

**Comment by vigneshhari** [comment]
The file upload feature was designed to be associated with any kind of data, the CEF folks can take this up, integration should take less than 10-20 mins.

**Comment by shaileshaanand** [comment]
Will this file upload be compulsory? @aparnacoronasafe @bodhish

**Comment by bodhish** [comment]
No
