### ISSUE TITLE
The filtering logic is not working

### ISSUE THREAD

**Issue by bodhish** [ohcnetwork/care_fe#1387]
Filter by event type in notifications is not working. 

https://www.loom.com/share/0ca4e620d7704188ab5e079360111ce2

**Comment by arpancodes** [comment]
@vigneshhari the caused by object is empty for 'SHIFTING_UPDATE'

**Comment by vigneshhari** [comment]
@arpancodes the frontend should not crash if the object is empty, this should be handled since there will be notifications with caused objects empty.

**Comment by arpancodes** [comment]
@vigneshhari it isn't crashing it's just that I am not able to redirect to the shifting update page due to the empty object...

**Comment by vigneshhari** [comment]
how is the shifting issue related to this issue then? The Backend has this bug resolved all new shifting updates should have this data now.

**Comment by arpancodes** [comment]
In the PR @aparnacoronasafe commented and marked as `test failed` that's why I asked
