### ISSUE TITLE
Create a triage form and view inside facility home

### ISSUE THREAD

**Issue by dauntlessnomad** [ohcnetwork/care_fe#139]
The form should have an option to update the following fileds.
# OP TRIAGE

TOTAL PATIENT VISITED IN CORONA TRAIGE | TOTAL NO.OF PATIENT ADVISED HOME QUARANTINE | TOTAL NO.OF PATIENTS UNDER ISOLATION | TOTAL OF PATIENTS REFFERED
-- | -- | -- | --

Refer the following issue for more details
https://github.com/coronasafe/care/issues/127

**Comment by psjishnu** [comment]
What is needed to be added in facilities?

**Comment by dauntlessnomad** [comment]
Models
FacilityPatientStatsHistory
facility_id -> refers Facility
entry_date -> date of the data entry (default will be today, can be overrridden)
num_patients_visited -> "TOTAL PATIENT VISITED IN CORONA TRAIGE"
num_patients_home_quarantine -> "TOTAL NO.OF PATIENT ADVISED HOME QUARANTINE"
num_patients_isolation -> "TOTAL NO.OF PATIENTS UNDER ISOLATION"
num_patient_referred -> "TOTAL OF PATIENTS REFFERED"
APIs
GET /facility/{id}/patient_stats/ - can support date filter
POST /facility/{id}/patient_stats/ - will create or update for the date mentioned

{
  "entry_date": "",
  "num_patients_visited",
  "num_patients_home_quarantine",
  "num_patients_isolation",
  "num_patient_referred"
}
