### ISSUE TITLE
"Something went wrong" SHIFTING

### ISSUE THREAD

**Issue by aparnacoronasafe** [ohcnetwork/care_fe#1402]
When a district admin user updates a shifting status to "DESTINATION APPROVED" something went wrong error comes up

**Comment by arpancodes** [comment]
@aparnacoronasafe could you give more information to reproduce this error? I was able to update the status to `DESTINATION APPROVED` using a district admin profile
![shifting_req](https://user-images.githubusercontent.com/42417893/121876534-39149180-cd27-11eb-8c7f-b31336e93f7b.gif)

**Comment by aparnacoronasafe** [comment]
resolved
