### ISSUE TITLE
Create an option to capture Critical Care flow chart for a patient

### ISSUE THREAD

**Issue by bodhish** [ohcnetwork/care_fe#1404]
The staff in a hospital should be able to capture the In-depth vitals for a patient in an ICU/Ventilator. 

Required Fields - [link](https://docs.google.com/spreadsheets/d/e/2PACX-1vTqV1adSFDg0I4g4_oUn8jBBQYr7zubxPlCYQFKHmfQaiCzxYthJSD8xbFmDJWTLfyVqXUwKCzSYh2W/pubhtml?gid=0&single=true)

Design - [Link](https://drive.google.com/file/d/1GXcAnbSGD6RjkEWLUxNHnZdILVTEmNXZ/view?usp=drivesdk)

[Sample of Critical Care Flow Chart](https://github.com/coronasafe/care_fe/files/6647304/Scan.Sep.17.2020.1.pdf)

Use Rescript to create the Form

**Comment by aparnacoronasafe** [comment]
@Sandra3657 I have marked the fields that wouldn't apply for Patients in Prone position in Red in the ICU Module spreadsheet https://docs.google.com/spreadsheets/d/e/2PACX-1vTqV1adSFDg0I4g4_oUn8jBBQYr7zubxPlCYQFKHmfQaiCzxYthJSD8xbFmDJWTLfyVqXUwKCzSYh2W/pubhtml?gid=0&single=true

Only the fields relating to pupil (size, reaction to light) needs to be hidden

**Comment by aparnacoronasafe** [comment]
Please refer to this doc to name the parts of the anatomy diagram for Pressure score.

[anatomy- Pressure score.pdf](https://github.com/coronasafe/care_fe/files/6785512/anatomy-.Pressure.score.pdf)

@peeyush14goyal
