### ISSUE TITLE
Bug in Add Consultation form

### ISSUE THREAD

**Issue by bodhish** [ohcnetwork/care_fe#142]
https://care.coronasafe.in/facility/166/consultation

Facility should not be a field in the form as it readly avilable in the sate. 
It should belng to a ptient so that, we know the patient ID.
Discharge data should default to nil
add a description for suggestion

**Comment by SandeepThomas** [comment]
Swagger: https://dev.care.coronasafe.in/swagger/

URL: http://0.0.0.0:4000/facility/200

It is currently having static data. We need to integrate the API and fix issues on the way. Please refer how API's are called in another pages and implement similarly.
