### ISSUE TITLE
Edit button is not working for consultation list

### ISSUE THREAD

**Issue by bodhish** [ohcnetwork/care_fe#145]
https://care.coronasafe.in/facility/200/consultation-list

**Comment by nandini-menon** [comment]
There is no edit button in the page. This is the page as it appears to me:-

![image](https://user-images.githubusercontent.com/29326753/78012101-213f3080-7362-11ea-97f2-fbe680e1e014.png)

**Comment by dauntlessnomad** [comment]
the button is hidden for the time being
