### ISSUE TITLE
The patient create flow does not allow creation of a patient without valid choices 

### ISSUE THREAD

**Issue by bodhish** [ohcnetwork/care_fe#146]
The form does not validate for submission without selecting a disease.
The diseases wont be in the list most of the time, its safe to add an other so that users wont get confused

https://care.coronasafe.in/facility/200/patient

```
{medical_history: [{disease: [""None" is not a valid choice."]}]}
```

**Comment by SandeepThomas** [comment]
The backend api is expecting ` medical_history: [{disease: 1, details: ""}` in POST and  `medical_history: [{disease: "NO", details: ""}` in PUT. 
The front end is sending the request like this now to prevent issues. Can be modified if backend is fixed. @bodhish

**Comment by dauntlessnomad** [comment]
@injas427
