### ISSUE TITLE
Edit Option for External result

### ISSUE THREAD

**Issue by aparnacoronasafe** [ohcnetwork/care_fe#1469]
Anyone with access to the external result (both localbody admin and district admin) must have the option to edit the following fields on External Result.
- Address
- Ward
- Local body
- Localbody type

@vigneshhari

**Comment by vigneshhari** [comment]
The update endpoint was always available the frontend only needs to be built.

**Comment by aparnacoronasafe** [comment]
@bodhish

**Comment by sam9111** [comment]
![Screenshot 2021-06-25 at 1 50 22 PM](https://user-images.githubusercontent.com/60708693/123394330-a8f30980-d5bc-11eb-8cb6-be62272ea3da.png)


Is this where the edit option should be added? @aparnacoronasafe

**Comment by vigneshhari** [comment]
yeah, add an edit button somewhere here, or on the listing page.

**Comment by sam9111** [comment]
What is a local body type? @aparnacoronasafe  @vigneshhari

**Comment by Sandra3657** [comment]
How does the "patch" method work `/external_result/{id}/` ?  It requires district and local_body_type, but then we are not able to sent the api request. @vigneshhari

**Comment by aparnacoronasafe** [comment]
@vigneshhari Please respond

**Comment by vigneshhari** [comment]
@aparnacoronasafe i have removed the local_body_type from the API itself , @aparnacoronasafe this value cannot be updated since it is inherited from the local body's value.

**Comment by aparnacoronasafe** [comment]
@vigneshhari noted. But it must be edited when the Local Body is edited right?

**Comment by aparnacoronasafe** [comment]
@vigneshhari the use case for this is, 

Currently, the external result is uploaded at the district level and then views at the panchayat level where actual card creation happend. 

But we see a lot of errors in Localbodies in the list uploaded at the district level. Since every panchayat can only see the list relevant to them, these entries with erroneous local bodies never translate to patient cards. 

We need a fix for this

**Comment by vigneshhari** [comment]
The local body type is tied to an actual local body , changing the local body will automatically change the local body type as well , we cant have invalid data anywhere.

**Comment by aparnacoronasafe** [comment]
@Sandra3657 @sam9111, please proceed with this as a priority.

@vigneshhari Thank you!
