### ISSUE TITLE
Add a option to group assets by location

### ISSUE THREAD

**Issue by nihal467** [ohcnetwork/care_fe#1491]
![kodksdksd;ds](https://user-images.githubusercontent.com/57055998/123523165-97eee900-d6df-11eb-9ba0-4dab5678831a.JPG)

**Comment by arpancodes** [comment]
@nihal467 could you explain group by location?

**Comment by nihal467** [comment]
@bodhish can you explain it

**Comment by bodhish** [comment]
This can be an advanced filter. 
If a facility is selected in the advance filter, show an option to select a location
