### ISSUE TITLE
Mark entries in External Result

### ISSUE THREAD

**Issue by aparnacoronasafe** [ohcnetwork/care_fe#1495]
The entries in external results for which Patient cards are already registered must be marked.

Give the user an option to manually mark against each entry in external result that the particular card is already registered. 

This option must be available to anyone that has access to external results

**Comment by khavinshankar** [comment]
@vigneshhari we need a variable inside the PatientExternalTest object that can store whether a patient is created from this external result or not.

**Comment by aparnacoronasafe** [comment]
@khavinshankar @vigneshhari 

Can we add a marker for external result entries for which patient cards are created by linking the SRF ID which is unique.

**Comment by vigneshhari** [comment]
@aparnacoronasafe i am adding a flag in the external results list that shows if a patient card has been generated, the users can manually set that flag to created, the system will automatically change that flag if it detects a user with that SRF ID within care.
** note that the check is case insensitive
