### ISSUE TITLE
Non-COVID : Consultation

### ISSUE THREAD

**Issue by aparnacoronasafe** [ohcnetwork/care_fe#1502]
- Change Category to "COVID Category" and add an option in the drop-down "NON-COVID Patient"
- Make the above change in consultation update as well

- Change 'State Test ID" to COVID State Test ID"

**Comment by divyagar** [comment]
@vigneshhari Please add "non-covid patient" option in category in consultation form.

**Comment by nihal467** [comment]
@aparnacoronasafe is this issue relevant or wishlist

**Comment by aparnacoronasafe** [comment]
irrelevant
