### ISSUE TITLE
Add a section for assets in facilities page 

### ISSUE THREAD

**Issue by aparnacoronasafe** [ohcnetwork/care_fe#1506]
Make the list of assets visible on Facility Dashboard

**Comment by sam9111** [comment]
Should the assets for each facility should be displayed on the main facility page? @aparnacoronasafe

**Comment by sam9111** [comment]
@joelsajichacko We need a design for listing the assets for each facility.

**Comment by bodhish** [comment]
@joelsajichacko We should have a section on the facility page with 2 buttons. 
1. View Assets 
2. Create Asset 

Can you revisit the current design in the facility show page.
