### ISSUE TITLE
Add Close Button in Assign to a volunteer Popup

### ISSUE THREAD

**Issue by nihal467** [ohcnetwork/care_fe#1562]
![bug 3](https://user-images.githubusercontent.com/57055998/125852462-107a3b14-6cc2-4368-bce5-e5c60d1b3653.PNG)

Once we open assign to a volunteer, we don't have a button to close the pop-up window

**Comment by divyagar** [comment]
@nihal467 Click `Cancel` button will close the pop up.

**Comment by nihal467** [comment]
@divyagar in a normal user perspective, we always look for a close button in the top right corner of the pop-up. @bodhish what do you think?

**Comment by developedBySJ** [comment]
@nihal467 [Dialogs - Material Design](https://material.io/components/dialogs)

**Comment by divyagar** [comment]
@nihal467 Bodhi said there is no need of close button.
