### ISSUE TITLE
Temperature Unit is Missing in Consultation Update

### ISSUE THREAD

**Issue by nihal467** [ohcnetwork/care_fe#1563]
![bug 5](https://user-images.githubusercontent.com/57055998/125853084-70ba9d7b-26c7-414c-8365-7f88eaff3d57.PNG)

the unit for the temperature is missing

**Comment by divyagar** [comment]
@bodhish Should there be a dropdown with values `celsius` and `fahrenheit`?

**Comment by nihal467** [comment]
in F , a value less than 95 is not accepting

**Comment by bodhish** [comment]
@nihal467 this will be solved with critical care
