### ISSUE TITLE
Edits to ICU Module

### ISSUE THREAD

**Issue by aparnacoronasafe** [ohcnetwork/care_fe#1573]
- [x] In the heading list, even if entries are made for a heading, It still shows 0% complete.
- [x] In ventilator parameters, in the slider for PEEP, the High/Normal/Low is marked all wrong
- [x] In PIP slider also, where Low/Normal/High Appears, 12 should have been normal. But it is marked as High
- [x] The LOW/NORMAL/HIGH is based on the inputs in the ICU Spreadsheet. However, the normal range mentioned is sometimes taken as an exclusive range and sometimes as an inclusive one.
- [x] EtCO2 field is missing
- [x] Add rounds type select field in the daily round creation form
- [ ] In INTAKE, Infusions, the Strength of loading in row 79 of the ICU Spreadsheet is missing. This is the concentration of the medicine in the IV

**Comment by nihal467** [comment]
Neurological Monitoring, Hemodynamic Parameters  - Completed Percentage is not working

**Comment by nihal467** [comment]
Hemodynamic Parameters, Aeterial Blood Gas Analysis,  - I can't completely erase the column to input the data

**Comment by nihal467** [comment]
Aeterial Blood Gass Analysis - PCO2, PO2, and base_excess not accepting decimal but when we are increasing the scale using the dot, it is coming in decimal

**Comment by nihal467** [comment]
Dialysis - by clicking on the dot, I am unable to move the scale freely

**Comment by nihal467** [comment]
https://user-images.githubusercontent.com/57055998/126077911-7e09dbde-5414-4691-ab42-9951a4ba1424.mp4



Dialysis - Dialysis Fluid Balance - I can't move the scale freely (Sometimes it works, and sometime it doesn't work)

**Comment by aparnacoronasafe** [comment]
- [x] The Slider pointer is too close to the reference sizes. The UI can be made better with proper spacing.

**Comment by aparnacoronasafe** [comment]
- [x] The options for Right Pupil reaction, the circles to mark selection are getting overlapped partially.

**Comment by nihal467** [comment]
![bug32](https://user-images.githubusercontent.com/57055998/126079116-aafa19aa-09de-4a43-8e8b-5f770e4a5138.PNG)

- [x] Unable to erase the data in the box completely and input the data ( in all sections )

**Comment by aparnacoronasafe** [comment]
When you click on the little arrows inside the numeric text box for The slider for Pulse BP Etc, the value keeps going up or down. It becomes difficult to control the slider. 

https://user-images.githubusercontent.com/67050716/126079267-eaa530a6-2291-4b3a-82b4-2fd0d7137bcf.mov

- [x] expected behavior

**Comment by nihal467** [comment]
![bsdbsd](https://user-images.githubusercontent.com/57055998/126079507-e5a26f64-3f3a-4657-8d09-c8089f4af64a.PNG)

- [x] when we are trying to reset any input parts, the part is giving a zero

**Comment by aparnacoronasafe** [comment]
- [ ] In ventilator parameters, in the slider for PEEP, the High/Normal/Low is marked all wrong

**Comment by aparnacoronasafe** [comment]
- [ ] In PIP slider also, where Low/Normal/High Appears, 12 should have been normal. But it is marked as High

**Comment by aparnacoronasafe** [comment]
In ventilator parameters, where Mean Airway Pressure appears,

- [x] Add (MAP) as an abbreviation to the text
- [x] ")" bracket is missing from UNIT

**Comment by nihal467** [comment]
![bug 4](https://user-images.githubusercontent.com/57055998/126079749-17a417ad-7d2b-42d2-9c22-88a723551ce8.PNG)

- [x] the time auto-filling is not working,

**Comment by aparnacoronasafe** [comment]
As I progress into filling info into more headings, and if i realise i need to go back to an earlier head to enter some additional info, All the previous "Complete" signs on the headings vanish

https://user-images.githubusercontent.com/67050716/126079991-00ccc34d-da6d-46f9-8a9c-3688438636a0.mov


- [x] Checked - This issue can't be fixed now. It will happen only for the basic editor as it's out of the current flow.

**Comment by aparnacoronasafe** [comment]
- [ ] The LOW/NORMAL/HIGH is based on the inputs in the ICU Spreadsheet. However, the normal range mentioned is sometimes taken as an exclusive range and sometimes as an inclusive one. 

For Eg, In systolic BP, The normal range is 100-140, and in the UI, 100 is marked as normal.

However, in certain other parameters, Oxygen flow rate, the normal is from 1-4, but 4 is marked as High

**Comment by nihal467** [comment]
![bug 5](https://user-images.githubusercontent.com/57055998/126080304-565023a6-342a-4989-8e36-e440d5b183a4.PNG)

- [x] when we are inputting data in base excess there is an unknown error showing in the HCO3

**Comment by aparnacoronasafe** [comment]
- [ ] EtCO2 field is missing

**Comment by nihal467** [comment]
![bug6](https://user-images.githubusercontent.com/57055998/126080746-360c1609-182f-426a-8e7d-c76f0b1419a4.PNG)

- [ ] Ventilator Parameters ->SPO2 % -> 90-100 is normal

**Comment by nihal467** [comment]
![bug 8](https://user-images.githubusercontent.com/57055998/126081208-d8dd1dd8-9127-493e-a48c-b4723f3cd058.PNG)

- [x] Nursing Care -> Stoma care , can you increase the space between text box and done button

**Comment by aparnacoronasafe** [comment]
- [ ] In INTAKE, Infusions, the Strength of loading in row 79 of the ICU Spreadsheet is missing. This is the concentration of the medicine in the IV

**Comment by arpancodes** [comment]
Adding the undone task to the issue description, so we can track the task list more efficiently, please add to that only from now one 😅

**Comment by peeyush14goyal** [comment]
> ![bsdbsd](https://user-images.githubusercontent.com/57055998/126079507-e5a26f64-3f3a-4657-8d09-c8089f4af64a.PNG)
> 
> * [x]  when we are trying to reset any input parts, the part is giving a zero

@nihal467 What is expected value of Braden Scale when you reset a part?
