### ISSUE TITLE
Add pagination in Consultation / Sample History

### ISSUE THREAD

**Issue by SandeepThomas** [ohcnetwork/care_fe#158]
URL: http://0.0.0.0:4000/facility/203/patient/67

Component: src/Components/Patient/PatientHome.tsx

- [ ] Add pagination feature for Consultation History (limit 5)
- [ ] Add pagination feature for Sample Test History (limit 5)

Refer Facility listing for existing implementation of paging.

**Comment by jithinlal** [comment]
i'll take this up
