### ISSUE TITLE
Testing facility Name: Sample Management Module

### ISSUE THREAD

**Issue by aparnacoronasafe** [ohcnetwork/care_fe#1593]
The Testing Facility name field in https://care.coronasafe.in/facility/01810c32-ec26-494a-9e65-40e5547a7746/patient/ed658453-49f6-4669-8267-1fff984a9475/sample-test is supposed to show all facilities of the following type:
- Labs
- Corona Testing Labs

Currently, only the corona testing labs appear there

**Comment by developedBySJ** [comment]
@aparnacoronasafe These three fields are populated in the `Testing Facility name` field

![Screen Shot 2021-07-19 at 5 29 40 PM](https://user-images.githubusercontent.com/76519654/126156832-82f1eb4c-c5fe-4cd7-9726-e5fbddcce59b.png)

**Comment by aparnacoronasafe** [comment]
Yes. There is a Test Lab 1, registered as "Labs" that don't appear here in the dropdown.  @developedBySJ
