### ISSUE TITLE
Download All Patient not working : Patients

### ISSUE THREAD

**Issue by nihal467** [ohcnetwork/care_fe#1616]
![pdk s pkd](https://user-images.githubusercontent.com/57055998/126748062-fbdb965d-bd71-4540-b311-cee3d82e15da.PNG)

when we download by clicking 'live list' and 'download all patient', both the generated excel is the same

**Comment by shaileshaanand** [comment]
@vigneshhari

careapi returns only active patients on

`/api/v1/patient/?page=1&offset=0&csv=true`

or

`/api/v1/patient/?page=1&offset=0&csv=true&is_active=True`

and inactive ones on `/api/v1/patient/?page=1&offset=0&csv=true&is_active=True`

is there a single endpoint to get all (both `active` and `inactive`) patients?

**Comment by vigneshhari** [comment]
No There is not and , you can go ahead and remove one of the links , we'll be deprecating downloads completely soon.

**Comment by bodhish** [comment]
The plan is to limit exports to a day/week at max.

**Comment by nihal467** [comment]
The issue is resolved in current staging
