### ISSUE TITLE
ISSUE IN EXTERNAL RESULT !!!!!!!!!            

### ISSUE THREAD

**Issue by samholics** [ohcnetwork/care_fe#1630]
issue in external result!!!!

when creating a patient from external result, after completing the consultation page
then name autofills to existing patient's name or anything saved on the browser as personal info

in some cases from field unfortunately name changes to existing patients name, thats makes things worse.

logged as local body admin
selected one card named "Y" from external result 
completed dob,pincode etc..also consultation click save
then the name in the patient card changes to "kadayiruppu dcc"

( "kadayiruppu dcc" is saved on my browser as personal info)

and i tried once again by turning off personal info,then it works the name remains
same as external result.

but, i cant turnoff personal info for alltime it helps me in otherways

**Comment by sam9111** [comment]
Is the autofill causing the issue? Could you make a gif or post screenshots of the problem? @samholics

**Comment by samholics** [comment]
sorry for the delayed reply @sam9111 
refer this video ;

Uploading Corona Care and 3 more pages - Personal - Microsoft​ Edge 2021-07-27 19-29-06.mp4…

**Comment by sam9111** [comment]
@samholics Could you re-upload the video?

**Comment by samholics** [comment]
https://user-images.githubusercontent.com/75214902/127192824-d28ea6ad-0df2-4d95-bd7e-cb9a86590206.mp4

@sam9111  is it fine?

**Comment by sam9111** [comment]
Cool thanks!

**Comment by sam9111** [comment]
@samholics Is the pincode entered by autofill? Mostly, autofill would be applied for fields like address, name and pin code so when you select from autofill for any of those, the rest tends to change too. Did you select the pincode from autofill?

**Comment by samholics** [comment]
yeah i think so......but the issue reported from the field facilities so dont know about their case. @sam9111

**Comment by sam9111** [comment]
@bodhish @vigneshhari can I remove the autofill ability in the material UI components for this page?
