### ISSUE TITLE
pagination for consultation is not working

### ISSUE THREAD

**Issue by aparnacoronasafe** [ohcnetwork/care_fe#1631]
A particular patient has over 30 consultation updates.

Only 14 appear as a list in consultation. Then the user clicks on the 2nd page to see the earlier consultation updates, the content on the 2nd page is also the same as the first page.

Moreover, only there 14 latest consultation updates appear in the treatment summary as well. 

The user is unable to access all older consultation updates.

**Comment by gigincg** [comment]
@aparnacoronasafe Do we have a patient to test this with in staging?

**Comment by aparnacoronasafe** [comment]
@gigincg we have patients in production.

**Comment by vigneshhari** [comment]
Unassigning me since pagination is already supported in the backend.

**Comment by Apurva-Nagar** [comment]
@aparnacoronasafe I tried reproducing the issue on staging (https://care.coronasafe.in/facility/da577337-8437-471b-b449-e4c688371c90/patient/8cc7304d-304f-49b7-92e9-9bd8508a1def/consultation/6641bc79-8f7f-45bc-9c68-15152a6bbd79), but the pagination for Updates seems to be working fine.

Can you share a staging link where this is happening?

**Comment by aparnacoronasafe** [comment]
@aparnacoronasafe This is fixed with the new UI that we deployed with Critical Care. Closing the issue.
