### ISSUE TITLE
Invalid dates in pressure sore section

### ISSUE THREAD

**Issue by divyagar** [ohcnetwork/care_fe#1635]
https://www.loom.com/share/2ae32b79a159441abf7a7b82a37cbd6b

**Comment by bodhish** [comment]
Let's look at a date selector like this. 

![image](https://user-images.githubusercontent.com/14979190/127137352-4169eeee-072c-4ce7-8a61-f8d36564960b.png)

**Comment by divyagar** [comment]
Okay. But don't you think it will occupy space when there are large number of dates?

**Comment by peeyush14goyal** [comment]
What was the issue @divyagar in rendering dates? Did I miss something?

**Comment by divyagar** [comment]
Hey @peeyush14goyal. The issue was that `results` variable contains 3 keys, one of which is `results` key. This is kind of confusing but you were using `results` variable to get date keys which in fact is contained in `results` key of `results` variable. Is it clear?

**Comment by peeyush14goyal** [comment]
Yes, I saw the file changes @divyagar. You did it in a structured way. Good work  ✅
