### ISSUE TITLE
Add cause of death to expired patients 

### ISSUE THREAD

**Issue by aparnacoronasafe** [ohcnetwork/care_fe#1649]
When a patient is marked as expired, an additional mandatory field to capture the cause of death must appear.

@bodhish @vigneshhari Please review

**Comment by nihal467** [comment]
@gigincg @aparnacoronasafe is this field still required since we already have a discharge note present in the platform 
![900180FC-C30B-43F0-8E12-15FF1FEE222B](https://user-images.githubusercontent.com/57055998/203069399-1a9cf937-01e8-4ad2-9049-da9f10570126.jpeg)

**Comment by aparnacoronasafe** [comment]
When 'discharge reason' is selected as expired, "discharge note" must change to "cause of death"
