### ISSUE TITLE
Common Search Bar for tests (Investigation)

### ISSUE THREAD

**Issue by aparnacoronasafe** [ohcnetwork/care_fe#1657]
The data entry persons are not from a medical background. Therefore they cannot be expected to know which test falls under what categorisation. 

So please add a common search bar to search across all headers.

<img width="1325" alt="Screenshot 2021-07-31 at 11 16 17 PM" src="https://user-images.githubusercontent.com/67050716/127748272-40571348-9bda-4764-87c0-7302db4702ac.png">

**Comment by ghost** [comment]
I think this issue is duplicate of #1671 . 😅

**Comment by nihal467** [comment]
the issue is resolved
