### ISSUE TITLE
Pressure Sore button not Working : Consultation Update

### ISSUE THREAD

**Issue by nihal467** [ohcnetwork/care_fe#1660]
https://user-images.githubusercontent.com/57055998/127749140-eda0c146-9756-4804-982c-17f707821093.mp4

when we click on the pressure sore button in the consultation update, the whole screen got white (no consultation update was inputted to the patient)

**Comment by ghost** [comment]
@nihal467 Can you check again if this issue still persist?
I also faced this problem tomorrow but not now. Don't know why 😅

**Comment by nihal467** [comment]
@abhinandanarya06 just create a new patient, as normal, and do not create any log update on the consultation page. Straightly go and press the pressure sore button, the whole screen go white

**Comment by arpancodes** [comment]
@nihal467 can't reproduce the error in `develop` branch

**Comment by nihal467** [comment]
@arpancodes @abhinandanarya06 the issue looks cleared, and it is working good now

**Comment by arpancodes** [comment]
Great then closing the issue.
