### ISSUE TITLE
Alignment Issue : Heading in the Consultation Update 

### ISSUE THREAD

**Issue by nihal467** [ohcnetwork/care_fe#1661]
![eowfewopkfep](https://user-images.githubusercontent.com/57055998/127749222-26d55773-e410-4419-ad1d-86e63325e465.PNG)

1. The heading does not seem to be properly aligned 
2.  remove the '_' in between the words

**Comment by sam9111** [comment]
Can we make it 2 rows? @bodhish

**Comment by sam9111** [comment]
Fixed
