### ISSUE TITLE
Audio file not working : Consultation Update

### ISSUE THREAD

**Issue by nihal467** [ohcnetwork/care_fe#1664]
![owdqwd](https://user-images.githubusercontent.com/57055998/127750143-3f065522-f682-4804-938c-f4883d3284b5.PNG)
![wekfe fw](https://user-images.githubusercontent.com/57055998/127750144-587b4578-5234-4762-b05d-7fb85fe92ece.PNG)

when we download the recorded file from the care, the file downloaded can't be played in the computer

**Comment by peeyush14goyal** [comment]
@nihal467 The issue was that while downloading the file` .mp3` extension was missing.  Added that in PR. You can test it.
