### ISSUE TITLE
changes to the ICU Module

### ISSUE THREAD

**Issue by aparnacoronasafe** [ohcnetwork/care_fe#1673]
- [x] #1676
- [x] #1677
- [x] #1678
- [x] #1679
- [x] #1680
- [x] #1681
- [x] #1682
- [x] #1683
- [x] #1684
- [x] #1685
- [x] #1686
- [x] #1687
- [x] #1688
- [x] #1689
- [x] #1690
- [x] #1691
- [x] #1692
- [ ]

**Comment by peeyush14goyal** [comment]
This issue is closed. Are all above-mentioned issues resolved? @aparnacoronasafe
