### ISSUE TITLE
Lab Tests: currently even in the investigation module we only capture the test type and result. The date sample is taken on and the date of result needs to be identified and logged

### ISSUE THREAD

**Issue by aparnacoronasafe** [ohcnetwork/care_fe#1676]

**Comment by sam9111** [comment]
![image](https://user-images.githubusercontent.com/60708693/128139683-7aff238d-de0e-47b9-861f-c6fe636ed803.png)


Should the dates be captured here?

**Comment by nihal467** [comment]
@aparnacoronasafe is it relevant or a wishlist

**Comment by aparnacoronasafe** [comment]
This is relevant. however, a lot more scoping needs to be done for V2 of Lab module. Going to assign it to myself

**Comment by bodhish** [comment]
Closing this as it no longer in scope.
