### ISSUE TITLE
ICU Module: Culture must be recorded as a separate section from lab tests

### ISSUE THREAD

**Issue by aparnacoronasafe** [ohcnetwork/care_fe#1677]
Cultures are a Microbiology category under Lab investigation

You can culture any fluid (including wounds) in the body. - most common CSF, Sputum, AFD (for TB), blood, urine, vaginal fluid, wound.

Result will have Fungal, viral, bacterial. description under these 3 fileds

**Comment by shivankacker** [comment]
Closing issue. @aparnacoronasafe

**Comment by nihal467** [comment]
@aparnacoronasafe is this wishlist or relevant right now

**Comment by aparnacoronasafe** [comment]
This needs to be done but is not a priority item.

**Comment by bodhish** [comment]
Closing this as the issue needs more scope.
