### ISSUE TITLE
Add few more fields in the consulation form

### ISSUE THREAD

**Issue by bodhish** [ohcnetwork/care_fe#170]
https://github.com/coronasafe/care/issues/226

## Add new 
- [x] `symptoms` = > dropdown => (fever, cough, sore throat, breathlessness, myalgia, abdominal discomfort, vomiting/Diarrhoea and others),
- [x] `date of onset of the symptoms` => date picker
- [x] `category`  => dropdown =>  ( “Mild(Category A) , moderate(Category B), severe(Category C))
- [x]  `room` => dropdown =>  isolation room/ICU/ICU with ventilator

## Rename
- [x] `Existing Medication` to `Medication if any for the above-mentioned symptoms`
- [x] `Decision after OP Triage` to `Decision after OP Triage/Consultation`

## order
1. symptoms
2. date of onset of the symptoms
3. examination details
4. exisiting medication 
5. category
6. Decision after OP Triage/Consultation”
7. room
8. admitted 
9. admitted dates

**Comment by vigneshhari** [comment]
The symptoms are currently sent as integers, please map them with this list until we find a better solution.
SYMPTOM_CHOICES = [
    (1, "ASYMPTOMATIC"),
    (2, "FEVER"),
    (3, "SORE THROAT"),
    (4, "COUGH"),
    (5, "BREATHLESSNESS"),
    (6, "MYALGIA"),
    (7, "ABDOMINAL DISCOMFORT"),
    (8, "VOMITING/DIARRHOEA"),
    (9, "OTHERS"),
]

**Comment by amitbhoj-fc** [comment]
can I work on this?

**Comment by SandeepThomas** [comment]
this is almost done

**Comment by amitbhoj-fc** [comment]
ok thanks to inform.

**Comment by dauntlessnomad** [comment]
Completed
