### ISSUE TITLE
Asset Management Module: Enhancement

### ISSUE THREAD

**Issue by aparnacoronasafe** [ohcnetwork/care_fe#1704]
https://care.coronasafe.in/assets/caa3d3b2-5b4e-456d-b63b-615ccb1db126

Add a log on when equipment has gone out of order and what was the downtime. A field to capture the cause may also be added.

**Comment by arihant-2310** [comment]
Can you please give me more details on this one. I am willing to take on this.

**Comment by arpancodes** [comment]
@arihant-2310 are you still available to work on this? We might need to add the `cause` field on the backend.
