### ISSUE TITLE
Asset Management Module: Vendor addition

### ISSUE THREAD

**Issue by aparnacoronasafe** [ohcnetwork/care_fe#1705]
When registering an asset, also capture the vendor information like:
- Vendor Name
- Name of the customer support
- Contact Phone number
- Contact email

This information must also be visible in the Asset dashboard.

**Comment by peeyush14goyal** [comment]
@vigneshhari is backend ready for this?

**Comment by vigneshhari** [comment]
API has been added, Removing the backend tag.
