### ISSUE TITLE
Consultation update: user

### ISSUE THREAD

**Issue by aparnacoronasafe** [ohcnetwork/care_fe#1712]
Make visible the user that enters each consultation update

**Comment by arpancodes** [comment]
Hey @aparnacoronasafe you are talking about this page right?
![image](https://user-images.githubusercontent.com/42417893/127903083-2bdd5f9a-ff8c-42cc-9029-a84d1dbaf333.png)

**Comment by arpancodes** [comment]
@vigneshhari need this in the response of `consultation_daily_rounds_list` endpoint

**Comment by vigneshhari** [comment]
This is added to the API, removing the backend tag.
