### ISSUE TITLE
Admitted to Facility Type Filter

### ISSUE THREAD

**Issue by aparnacoronasafe** [ohcnetwork/care_fe#1718]
In-Patient list advanced filter, add a filter to sort by admitted to facility type

**Comment by khavinshankar** [comment]
@vigneshhari need API for filtering `patients` by `admitted_to_facility_type`

**Comment by vigneshhari** [comment]
@khavinshankar filter in API has been added, filter field is called facility_type, pass the actual value not the Enum.
