### ISSUE TITLE
Preview not working !!!!

### ISSUE THREAD

**Issue by samholics** [ohcnetwork/care_fe#1734]
after upload consultation files in patient's card  preview not available but only a blank page showing
![image](https://user-images.githubusercontent.com/75214902/128839041-1e93d963-2a36-4286-b544-f00c6ddffe5c.png)
also automatically downloading the file when we click on preview
In hospitals this file used to evaluate patient's condition and they totally depend upon this feature, so can you guys pls look into that??? it may affect shifting also
@bodhish

**Comment by shaileshaanand** [comment]
duplicate of https://github.com/coronasafe/care_fe/issues/1663 ?

**Comment by arpancodes** [comment]
Yes, closing.
