### ISSUE TITLE
Create a dahboard for district admin

### ISSUE THREAD

**Issue by bodhish** [ohcnetwork/care_fe#174]
The dashboard should have:

- [ ] total number of patients 
- [ ] Number patients in isolation/admitted/ICU/ventilator
- [ ] no. of tests requested/awaiting/result

**Comment by albseb511** [comment]
What should be the route?

`/district/:districtId`

I can get the district id from 
`/district/` api.


Is there already a page where the list of districts are shown and from there they get rerouted from? 

or do the district admins have a login form?

Is there an api to get all patients data based on district? is it still under works?

I see a patient sample list, which has filters for district.  it has a `patient_pk` param which I am not sure what it stands for.

or I can get all patients data which has a count field as reponse
Assuming its either no of total patients or total pages, I can change the limit to get all the data,
 and filter it based on the district and show the data.

But is this recommended?

**Comment by bodhish** [comment]
You check the avilable api documentation below.
 
https://api.care.coronasafe.network/swagger
https://api.care.coronasafe.network/redoc

You will have to create a summary dashbaord for a district admin level user. 

All the users use the same login. 
This can be `/dashboard` where the numbers change depending upon the user type

**Comment by albseb511** [comment]
okay alright understood on the route and user type. will get back to you if I have any doubts.

**Comment by bodhish** [comment]
@albseb511 any updates?

You can use https://careapi.coronasafe.in/swagger/  `facility_summary` api

**Comment by albseb511** [comment]
@bodhish hey sorry I think api had issues at that time. 
very held up at office atm. 
So this issue is still open now?
if so I can have a look over the weekend

**Comment by dauntlessnomad** [comment]
being worked on at https://github.com/coronasafe/dashboard . 
closing this issue @albseb511  please check the above repo
