### ISSUE TITLE
Add the following fields in create patient form

### ISSUE THREAD

**Issue by bodhish** [ohcnetwork/care_fe#175]
The following should be added to patient create/edit form.

- [x] `Date of return` 
- [ ] `Already prescribed medication for any underlying condition`

**Comment by albseb511** [comment]
can I take it up?

`/facility/:id/patient`

is this the route?

**Comment by albseb511** [comment]
Made a PR

https://github.com/coronasafe/care_fe/pull/189

@bodhish
