### ISSUE TITLE
Create a form to add / update health status for a patient

### ISSUE THREAD

**Issue by bodhish** [ohcnetwork/care_fe#176]
Daily health status of patients to be added

Rename other to (Current health status of the patient)

**Comment by dauntlessnomad** [comment]
https://api.care.coronasafe.in/redoc/#operation/consultation_daily_rounds_list

**Comment by albseb511** [comment]
right now there is a present health field.

is it to create historical field values?

Like `[ { date: "dd-mm-yyyy", health: "" } . {...} . {...}  ]` ?

It can be made with a button, onclick show a modal, select date and add/update health.

The data can be shown as how health changed from admission.

date: dd-mm-yy   health_1 --------> date: dd-mm-yy   health_2 ----->
