### ISSUE TITLE
Add search and filter options in Patients tab

### ISSUE THREAD

**Issue by bodhish** [ohcnetwork/care_fe#177]
Please add a filter to see positive cases alone. 

It would be nice to colour the positive cases patient card red and discharged/recovered patients card green. (or any other way to easily identifying, it will come handy when the no. of patients grows)

**Comment by cyriacbijun** [comment]
@bodhish  I have finished the card colour change and filtering of Positive changes in my forked repo, what should I do next?
Also, the Button for filtering needs to be placed according to your requirements. Currently, it's below the heading `Covid Suspects`

**Comment by jithinlal** [comment]
You can contact them in slack, or you could pull the latest changes from the forked repo and then create a pull request from your forked repo develop branch to the main repo develop branch
