### ISSUE TITLE
Sample test management - add filter 

### ISSUE THREAD

**Issue by samholics** [ohcnetwork/care_fe#1776]
In sample test management, add a filter known "BY FACILITY" in advanced filters

* logged in as Lab facility ( staff user id) 
* selected sample test
* opened  the sample test request dashboard 
* there we can see lots of request from various hospital facilities
* now only "status" and "result" filter in advanced filters.
![image](https://user-images.githubusercontent.com/75214902/131259669-2d98bb32-5429-4279-a92c-35f7bb8711df.png)

a particular lab gets requests from various facilities right, so this filter helps them to track the patient request card better.

**Comment by ghost** [comment]
@vigneshhari 
Need `facility` param in `/test_sample` endpoint for filter by facility.

**Comment by Apurva-Nagar** [comment]
@abhinandanarya06 Created a PR with the required changes to the backend. Removing backend label
