### ISSUE TITLE
Identify COVID re-infections

### ISSUE THREAD

**Issue by aparnacoronasafe** [ohcnetwork/care_fe#1788]
In CARE, currently, there is no way of identify re-infections.

The system must automatically detect if a patients disease status has gone from Positive to recovered/negative and then positive. 

But the second positive log shall not happen immediately after Recover/Negative status was marked, since this could be an error in data entry corrected.

**Comment by gigincg** [comment]
@vigneshhari What's your take on this?

**Comment by vigneshhari** [comment]
We store history for all patient-related data, with this we can identify how many unique times a given person has been infected with a disease, I think it's better to run this as an async task when a patients status changes from something to POSITIVE/ACTIVE, we can store infection details as an object or just store the count back in the patient object. We also need to design migrations to handle all the existing patients

**Comment by aparnacoronasafe** [comment]
this was a feature that was relevant during covid. 

This is however a good to have feature. to have a flag, whenever a patient is diagnosed with a disease, cured and then rediagnosed with the same disease again

**Comment by nihal467** [comment]
@aparnacoronasafe This data is available and can be calculated during analytics. If you need a feature around it please elaborate. Closing this.
