### ISSUE TITLE
Add new bed type in create bed type form

### ISSUE THREAD

**Issue by bodhish** [ohcnetwork/care_fe#180]
The facility should be able to select  `Single Room with attached bathroom`  in the choose bed type dropdown

**Comment by cyriacbijun** [comment]
I would like to take up the issue. Is there any dummy login credentials to see how the output looks like? @bodhish

**Comment by bodhish** [comment]
devstafftester
DevTesterStaff@123


Api docs https://api.care.coronasafe.in/redoc

Staging url

Care.coronasafe.in

**Comment by cyriacbijun** [comment]
The API is not providing the option for `single room with attached bathroom`
![image](https://user-images.githubusercontent.com/35319861/78327226-fd662f80-7599-11ea-812a-a05ee4b05331.png)

@bodhish 
Edit: thank you for updating API
