### ISSUE TITLE
Add an option to select facility type

### ISSUE THREAD

**Issue by bodhish** [ohcnetwork/care_fe#182]
The facility create/update form should allow users to choose the facility type.

Add drop down that could be used to choose one of [Government Hospital, Private Hospital]

**Comment by dauntlessnomad** [comment]
Api not yet created @vigneshhari

**Comment by vigneshhari** [comment]
Finished today eve itself

**Comment by amitbhoj-fc** [comment]
Can I pick this issue?

**Comment by dauntlessnomad** [comment]
sure . if not done already .
