### ISSUE TITLE
cleaup unused packages

### ISSUE THREAD

**Issue by bodhish** [ohcnetwork/care_fe#193]
Cleanup / remove unused packages from package.json

Example: draftjs

**Comment by amitbhoj-fc** [comment]
I am picking this task. Is anyone already works on it, let me know.

**Comment by amitbhoj-fc** [comment]
completed. Please concern the person review it and let me know if I need to change anything.
https://github.com/coronasafe/care_fe/pull/208

**Comment by SandeepThomas** [comment]
PR merged.
