### ISSUE TITLE
Daily rounds detail view and edit view

### ISSUE THREAD

**Issue by SandeepThomas** [ohcnetwork/care_fe#207]
Currently we are having a list view at /facility/205/patient/51/consultation/37/daily-rounds-list.

Need to create a new detail view on clicking the card and an edit button on the detail view to go to edit page. The create daily round page (src/Components/Patient/DailyRounds.tsx) can be modified to include the edit feature.

Detail 
route : /facility/205/patient/51/consultation/37/daily-rounds-list/{id}
swagger: https://api.care.coronasafe.in/redoc/#operation/consultation_daily_rounds_read

Edit 
route : /facility/205/patient/51/consultation/37/daily-rounds-list/{id}/update
Swagger: https://api.care.coronasafe.in/redoc/#operation/consultation_daily_rounds_update

**Comment by amitbhoj-fc** [comment]
I am picking this task. Please let me know if someone already working on it?

**Comment by amitbhoj-fc** [comment]
Hi all, 
I have completed this task. 
https://github.com/coronasafe/care_fe/pull/221
Please do the needful and let me know if in case of an issue.

Thanks:-
Amit

**Comment by SandeepThomas** [comment]
PR merged
