### ISSUE TITLE
Add an option to edit facility type in facility update

### ISSUE THREAD

**Issue by bodhish** [ohcnetwork/care_fe#214]
Thier should be an option update hospital type, (Public/private) in the hospital update tab

**Comment by anandsimmy** [comment]
@bodhish @tomahawk-pilot  @SandeepThomas 
I'm working on this, how many facility types should be given in dropdown.In api, 8 are listed
[Educational Inst, Private Hospital, Other, Hostel, Hotel, Lodge, TeleMedicine, Govt Hospital]
should we include all these or just (govt/private)

**Comment by qburst-sandeep** [comment]
@anandsimmy 
[(1, 'Educational Inst'), (2, 'Private Hospital'), (3, 'Other'), (4, 'Hostel'), (5, 'Hotel'), (6, 'Lodge'), (7, 'TeleMedicine'), (8, 'Govt Hospital')]

**Comment by SandeepThomas** [comment]
@anandsimmy 
(1, 'Educational Inst'), (2, 'Private Hospital'), (3, 'Other'), (4, 'Hostel'), (5, 'Hotel'), (6, 'Lodge'), (7, 'TeleMedicine'), (8, 'Govt Hospital')

**Comment by SandeepThomas** [comment]
done
