### ISSUE TITLE
Logout menu item positioning

### ISSUE THREAD

**Issue by saranjith** [ohcnetwork/care_fe#225]
The **Logout** option in the menu is a bit confusing. While the rest of the options are for navigation, only this corresponds to an action. There are chances that the users may click it by accident. When they do so, they get logged out instantly. 
We can:
1. Move this under the **User** menu item. Ask for confirmation after user clicks on the option.
2. Keep it as it is, but ask for confirmation once the user clicks on it.
Out of the two, I'd recommend option 1, as it will reduce the possibility of the user clicking on Logout by accident.

**To Reproduce**
1. Click on Logout from the side menu
2. User is logged out immediately.

**Expected behavior**
Can we make it as an accordion and push the logout button under it? like i said above, it will reduce the possibility of the user clicking it accidentally.
correct me if i got this wrong, but I don't think users once they log-in, they'll log out for a considerable amount of time. (I may be completely wrong at this assumption). so, keeping the logout below the user's name will be safer. also if there's a plan to add some more user specific actions(edit profile, change password), those can be accommodated as well.

**Screenshots**
![image](https://user-images.githubusercontent.com/266199/78574350-83f36900-7847-11ea-82c7-039e05aa8085.png)

**Desktop (please complete the following information):**
 - OS: MacOS Catalina
 - Browser: Chrome
 - Version: 80.0.3987.149

**Additional context**

**Comment by bodhish** [comment]
Would be great if you could add a PR 😀
