### ISSUE TITLE
Add localisation 

### ISSUE THREAD

**Issue by bodhish** [ohcnetwork/care_fe#232]
Labels and messages should be translated to all Indian languages as we have request from few other states to deploy the systems

**Comment by SandeepThomas** [comment]
@anandsimmy 
(1, 'Educational Inst'), (2, 'Private Hospital'), (3, 'Other'), (4, 'Hostel'), (5, 'Hotel'), (6, 'Lodge'), (7, 'TeleMedicine'), (8, 'Govt Hospital')

**Comment by amruthavijay88** [comment]
@shrihari689 - to create pull request.
