### ISSUE TITLE
Add More FIelds to Patient Sample Flow

### ISSUE THREAD

**Issue by vigneshhari** [ohcnetwork/care_fe#233]
TO BRING OUR SYSTEM IN LINE WITH ICMR SPECIMEN REFERRAL SYSTEM a couple of changes are made to the patient sample API, please view the list of changes and make the required changes in the creation and viewing of Patient Sample Data

Specimen Type (options) - With optional Text Field for Others Type
SARI (YES/NO)
ARI (YES/NO)
Unique ID - Id of the Patient Sample ( Made by the backend )
Name of Doctor
Diagnosis [FREE TEXT]- OPTIONAL
Differential diagnosis [FREE TEXT]- OPTIONAL
Etiology Identified [FREE TEXT]- OPTIONAL
Atypical presentation YES/NO  [FREE TEXT]- OPTIONAL
Unusual/Unexpected Course YES/NO

**Comment by bodhish** [comment]
Everything related to sample can stay in the sample request.

**Comment by SandeepThomas** [comment]
Added the fields in sample. has_sari is present in both sample and patient as of now.
