### ISSUE TITLE
Daily Rounds Details Page >> The "Time" value is not displayed in the field "Temperature Measured At"

### ISSUE THREAD

**Issue by roshinraj007** [ohcnetwork/care_fe#248]
In Patient Detail page >> View Daily Rounds Details Page :

For an existing record, the value of Date is displayed in the field "Temperature Measured At", but the 'Time' is not displayed. Please refer the screenshot attached. 

Expected : Both Date & Time must be displayed in the field "Temperature Measured At".

![temperature](https://user-images.githubusercontent.com/13899062/79137129-c67cee80-7dcf-11ea-983b-e967a27c1a3b.png)

**Comment by SandeepThomas** [comment]
fixed
