### ISSUE TITLE
Allow User Search By Phone Number

### ISSUE THREAD

**Issue by bodhish** [ohcnetwork/care_fe#250]
The backgorund seach for user is not working while creating picking the date via date picker

Allow User Search by phone number in user add

**Comment by SandeepThomas** [comment]
I cannot reproduce this issue. Only if both phone number and date of birth are entered and they are valid only then the background search will happen.

**Comment by SandeepThomas** [comment]
@bodhish

**Comment by SandeepThomas** [comment]
Done.
