### ISSUE TITLE
Cleanup users tab

### ISSUE THREAD

**Issue by bodhish** [ohcnetwork/care_fe#268]
Clean up users tab! 
![Screenshot from 2020-05-11 17-22-14](https://user-images.githubusercontent.com/14979190/81558849-05d93380-93ac-11ea-9237-13912bfe67c2.png)

- [ ] Random number `0` below user :thinking: 
- [x] Scope users by access level
   - Facility admin should see details of users linked to that facility. (staff, doctor, etc)
   - District admin should be able to see all the users (scope by district)
- [x]  Show name, contact, role and facility name for each user

**Comment by dauntlessnomad** [comment]
1st issue not reproduced
