### ISSUE TITLE
Add validation for corona triage form

### ISSUE THREAD

**Issue by bodhish** [ohcnetwork/care_fe#271]
![Screenshot from 2020-05-11 17-33-59](https://user-images.githubusercontent.com/14979190/81559758-a2500580-93ad-11ea-8aca-a73eb186b301.png)

The sum of `Advised Home Quarantin` , `Under Isolation`, `Reffered` should be eqal to `visited`

**Comment by dauntlessnomad** [comment]
Fixed https://github.com/coronasafe/care_fe/commit/e2a9c1a35d4915805f90e33f78e18b4e5a507272
