### ISSUE TITLE
Unable to create daily round for a user

### ISSUE THREAD

**Issue by bodhish** [ohcnetwork/care_fe#274]
Getting `500` for daily round create api
![Screenshot from 2020-05-11 17-44-01](https://user-images.githubusercontent.com/14979190/81560506-2656bd00-93af-11ea-972b-0b9d857044e6.png)

**Comment by dauntlessnomad** [comment]
@bodhish can you share the network tab screenshot
i cant reproduce this

**Comment by dauntlessnomad** [comment]
no issue found
