### ISSUE TITLE
Daily rounds breaking in consultation show

### ISSUE THREAD

**Issue by bodhish** [ohcnetwork/care_fe#275]
Getting `500` for daily rounds in  consultations show 
url : `https://care.coronasafe.in/api/v1/consultation/90237b4c-97d2-440e-a0c9-0f21781df7b6/daily_rounds/?limit=5&offset=0`

**Comment by dauntlessnomad** [comment]
@vigneshhari 
@anroopak

**Comment by vigneshhari** [comment]
issue is Fixed
