### ISSUE TITLE
Unable to create staff account from district admin

### ISSUE THREAD

**Issue by bodhish** [ohcnetwork/care_fe#276]
Getting the following error when i am trying to create a user.
![Screenshot from 2020-05-11 17-56-12](https://user-images.githubusercontent.com/14979190/81561387-ba755400-93b0-11ea-8f33-085d1e7a4685.png)
local_body - Cannot create for a different local body

**Comment by dauntlessnomad** [comment]
need to remove the facility check for that . 
its expecting a facility value .

**Comment by vigneshhari** [comment]
Issue not existing now
