### ISSUE TITLE
BUG: ICMR Form

### ISSUE THREAD

**Issue by bodhish** [ohcnetwork/care_fe#287]
## A1
- [x] incorrect data shown in  `Patient village / town`
- [x] check if the age calculation is correct

## A2 (all columns are required here )
- [x] collection date is blank 
- [x] option to add label for a sample
- [ ] option to add `sample repeated` flag
- [x] sample collection facility name missing 
- [x] sample collection facility pincode missing 

## A3 
- [x] Add a field `sample_patient_category` in be options are `[Cat 1, Cat 2, Cat 3, Cat 4, Cat 5a, Cat 5b]` 
- [x] fe should have an option to choose a category of the patient

## B.1
- [x] address is missing
- [x] pincode missing

**Comment by bodhish** [comment]
## ICMR form for reference

![IMG_20200613_145949](https://user-images.githubusercontent.com/14979190/84565463-f6705000-ad86-11ea-8546-7fee6aa8a618.jpg)

![IMG_20200613_145958](https://user-images.githubusercontent.com/14979190/84565459-f4a68c80-ad86-11ea-94e3-f04ec0b62e5d.jpg)

**Comment by dauntlessnomad** [comment]
This requires backend Changes @coronasafe/care-developers

**Comment by dauntlessnomad** [comment]
A2 collection date is coming as null from API @coronasafe/care-developers

**Comment by dauntlessnomad** [comment]
sample collection facility name missing
 sample collection facility pincode missing. 
not present in API @coronasafe/care-developers

**Comment by dauntlessnomad** [comment]
Looks like icmr form is having all the necessary fields but the data is not coming in @bodhish

**Comment by DrRahul** [comment]
![WhatsApp Image 2020-06-15 at 5 50 18 PM](https://user-images.githubusercontent.com/66953410/84657944-b64dd080-af32-11ea-919e-cf0b4468bd0d.jpeg)
we need to add 'Cat 0' in the ICMR form.

**Comment by dauntlessnomad** [comment]
option to add sample repeated flag requires change  from  backend @coronasafe/care-developers
