### ISSUE TITLE
Login Screen

### ISSUE THREAD

**Issue by dauntlessnomad** [ohcnetwork/care_fe#3]
Api to be avaliable at POST - https://dev.care.coronasafe.in/api/v1/login

Check if use is signed in GET - https://dev.care.coronasafe.in/api/v1/getcurrentuser

**Comment by gauravsoti1** [comment]
@tomahawk-pilot I'll be doing this. When will the apis be ready?

**Comment by dauntlessnomad** [comment]
@vigneshhari will provide the apis soon

**Comment by dauntlessnomad** [comment]
login and session is done

**Comment by dauntlessnomad** [comment]
done
