### ISSUE TITLE
Exportable (Excel) patient details for analysis

### ISSUE THREAD

**Issue by aparnacoronasafe** [ohcnetwork/care_fe#304]
PRIORITY!!!

The medical research team needs data to analyse. We need a feature to export patient data in a single excel sheet. The sheet must have the following columns:-
1. Patient Name (may be removed, replaced with a unique ID), 
2. age, 
3. gender, 
4. address, 
5. Locale body, 
6. travel history (international and domestic separately), 
7. contact history, 
8. SARI, 
9. other symptoms, 
10.medical history
11. Medical Status (Current),
12. Categorization (Mild/Moderate/Severe),
13. duration of hospital stay, 
14.Duration of positivity (of COVID 19), 
15. Isolation Ward/ICU/Ventilator,
16. Whether Oxygen Supplementation required.

This is an URGENT requirement. This will be the primary source of data for the doctors and scientists in the research team.

**Comment by bodhish** [comment]
Let's not export patient name.

**Comment by aparnacoronasafe** [comment]
@bodhish Can you please assign it to someone. This is IMPORTANT

**Comment by aparnacoronasafe** [comment]
@vigneshhari Please assign this to someone! URGENT!!

**Comment by vigneshhari** [comment]
@bodhish developers venam , i ded 😭

**Comment by dauntlessnomad** [comment]
@gvnidheesh  require your inputs on this
