### ISSUE TITLE
Add question "Are you a pregnant woman" to Patient Details form

### ISSUE THREAD

**Issue by aparnacoronasafe** [ohcnetwork/care_fe#308]
https://care.coronasafe.in/facility/6248f03b-cf47-4bfb-9b89-d2235082d8ff/patient

Please add a question with check box that reads as "Are you a pregnant woman?" to the form.

Antenatal cases are separated out from the very beginning. Therefore it is important to recognise and filter out such persons at the first instance.

**Comment by bodhish** [comment]
Please make the question `Antenatal ?` and a boolean which defaults to false.
As the data is entered by a hospital staff, it doesnt make sense to ask `Are you a pregnant woman?`

**Comment by vigneshhari** [comment]
adding this as a boolean field into the patient data form

**Comment by vigneshhari** [comment]
API is deployed, field is "is_antenatal" in the patient API.
