### ISSUE TITLE
Whether admitted asked twice

### ISSUE THREAD

**Issue by aparnacoronasafe** [ohcnetwork/care_fe#310]
https://care.coronasafe.in/facility/05fcf441-48b2-4d90-9389-f9ab9af107d5/patient/f49bf052-1f0e-4594-97e9-89d9bfa31ae9/consultation

In "Decision after OP Triage" once we mention admission, there is again a Y/N question on admission which then activates further fields about admission.

**Comment by dauntlessnomad** [comment]
it has a purpose. 😉

**Comment by aparnacoronasafe** [comment]
@tomahawk-pilot  what is the purpose?
