### ISSUE TITLE
Change layout of patient dashboard

### ISSUE THREAD

**Issue by aparnacoronasafe** [ohcnetwork/care_fe#311]
https://care.coronasafe.in/patients 

Please change the appearance of cards into a list. 
Against each patient name, we need the below options shown:-

"Patient Name".            {“View Details”_“Consultation”_”Daily Rounds”_“Sample Test”_“Shift” }
"Age" "Facility" “Admission Date”, A flag if patient is in ICU/Ventilator

**Comment by dauntlessnomad** [comment]
LIsts are not mobile friendly and will break the UI  thats why we have take it as cards

**Comment by aparnacoronasafe** [comment]
Can we have the buttons on the card then?
@tomahawk-pilot

**Comment by dauntlessnomad** [comment]
> Can we have the buttons on the card then?
> @tomahawk-pilot
that is possible. Please create an issue for that.

**Comment by dauntlessnomad** [comment]
#336
