### ISSUE TITLE
Add filters to sort patients by

### ISSUE THREAD

**Issue by aparnacoronasafe** [ohcnetwork/care_fe#312]
https://care.coronasafe.in/patients

Please add the following filters to sort patients by
1) Admission day. , 
2) ICU/Ventilator/Isolation, 
3) LSGT

**Comment by aparnacoronasafe** [comment]
Could you speed this up?

At least sorting by date of admission? @tomahawk-pilot

**Comment by dauntlessnomad** [comment]
#336 requieres the same fields in api

**Comment by vigneshhari** [comment]
Will do this

**Comment by MrRobz** [comment]
@vigneshhari if your done can you share the API details?

**Comment by bodhish** [comment]
Will not filtering by LSG

**Comment by aparnacoronasafe** [comment]
Why no filter by LSG?

**Comment by bodhish** [comment]
The filter is pretty complicated now and lsg filter is not something people would use everyday and i am ignoring it for now. 

They also have an option to download the data and filter.
