### ISSUE TITLE
Simplify Daily Rounds Form (Delete fields)

### ISSUE THREAD

**Issue by aparnacoronasafe** [ohcnetwork/care_fe#318]
https://care.coronasafe.in/facility/c92cc4df-0fea-4d37-9c24-1c9f07bfac23/patient/e26f7a88-03de-41d2-904f-482fc7335a05/consultation/377086b1-9322-4f16-b08f-5bca0ed18708/daily-rounds

Only keep the "Symptoms" "Category" and "Current Health" fields and delete the rest. 
an "Additional Notes" text field may be added.

**Comment by dauntlessnomad** [comment]
this data is depending to another data model .so closing this as  a won't fix
