### ISSUE TITLE
Correction in Patient Form

### ISSUE THREAD

**Issue by aparnacoronasafe** [ohcnetwork/care_fe#321]
https://care.coronasafe.in/facility/6248f03b-cf47-4bfb-9b89-d2235082d8ff/patient

In the field for "Disease Status", the drop-down that appears has "Recovery" as an option, there is another option "Recovered" too.

Please delete the former.

**Comment by vigneshhari** [comment]
Recovery is different from Recovered, right? Past tense vs Present participle

**Comment by dauntlessnomad** [comment]
@bodhish @aparnacoronasafe confirm this is still relevant

**Comment by bodhish** [comment]
Leave it for future reference.
