### ISSUE TITLE
Add more buttons to patient card

### ISSUE THREAD

**Issue by aparnacoronasafe** [ohcnetwork/care_fe#336]
https://care.coronasafe.in/patients

Against each patient name, we need the below options shown:-
"Patient Name". {“View Details”“Consultation””Daily Rounds”“Sample Test”“Shift” }

And the following information:-
"Age" "Facility" “Admission Date”, A flag if the patient is in ICU/Ventilator

**Comment by dauntlessnomad** [comment]
need api @vigneshhari

**Comment by dauntlessnomad** [comment]
- consultation id
- daily rounds id 
- A flag if the patient is in ICU/Ventilator

**Comment by aparnacoronasafe** [comment]
@tomahawk-pilot I cannot see this change in staging. Are we not doing this at all?

**Comment by dauntlessnomad** [comment]
We have additional views for this
