### ISSUE TITLE
Broken drop down menu in "Refer to another hospital"

### ISSUE THREAD

**Issue by aparnacoronasafe** [ohcnetwork/care_fe#354]
https://care.coronasafe.in/facility/874bff56-2d55-4f13-8ef1-bba9a0745a21/patient/26a64ed8-73fe-4514-b729-0d43ff717e1b/consultation

When "refer to another hospital " is chosen in the decision after OP triage, in the field that appears for "Referred to facility" the drop down menu does not show all facilities.

The error was reported in production. Kalamassery Medical College is trying to refer to ADLUX FLTC, but cannot find the facility in the dropdown menu.

**Comment by dauntlessnomad** [comment]
@coronasafe/care-developers

**Comment by aparnacoronasafe** [comment]
@vigneshhari This issue persists. Can we please find a fix. I was reported 20 days back. The field staff are getting impatient. 

@tomahawk-pilot @bodhish

**Comment by vigneshhari** [comment]
I believe the issue was fixed by @tomahawk-pilot

**Comment by vigneshhari** [comment]
@aparnacoronasafe can we move this to closed? 
@tomahawk-pilot this is deployed, right?
