### ISSUE TITLE
Request to Access Tele-medicine Database 

### ISSUE THREAD

**Issue by Jometjohn** [ohcnetwork/care_fe#356]

**Comment by aparnacoronasafe** [comment]
@tomahawk-pilot Please do the needful

**Comment by bodhish** [comment]
Hey sorry, we are not authorised to share data. The data can only accessed by a an authorised user in the system.

None of developers have access to the database, sorry

**Comment by aparnacoronasafe** [comment]
@bodhish but cant you build it as a feature? hiding the patient name?

or suggest way forward. Who can authorise?

**Comment by bodhish** [comment]
That should be feature request. We don't deal with data.

Do create a separate feature request on a data export feature.

**Comment by Jometjohn** [comment]
@bodhish Will i be able to access that feature afterwards?

**Comment by bodhish** [comment]
No, the data is encrypted and secure in nature, so i am authorised to share access.

**Comment by Jometjohn** [comment]
@bodhish I have put up a tele Med request
