### ISSUE TITLE
Shifting Module for tele-medicine 

### ISSUE THREAD

**Issue by aparnacoronasafe** [ohcnetwork/care_fe#357]
Shifting module must be built for Telemedicine.

When "shift" is opted for a particular patient in telemedicine, the below-attached questionnaire should appear
[SHIFTING QUESTIONNAIRE.docx](https://github.com/coronasafe/care_fe/files/4826986/SHIFTING.QUESTIONNAIRE.docx)

Shifting team to have a separate login.
The shifting team must be able to see list of patients. Options "Shifting complete" or "Pending" must appear against each patient listed there.

patient card must automatically go to the receiving facility

**Comment by dauntlessnomad** [comment]
@aparnacoronasafe post this in @coronasafe/telemedicine
