### ISSUE TITLE
Ambulance Data View

### ISSUE THREAD

**Issue by dauntlessnomad** [ohcnetwork/care_fe#36]
- [ ]  district wise count as cards

- [ ]  view to select an ambulance from a list filtered district wise.
         - [ ]   pagination and search

- [ ]  ambulance detail view with details

**Comment by SandeepThomas** [comment]
Hi, do we have any design for these pages?

**Comment by dauntlessnomad** [comment]
We don't have designs for any of the pages  
It's make as you go.

**Comment by cyriacbijun** [comment]
@tomahawk-pilot  where can I get the API info for checking the ambulance info?

**Comment by dauntlessnomad** [comment]
Check the read me

**Comment by anandsimmy** [comment]
@cyriacbijun 
https://dev.care.coronasafe.in/swagger/

**Comment by dauntlessnomad** [comment]
is anyone working on this . else am taking this up >>

**Comment by dauntlessnomad** [comment]
Depricated . Not required
