### ISSUE TITLE
Add Features for facilities

### ISSUE THREAD

**Issue by bodhish** [ohcnetwork/care_fe#370]
This is for filering the facilities based on the features.

Example. 
- Supports antenatal care

Dr. Athul could add more details here.

**Comment by athulmanuel** [comment]
first filter must be on whether its a Govt Facility or Private. - most of the management and reach is very much different in these 2 settings. - so a filter which allows us to select multiple option like we do for symptoms f could give us know how on the facility details in a govt. hospital- it is more vital now as we are mainly using govt hospitals for covid.
Even regarding the facility - govt v/s private has a standard differences.  

on categorizing facilities on the features we had made a basic google sheet. 
https://docs.google.com/spreadsheets/d/1g3oWe9zyrtgqQQJ6Rchz5hQT9oQR3q7dP4a7fu0S3To/edit?usp=sharing
The above mentioned feature categorization would help us give a clue on which hospital to refer to irrespective of the available beds.

we need to know the specific beds( ward or ICU) which has been designated for Covid, as we want to continue the Non- covid system without crashing, just knowing the total capacity would not help us i deciding on the capacity for taking in covid cases. We need specific data on the beds occupied v/s total on covid designated beds

also in the tile for each facility a display of total covid beds ( ward + ICU) occupied- this will give us an overview of covid patients in each facility. in the present scenario we have to add each type and also it does not show the covid facility status

as days go by, isolation facility will be opened in each hospital and it will be like a water tight compartment, but it will expand according to demand and we have to know and keep track of it.

**Comment by aparnacoronasafe** [comment]
Let's have a feature to list facilities in any hospital.  

Add a field for "Services available" and give a dropdown with the Multi-select option.

A few options must be 
- CT Scan Facility
- Maternity care
- X-Ray facility
- Neonatal care
- Operation theater

This information must be visible as small flags below phone. no. on hospital dashboard (https://care.coronasafe.in/facility/551f9e09-04a3-4f52-ade2-1db45588741d) as well as on facilities list (https://care.coronasafe.in/facility)

**Comment by shivankacker** [comment]
@aparnacoronasafe are these the only features or are there more?
