### ISSUE TITLE
Inter-facility Transfer  

### ISSUE THREAD

**Issue by aparnacoronasafe** [ohcnetwork/care_fe#377]
The amended Transfer flow is very good. 

But it requires one change. 

Presently all patients, by default are marked as "Allowed to transfer". Can we change that and keep default setting as "Not Allowed to Transfer"

In that case as and when a patient is sent from a hospital, they can change the setting from "Not Allowed to Transfer" to "Allowed to transfer".

The other way around doesn't make sense. 

@tomahawk-pilot

**Comment by dauntlessnomad** [comment]
this is possible.
this was our initial plan. 
 @vigneshhari please do the needful for this. change

**Comment by bodhish** [comment]
Let's not automate it. Add this as a flag while creating the consultation. 

Their is a possibility of consultation without admission so let's not block stuff.

**Comment by bodhish** [comment]
Also if a hospital staff is is not available on call to switch the flag it can create delays. Let's not set the flag automatically

**Comment by aparnacoronasafe** [comment]
1) Can we please have the default option of "TRANSFER DISABLED" for only people ADMITTED within the facility. At discharge, this should automatically turn to "Enable Transfer". This is so that after recovery when the patient visited another hospital for any new illness, his patient card must new available to the new hospital, even without the old hospital actively participating in the process of transfer of patient card. 
The transferability of a patient must switch at admission or discharge. We need to keep in mind that there may be facilities like the telemedicine, which will be integrated into the CARE system as a facility where all patients will be outpatients. Patient cards must be easily transferrable to any hospital from here without the hospital having to place a request with the telemedicine to allow the transfer. 

2) Also, at the time of transfer, a transfer summery, much like the discharge summary may be made available in a printable form. @bodhish Please elaborate on this one.

@vigneshhari please do the needful

**Comment by vigneshhari** [comment]
This is already implemented

**Comment by bodhish** [comment]
@aparnacoronasafe can you extract our point 2 to another card

**Comment by dauntlessnomad** [comment]
implemented
