### ISSUE TITLE
"Refer to another hospital" function

### ISSUE THREAD

**Issue by aparnacoronasafe** [ohcnetwork/care_fe#379]
https://care.coronasafe.in/facility/c2d37a3e-3b82-4a12-881f-5faca5a44134/patient/26bfd2e5-380d-4153-836a-69ac74e5990a/consultation

In the consultation page, when a patient is referred to another hospital, in the field that appears to enter the facility name, it always appears as "No facility found"

Can we make it a free text field where any facility name can be typed in? Since this entry doesn't affect the transfer of patient card, why do we have to restrict entries to only facilities within the system? Why can't we let the hospitals just type in any text into the field? @tomahawk-pilot  Please comment

**Comment by aparnacoronasafe** [comment]
@tomahawk-pilot please do the needful

**Comment by dauntlessnomad** [comment]
that is counterproductive. since facility mapping is part of the system and will cause major issues. when free text is allowed
