### ISSUE TITLE
Patient Data Entry

### ISSUE THREAD

**Issue by dauntlessnomad** [ohcnetwork/care_fe#38]
backend issue  https://github.com/coronasafe/care/issues/80
in frontend, the patient name field should be read-only. and must populate a unique uid like smart-puppy or similar

Deadline is tonight in staging and production by tommorow morning.

**Comment by bodhish** [comment]
Lets stop work on this issue for now.

We would moslty be collecting this data using sprinklr plarform.

https://developer.sprinklr.com/

**Comment by dauntlessnomad** [comment]
Completed
