### ISSUE TITLE
OP Consultation Patients.

### ISSUE THREAD

**Issue by aparnacoronasafe** [ohcnetwork/care_fe#381]
**Situation to be addressed**- When a corona suspect/a person under quarantine/corona positive patient, comes in for a consultation for any other purpose, say an antenatal case coming in for regular check-up, where do you record that visit?

**Proposed solution**- 
https://care.coronasafe.in/facility/c2d37a3e-3b82-4a12-881f-5faca5a44134/patient/26bfd2e5-380d-4153-836a-69ac74e5990a/consultation
Please add an option under "Decision after OP Triage/Consultation" in the drop-down menu, add "OP Consultation". When the same is selected, a free text space must appear to give in details like Antenatal consultation, dialysis, etc etc.

@tomahawk-pilot

**Comment by dauntlessnomad** [comment]
this requires backend changes. @vigneshhari 
@aparnacoronasafe  please give a list of fields to be included.

**Comment by aparnacoronasafe** [comment]
Please add a field in the consultation form, saying "OP Consultation"

When this is selected, an additional text field must appear to give details.

**Comment by aparnacoronasafe** [comment]
Please make this field appear beside "Decision after OP Triage". And it must be mandatory to either fill "Decision after OP Triage" or "OP Consultation"

**Comment by vigneshhari** [comment]
API is deployed, Consultation API has a consultation_notes to store notes and it has OP consultation as a suggestion.
