### ISSUE TITLE
Allow edit for for daily rounds

### ISSUE THREAD

**Issue by bodhish** [ohcnetwork/care_fe#385]
The facilty should be given an option to edit the daily rounds creadted in order to avoid duplication per day.

**Comment by dauntlessnomad** [comment]
its already implemented. 

![Screenshot 2020-07-06 at 2 33 13 PM](https://user-images.githubusercontent.com/11440246/86575914-a22b4b00-bf95-11ea-9bea-75f4797f5184.png)

Please confirm if this is working
