### ISSUE TITLE
Hard refresh Button

### ISSUE THREAD

**Issue by dauntlessnomad** [ohcnetwork/care_fe#393]
**Create a button in the UI to hard refresh cache and update service worker .**

**Comment by psjishnu** [comment]
@tomahawk-pilot 

Where will be the suitable place for button .

Do we need to use function `window.location.reload(false)` ?

**Comment by Robin-Thomas-577** [comment]
Ideally, I would say there need not be a cache clear btn. Service worker should update itself and clear needed cache after each deployment.

adding a refresh btn, would be confusing to the user.

**Comment by dauntlessnomad** [comment]
this issue is relevant because some are using really old browser versions and phones. so we need to have a button to do a hard refresh to clear cache and restart sw
