### ISSUE TITLE
Shifting System

### ISSUE THREAD

**Issue by athulmanuel** [ohcnetwork/care_fe#396]
Shifting will be our main role in managing the pandemic.

The major problem is to find out where to shift according to the availability- this could be decided with the proper map that has been developed. if we have a search option with given criteria it would be better. 
eg: male patient in quarantine having chest pain, - so we need to take him to a place where there is a facility with isolation facility with ECG support and physician on duty. ( at present only place is Kalamashery medical college) but later we are expecting more centers having such facility in the isolation area so would need to search that. 

so when the request is created the doctor needs to enter the requirement he need in a format. a match needs to be found depending on the address.----- the doctor calls the facility and confirms whether they can receive the patient---- once the destination is fixed. ---- doctor confirms it--- the request goes to the shifting team ( mainly comprising of non medical people but a doctor would be there to trouble shoot and guide) ---- shift team assigns the vehicle. and coordinates with the patient or the center that needs to shift the patient and carries out the shift.. ---- this info has to go to the family of the patient as well as the medical officer in charge of the patient ( his native panchayath). this is vital as the patient doesn't have family with him/her they need to be informed in person but a message would confirm it, as when the load increases we are not sure whether calling would be feasible every time we shift.   

the following would be a sample what the shifting team needs to know for shifting a patient. 

[SHIFTING QUESTIONNAIRE.docx](https://github.com/coronasafe/care_fe/files/4881046/SHIFTING.QUESTIONNAIRE.docx)

**Comment by dauntlessnomad** [comment]
@bodhish
