### ISSUE TITLE
Sample test result - enter manually

### ISSUE THREAD

**Issue by athulmanuel** [ohcnetwork/care_fe#397]
Till results are coming through the care system, all the sample requests will be pending. till then we need to have need have an option to add the result manually. otherwise even in the discharge summary the result will be pending. 

without adding this option the facilities wont use the discharge option of CARE. it is very important to do this ASAP
@bodhish

**Comment by dauntlessnomad** [comment]
added a role check bypass to allow anyone to change status and put results in

**Comment by aparnacoronasafe** [comment]
Tested. 
Please close the issue
