### ISSUE TITLE
Transfer NOT allowed

### ISSUE THREAD

**Issue by athulmanuel** [ohcnetwork/care_fe#398]
on the patient card, this must be the default, so that no other facility can take the patient unless the admitted facility allows,
on planning of discharge, this could be changed so that either the other facility can take in the patient if not transferred from this facility.

**Comment by dauntlessnomad** [comment]
@vigneshhari please run a migration for this

**Comment by vigneshhari** [comment]
All existing patient transfer status to false ?

**Comment by tomahawk-pilot** [comment]
@anroopak  please confirm

**Comment by vigneshhari** [comment]
@tomahawk-pilot does this issue persist ?
