### ISSUE TITLE
registration page

### ISSUE THREAD

**Issue by dauntlessnomad** [ohcnetwork/care_fe#4]
POST api to be avaliable at https://dev.care.coronasafe.in/api/v1/signup
fields and registration types will be updated soon.

**Comment by injas427** [comment]
I'll work on this. Please update once the fields are ready.

**Comment by dauntlessnomad** [comment]
@injas427 api is ready

**Comment by injas427** [comment]
@tomahawk-pilot [#45](https://github.com/coronasafe/care_fe/pull/45). Please do check
