### ISSUE TITLE
Viewing Saved Consultation Details of patients

### ISSUE THREAD

**Issue by aparnacoronasafe** [ohcnetwork/care_fe#402]
https://care.coronasafe.in/facility/c2d37a3e-3b82-4a12-881f-5faca5a44134/patient/26bfd2e5-380d-4153-836a-69ac74e5990a/consultation/3bfbc1b0-7a42-4750-b34b-c278ff77edf4/

Error appears while viewing saved consultation details
<img width="541" alt="Screenshot 2020-07-07 at 2 28 55 PM" src="https://user-images.githubusercontent.com/67050716/86765975-82fcee00-c067-11ea-8f13-77be67ecdadf.png">

**Comment by aparnacoronasafe** [comment]
This same issue had occurred earlier and i believe @tomahawk-pilot had fixed it.

**Comment by dauntlessnomad** [comment]
@vigneshhari backend fix please
