### ISSUE TITLE
Blood Group : to me mandatory field

### ISSUE THREAD

**Issue by aparnacoronasafe** [ohcnetwork/care_fe#404]
https://care.coronasafe.in/facility/c2d37a3e-3b82-4a12-881f-5faca5a44134/patient

Make Blood Group a Field Mandatory field

**Comment by aparnacoronasafe** [comment]
@tomahawk-pilot URGENT. Please assign soon

**Comment by aparnacoronasafe** [comment]
@tomahawk-pilot URGENT. Please assign soon

**Comment by dauntlessnomad** [comment]
@vigneshhari this requires api change. 
validation already present in fe

**Comment by vigneshhari** [comment]
API Changes Made, Closing this issue.
