### ISSUE TITLE
Need auto-direct from patient form to consultation form

### ISSUE THREAD

**Issue by aparnacoronasafe** [ohcnetwork/care_fe#405]
From https://care.coronasafe.in/facility/c92cc4df-0fea-4d37-9c24-1c9f07bfac23/patient form, redirect staright to the below form 
https://care.coronasafe.in/facility/c92cc4df-0fea-4d37-9c24-1c9f07bfac23/patient/f9c491c2-15ee-48d6-90d5-0e1d1c53d182/consultation

**Issue**- At hospitals, the data entry persons are filling the basic details of a patient and they forget to add consultation. 

URGENT: @tomahawk-pilot

**Comment by dauntlessnomad** [comment]
@aparnacoronasafe we need to think this over. since consultation requires the patient id. 
so patient register response is required to create a consultation. 
lets think this over.

**Comment by aparnacoronasafe** [comment]
@tomahawk-pilot I understand. Once the patient detail form is saved, a patient ID will be generated instantly right. So instead to taking the user to the patient dashboard, can he not be taken to the consultation form?
