### ISSUE TITLE
In sample testing, after giving the option "awaiting", there is no option to change the status to "positive"/"negative" for a patient card

### ISSUE THREAD

**Issue by amruthavijay88** [ohcnetwork/care_fe#428]
**Describe the bug**
In sample testing, after giving option "awaiting", there is no option to change the status to "positive"/"negative" for the same patient card (button saying"update sample test status" disappears).

**To Reproduce**
Using the labadmin credentials, login. 
1. Go to 'Sample Test" in the LHS of page. 
2. Click on 'the patient card' that has come for testing.
3. Click on 'Update sample test status', select approved. Then update the status as 'sample taken and sent to collection center".  Then select 'received at lab', and then finally select 'test completed'.
4. When we type 'test completed', an option 'result' pops up with dropdown options - positive/negative/awaiting/invalid. If we select 'awaiting', then automatically - we won't be able to change the result status any further. The button "update sample test status" disappears. 

**Expected behavior**
We need to have the option 'Update same test status" and select 'result' options such as positive/negative/invalid - (after having given 'awaiting' as an option, in this case)

**Desktop (please complete the following information):**
 - OS: [Windows]
 - Browser [chrome]

**Comment by dauntlessnomad** [comment]
@vigneshhari   anything we can do for this ??

**Comment by vigneshhari** [comment]
As i see it, We can remove awaiting as an option.

**Comment by dauntlessnomad** [comment]
ok
please make the backend change
and we will make the necessary fe changes

**Comment by vigneshhari** [comment]
Removing the option does not need a backend change.

**Comment by vigneshhari** [comment]
@tomahawk-pilot if the option is removed, please close this issue
