### ISSUE TITLE
Referring after triage.  

### ISSUE THREAD

**Issue by athulmanuel** [ohcnetwork/care_fe#431]
In our CARE system, while entering the OP/Triage details; if decided to enter the option on 'Referring to another facility' the list is blank.

**Comment by dauntlessnomad** [comment]
@athulmanuel  did you try typing in a hospital name ??

**Comment by dauntlessnomad** [comment]
![Screenshot 2020-07-12 at 3 02 34 PM](https://user-images.githubusercontent.com/11440246/87243099-ba491180-c450-11ea-9df3-deeddbcf93ae.png)
its working fine for me

**Comment by athulmanuel** [comment]
![Uploading 87276825...]()

**Comment by athulmanuel** [comment]
It not working for me.

**Comment by athulmanuel** [comment]
@tomahawk-pilot - i checked from both admin log in and facility log in. 
In the admin log in we are able to refer, but in the facility log in only that same particular facility comes in the Dropbox. No other facility is appears in the drop box.

**Comment by dauntlessnomad** [comment]
@athulmanuel fixed this in todays release . Please Verify
