### ISSUE TITLE
Find an Alternative for pnotify

### ISSUE THREAD

**Issue by dauntlessnomad** [ohcnetwork/care_fe#433]
WARNING in ./node_modules/pnotify/dist/es/PNotify.js
Module Warning (from ./node_modules/source-map-loader/index.js):
(Emitted value instead of an instance of Error) Cannot find source file '..//PNotify.js': Error: Can't resolve '..//PNotify.js' in '/Volumes/Storage/Code/coronasafe/care_fe/node_modules/pnotify/dist/es'
 @ ./src/Utils/Notifications.js 1:0-46 5:25-32
 @ ./src/Redux/fireRequest.tsx
 @ ./src/Redux/Reducer.tsx
 @ ./src/index.tsx
 @ multi ./src/index.tsx webpack-dev-server/client

We need to find an alternative for pnotify package.

**Comment by MrRobz** [comment]
updating PNotify might solve these errors.

**Comment by dauntlessnomad** [comment]
tried and failed

**Comment by MrRobz** [comment]
hmm, updating fixed this warning for me. Let me give a PR you can check.

**Comment by dauntlessnomad** [comment]
do we need the entire pnotify package ? we can just use the core pack and that theme right ?

**Comment by MrRobz** [comment]
yes
