### ISSUE TITLE
Blood Group: Add UNKNOWN

### ISSUE THREAD

**Issue by aparnacoronasafe** [ohcnetwork/care_fe#438]
https://care.coronasafe.in/facility/005215fa-c20a-4409-aabf-4349dde4504d/patient

In the mandatory field of blood group, please add UNKNOWN as an option in the dropdown menu.

**Comment by aparnacoronasafe** [comment]
@tomahawk-pilot Can we have this built soon?

**Comment by dauntlessnomad** [comment]
we can do this
@vigneshhari please update the api and let me know

**Comment by vigneshhari** [comment]
Will add it

**Comment by vigneshhari** [comment]
Pushed API to staging

**Comment by dauntlessnomad** [comment]
Completed. Fe also . Will have a drop down object named UNK
