### ISSUE TITLE
Search by NAME: in sample management

### ISSUE THREAD

**Issue by aparnacoronasafe** [ohcnetwork/care_fe#439]
https://care.coronasafe.in/sample

Please give a search by name function here.

**Comment by dauntlessnomad** [comment]
Not possible @aparnacoronasafe . there is no direct relation between a patient and sample

**Comment by dauntlessnomad** [comment]
@vigneshhari willl explain

**Comment by vigneshhari** [comment]
You can search for a patient, get his details page, and there you'll get his list of samples. this should suffice, right ?
