### ISSUE TITLE
Exportable Patient Details

### ISSUE THREAD

**Issue by aparnacoronasafe** [ohcnetwork/care_fe#440]
The exportable patient details need edits:

The columns in the excel sheet may be as follows:
**(A few of this information are not captured in the system yet, they may have to be added as fields in the different forms. I will mention the forms as well. There will have to be an extra form added for discharge as well)**

1- **Unique ID of the patient**- this unique ID may be searchable on CARE system. In case the district admin wants to identify the patient using the unique ID, it must be possible to do so on CARE. (Adding a search bar with patient ID to Patient/Suspect Tab only available to the district admin should work)

2- **Date of Admission**- info available from consultation form

3- **Age**- info available from patient basic details form

4- **Gender** - Male/Female/Others- info available from patient basic details form

5- **Native State**- This may be added as a new field in the patient basic details form (https://care.coronasafe.in/facility/005215fa-c20a-4409-aabf-4349dde4504d/patient)

6- **District Currently in**- Info can be pulled from patient basic details form

7- **Locale Body**- info available from patient basic details form

8- **Ward/block/division**- Info available from patient basic details form

9- **Occupation**- This may be added as a new field in the patient basic details form (https://care.coronasafe.in/facility/005215fa-c20a-4409-aabf-4349dde4504d/patient)

10- **Front-Line Worker**- Yes/No
The question about "Medical Worker" may be replaced in the basic patient details form (https://care.coronasafe.in/facility/005215fa-c20a-4409-aabf-4349dde4504d/patient) with the question "Whether a front-line worker"- Give the definition of the front-line worker there (A front line worker is an individual who has worked in a COVID related environment with possible exposure in the last 14 days. Eg: Doctor at a COVID treatment centre, Security personnel at Airport, Housekeeping staff at a corona care facility etc.)

11- **International Travel (in last 28 days)**-Yes/No - Info available from patient basic details form

12- If yes for 11, Countries visited- Info available from patient basic details form

13- if yes for 11, date of arrival in India-  Info available from patient basic details form

14- **Interstate Travel**(in last 28 days)- Yes/No - This may be added as a new field in the patient basic details form (https://care.coronasafe.in/facility/005215fa-c20a-4409-aabf-4349dde4504d/patient)

15- if yes for 14, places visited

16-  if yes for 14, Date of arrival in Kerala

17-  if yes for 14, Mode of interstate transportation

18- **Conatct with Covid Postive patient**- Yes/no- Info available from patient basic details form

19- If yes for 18, Name of the covid patient- This may be added as a new field in the patient basic details form (https://care.coronasafe.in/facility/005215fa-c20a-4409-aabf-4349dde4504d/patient)- NOT A MANDATORY FIELD

20- **Conatct with quarantined person**- Yes/No- The question on contact with COVID suspect in the atient basic details form (https://care.coronasafe.in/facility/005215fa-c20a-4409-aabf-4349dde4504d/patient) may be rephrased as Contact with quarantined person. 

21- If yes for 20, **Details of quarantines person**- Within Family/Outside Family/ Others(free text space)- This may be added as a new field in the patient basic details form (https://care.coronasafe.in/facility/005215fa-c20a-4409-aabf-4349dde4504d/patient)

22- **History of visiting any known hotspots in the last 14 days**- Yes/No/Not sure - This may be added as a new field in the patient basic details form (https://care.coronasafe.in/facility/005215fa-c20a-4409-aabf-4349dde4504d/patient)

23- List of places you have travelled to in the last 14 days- Free text space - NOT A MANDATORY FIELD- This may be added as a new field in the patient basic details form (https://care.coronasafe.in/facility/005215fa-c20a-4409-aabf-4349dde4504d/patient)

24- **Public transport used in the last 14 days**- None/ Autorickshaw/ bus/ Taxi/ Others (free text space)- This may be added as a new field in the patient basic details form (https://care.coronasafe.in/facility/005215fa-c20a-4409-aabf-4349dde4504d/patient)

25- **Attended any public gathering in the last 14 days**- Yes/No/Unsure- This may be added as a new field in the patient basic details form (https://care.coronasafe.in/facility/005215fa-c20a-4409-aabf-4349dde4504d/patient)

26- if yes for 25, Details- (free test space)- This may be added as a new field in the patient basic details form (https://care.coronasafe.in/facility/005215fa-c20a-4409-aabf-4349dde4504d/patient)

27- **Number of people living in the same household**- This may be added as a new field in the patient basic details form (https://care.coronasafe.in/facility/005215fa-c20a-4409-aabf-4349dde4504d/patient)

28- **No. of dependents over 60 years**-  Info available from patient basic details form

29- **No. of chronic diseased dependents**-  Info available from patient basic details form

30- **Blood Group**-  Info available from patient basic details form

31- **Reason for testing**- (free test space)- This may be added as a new field in the sample request form https://care.coronasafe.in/facility/005215fa-c20a-4409-aabf-4349dde4504d/patient/6d14160e-de5c-46bd-8331-1825fdedca14/sample-test

32- **Approximate height in cms**- T'his may be added as a new field in the patient basic details form (https://care.coronasafe.in/facility/005215fa-c20a-4409-aabf-4349dde4504d/patient)

33- **Approximate weight in Kgs**- This may be added as a new field in the patient basic details form (https://care.coronasafe.in/facility/005215fa-c20a-4409-aabf-4349dde4504d/patient)

34- **Date of onset of symptoms**- Info available from consultation form 

35- **Date of swab testing**- The only relevant date here is the date of first RT-PCR swab test done where the result was positive. The other test details are irrelevant here.- Info available in Sample management 

36- **Symptoms at the time of admission/testing**- informaton must be pulled from both consultation form as well as sample request form. In consultation form (https://care.coronasafe.in/facility/005215fa-c20a-4409-aabf-4349dde4504d/patient/6d14160e-de5c-46bd-8331-1825fdedca14/consultation) in Symptoms, add "Headache", "Loss of smell", "Loss of taste", replace SARI with "breathing difficulty".

37- **Commorbidities** - Info to be pulled from patient basic details form. Make edits to the medical history section. Rename it as "Commorbidities" and add the following options in addition to the existing options- 
a) None
b)Pregnancy
c) High Cholestrol
d) Others (Free ext space)

38- **Category** - Info available in consultation form

39- **Date of last test in which found negetive**- Info may be pulled from sample maagement system

40- **Complications developed during hospital stay**- yes/no/not known - This may be added as a field in Discharge form.

41- if yes for 40, Details of the same- This may be added as a field in Discharge form.

42- **ICU Admission**- Yes/No/Not known - This info may be either pulled from the consultation details. But I do not think the hospitals will be sure to update consultation. The question may be added to the discharge form 

43- **Ventilator Support**- Yes/No/Not known- This info may be either pulled from the consultation details. But I do not think the hospitals will be sure to update consultation. The question may be added to the discharge form 

44- **Date of discharge**- may be pulled from discharge.

- [ ] Build search by Unique patient ID available to the district admin (refer to point 1 above)

- [ ] Make changes in basic patient details form (refer to points 5, 9, 10, 14-17, 19, 20, 21, 22, 23, 24, 25, 26, 27, 32, 33 and 37)

- [ ] Make changes in Consultation form (refer to point 36 above)

- [ ] Make changes to Sample request form (refer to point 31 above)

- [ ] Build discharge form (refer to point 40, 41, 42 and 43 above )

- [ ] Edit the patient details export sheet ( refer to all points above)

- [ ] Run test- Approval by Aparna/Amrutha/Bodhi @bodhish 

- [ ] Deploy to production

**Comment by aparnacoronasafe** [comment]
URGENT!!! HIGH PRIORITY!!!

@tomahawk-pilot

**Comment by aparnacoronasafe** [comment]
While building discharge form, please refer to Issue #441

**Comment by bodhish** [comment]
@aparnacoronasafe it a humongous change. Please split this as multiple issues.

As of Patient export, let this issue handle export of just the data we store at this point of time. 

Let improve the exports once the other fields are added. 

Questions are more on the lines of surveillance, i am not sure if those are part of a patient management system.

Let's discuss it on a new issue.

**Comment by aparnacoronasafe** [comment]
Alright. lets go ahead and add all the info that we are already capturing. (in all the forms, patient basic info, consultation and sample management.

**Comment by aparnacoronasafe** [comment]
hey. any update?

**Comment by bodhish** [comment]
Resolved
