### ISSUE TITLE
Discharge: Amendments

### ISSUE THREAD

**Issue by aparnacoronasafe** [ohcnetwork/care_fe#441]
An ideal discharge summary should look like this
https://drive.google.com/file/d/1ihy9XD-9XKLngoha4Zq8lOVdrIP151AH/view?usp=sharing

Please create a discharge form, and add all necessary fields

Issue 440 also suggests some fields in Discharge form, Please read Issue #440

**Comment by aparnacoronasafe** [comment]
@tomahawk-pilot Please assign at the earliest.

**Comment by vigneshhari** [comment]
@bodhish what all things needs to be changed design and data wise

**Comment by vigneshhari** [comment]
Also @aparnacoronasafe that drive doc's permission is limited right ?

**Comment by bodhish** [comment]
@vigneshhari We need to add

- Course in facility
- Discharge advice.

Its also recommended if we could create templates for discharge advice.

Ex,
Use case, 90% of a contents on a covid positive case would be same. It would be great if their is an option to choose a discharge summary template. (can be extracted out as a new issue)

**Comment by vigneshhari** [comment]
@bodhish we have all data related to a patient coming into the HTML template now, if the current template needs more data change the template with the required changes. 

As for the concept of the template, this can be easily implemented in the backend, you can go ahead and create multiple templates in the same folder as the existing template and I'll accept another param in the discharge summary to specify the summary template. 

ping me after the template is complete, i can provide more data to the template if required.

**Comment by aparnacoronasafe** [comment]
@vigneshhari when can we have this closed?

**Comment by vigneshhari** [comment]
@bodhish do you have an ETA on the template changes ?

**Comment by aparnacoronasafe** [comment]
Let's add the discharge advice available in the sample discharge summary as a template. I don't think we should spend more time on this

**Comment by bodhish** [comment]
It can't be a backend template.

It should be a db field and fe should have options to update the same.

We could think about caching the advice at fe but that will eventually have to be facility specific custom messages.

@vigneshhari let's consider this for weekend release

**Comment by aparnacoronasafe** [comment]
When can we expect the new discharge summery?

**Comment by aparnacoronasafe** [comment]
Also, we are adding diagnosis also right?

**Comment by aparnacoronasafe** [comment]
Tested Discharge. The following issues were noted:

1)  "None" appears against Discharge date

2) In Consultation form, when Other symptoms are chosen, and details are given, the same does not appear under symptoms in discharge summary.

**Comment by aparnacoronasafe** [comment]
Comorbidities must be shown on the Discharge summary

**Comment by aparnacoronasafe** [comment]
Final Changes Needed to Discharge:-

1) "None" appears against Discharge Date

2) In the Consultation form, when Other symptoms are chosen, and details are given, the same does not appear under symptoms in the discharge summary.

3) Comorbidities from basic patient form Must appear in the discharge summary. 

4) Discharge form to be built. The discharge form must have
a) Course of treatment within the facility (Treatment summary) 
b) Discharge advice
c) Prescription module


@tomahawk-pilot

**Comment by aparnacoronasafe** [comment]
Add a field for 'Diagnosis' above symptoms, with free text space with 2 lines.

Add a field "verified by" at the bottom, with a space to enter name.

**Comment by aparnacoronasafe** [comment]
Let us split "treatment summary" into "course in facility" and "treated with"

Lab report: label for testing needs to be visible in discharge summery. May be replaced for diagnosis.

**Comment by aparnacoronasafe** [comment]
We need the following changes in the Discharge Summary.

1) Add a field for IP No. Along with the basic patient details on top of the summary 

2) We need a field “Diagnosis” right above symptoms. A short text space may be added in consultation for the same.

3) At the bottom add a field “Verified by” where the doctors' name can be typed in. A short text space may be added in consultation for the same. Space must be enough to type in names and designations of 2 doctors. A discharge summary has no authenticity unless it's verified by 2 doctors. 

4) Rename “Treatment Summary” as “Course within the facility”. Change to be made in consultation form as well.

5) Add a field “Treated with” right below #4. A short text space may be added in consultation for the same.

6) In the Lab Report Table, please remove Diagnosis and add “Label”. This is the “Label” given in the Sample Request Form.

7) Remove NHM and Dept of health services Logo.

This is the final set of changes noted after personally meeting with the staff at GH Ernakulam. 

@tomahawk-pilot please take note. This is the aggregate of all changes required.

**Comment by bodhish** [comment]
Fixed in multiple other issues
