### ISSUE TITLE
Discharge Form

### ISSUE THREAD

**Issue by vigneshhari** [ohcnetwork/care_fe#448]
Create a discharge form, attached to the consultation card,
It should have two fields, 
1) Course in Current Facility ( Free Text Area ) ( type: string ) ( API Key : course_in_facility )
2) Discharge advice ( Prescription ( Module built by @bodhish  ) ) ( type : JSON ) ( API Key : discharge_advice )

The data should be posted to the consultation patch API.

**Comment by athulmanuel** [comment]
@tomahawk-pilot --- status?
