### ISSUE TITLE
error while saving consultation of a patient transferred from another facility

### ISSUE THREAD

**Issue by aparnacoronasafe** [ohcnetwork/care_fe#455]
![IMG_6553](https://user-images.githubusercontent.com/67050716/87871869-c8a7a800-c9d1-11ea-8760-f587142f247b.JPG)

This error shows up when consultation is saved for a patient just transferred in from another facility.

The issue was reported in production. I ran a test on staging and the error came up.

@tomahawk-pilot to be resolved at the earliest

**Comment by dauntlessnomad** [comment]
fixed on next release
