### ISSUE TITLE
Consultation form: Add new category "Asymptomatic" 

### ISSUE THREAD

**Issue by aparnacoronasafe** [ohcnetwork/care_fe#456]
https://care.coronasafe.in/facility/c2d37a3e-3b82-4a12-881f-5faca5a44134/patient/7e32bd9b-a8f6-462f-8445-260338fdb4de/consultation

In consultation page, under category, in the drop down menu, please Add "ASYMPTOMATIC" as the first option

**Comment by aparnacoronasafe** [comment]
Initially there were only 3 categories, A,B and C. The guidelines have changed now and Asymptomatic is not included in Category A. 

Hence the change.

**Comment by vigneshhari** [comment]
@tomahawk-pilot the API's are done, you can proceed to make the UI changes.
