### ISSUE TITLE
Discharged Patient, when transferred to new facility still appears as discharged

### ISSUE THREAD

**Issue by aparnacoronasafe** [ohcnetwork/care_fe#459]
When a patient is discharged from a facility and later transferred to another facility, The patient card still appears as a discharged patient. Only option of discharge summary appears instead of options to add consultation/ request for sample test etc.

<img width="1408" alt="Screenshot 2020-07-20 at 3 37 22 PM" src="https://user-images.githubusercontent.com/67050716/87926402-48e80f00-ca9f-11ea-8508-def110c39400.png">

**Comment by vigneshhari** [comment]
This is a backend Issue, the issue should be solved in staging now.

**Comment by vigneshhari** [comment]
@aparnacoronasafe it seems to be working when i tested, test it again and close this issue if it's okay.
