### ISSUE TITLE
Op Consultation details not visible in saved consultation card

### ISSUE THREAD

**Issue by aparnacoronasafe** [ohcnetwork/care_fe#460]
https://care.coronasafe.in/facility/c2d37a3e-3b82-4a12-881f-5faca5a44134/patient/7e32bd9b-a8f6-462f-8445-260338fdb4de/consultation/0c0303b7-24d9-4db2-8acf-4bd329ad4bd4/

A consultation is saved with OP Consultation, and details of OP consultation was typed into the free text field. When viewing the saved consultation, the detail of OP consultation does not appear. Please add the filed with details

**Comment by bodhish** [comment]
Solved
