### ISSUE TITLE
Prevent duplication of patient card

### ISSUE THREAD

**Issue by aparnacoronasafe** [ohcnetwork/care_fe#464]
A patient card with same number and DOB must not be allowed to be created unless it is with a different name.

**Comment by aparnacoronasafe** [comment]
@bodhish

**Comment by aparnacoronasafe** [comment]
I see that you have highlighted the options appearing to create a new patient card/transfer existing patient. Also, the message to enter DOB correctly. 

Yet I believe the system should block any attempt to make a duplicate card for a patient based on the unique combination of the 2 data (Name, DOB and phone number)

This is a flaw at the very root of our system. The earlier we mend it the better. 

From my end, I will strengthen the training and STRICTLY ask the data entry persons to NEVER create duplicates.

But the threat of one unaware data entry personal ruining the credibility of our data persists. 

@bodhish @tomahawk-pilot Please comment

**Comment by bodhish** [comment]
It's never a flow. It was designed to support it.
Only human can create duplicates. If they are doing it with the current flow, they will do the same even if we separate it out.

Its allowed to create patients with same phone number and date of birth as their would be cases where these two conditions are true in the real world

**Comment by aparnacoronasafe** [comment]
Why can't we have the name as an identifying factor too?

**Comment by bodhish** [comment]
Name can't be used as it would create even more edge cases.
- spelling mistakes 
- full name vs first name
