### ISSUE TITLE
Capture Patient Shifting Flow

### ISSUE THREAD

**Issue by bodhish** [ohcnetwork/care_fe#469]
As the number of cases are growing, the district administration wants a system to manage shifting.

- The facility should have an option to request shifting for a patient based on consultation. 
- All the shifting request created by the facility should be listed
- Facility should have an option to see incoming patients as seperate tab
- district admin should see and have an option to update shifting

## shifting
- direction of shift - UP / Down 
- orgin facility
- destination facility  (optional)
- emergency flag
- reason for shifiting (text)
- vehicle_of_preference (text) (optional)
- comments (optional)
- status [ pending, approved, rejected, final_destination_confirmed, awaiting_vechicle, completed ]

https://github.com/coronasafe/care/issues/435

**Comment by dauntlessnomad** [comment]
new facility type added:::
https://github.com/coronasafe/care_fe/commit/d102c62e8e0608aebdd32e5d7204a3614104bc24
shifting choice list with key added
https://github.com/coronasafe/care_fe/commit/f5a02f5b84e5a8122f49d78e0388f500f25ad63b

**Comment by dauntlessnomad** [comment]
@MalayaliRobz

**Comment by dauntlessnomad** [comment]
@vigneshhari please share the api details

**Comment by vigneshhari** [comment]
Check swagger under shifting

**Comment by MrRobz** [comment]
> Check swagger under shifting

and where is the swagger page? link pls.

**Comment by dauntlessnomad** [comment]
https://careapi.coronasafe.in/redoc/#tag/shift

**Comment by dauntlessnomad** [comment]
https://careapi.coronasafe.in/swagger

**Comment by MrRobz** [comment]
@bodhish could share the user flow. Or validate mine from what I understood.

User flow in patient page:
1. Admins/management-staff of a facility should be able to "request shift" for a patient.
2. In patient page, there will be another button named "request shift".
3. On clicking navigate to shift page. User is asked to fill a form containing:- 
    "direction of shift",
    "origin-facility",
    "emergency flag",
    "reason for shifting",
    "vehicle_of_preference",
    "comments",
    "status"
4. User can come back to this page to edit status or other values of the shift.

User flow in facility page:
1. In the facility page, there will be another button "list shifts".
2. When clicked, navigate to a page that shows a list of shifts happening and patient associated.

Also Doubt: what did you mean by "Facility should have an option to see incoming patients as separate tab"?

**Comment by bodhish** [comment]
@MalayaliRobz 

1. True

2. It can be on the consultation tab. Shifting request can only be made on the last consultation.

3. Origin facility and status will be automatically added by the server.

4. Origin facility can delete the shifting request

## New page shifting on Nav

- it will have 3 tabs, pending, incoming shifts and completed a
Shifts.

Pending will be all shifting request created by the same facility which are not complete

Incoming will be the list of request where destination is marked as that facility

Completed shifts are onces with status complete.

The listing should have an option to edit the shifting the shifting request (all fields except origin) 

The listing should show the patient and consultation details. 

Ideally the page would look like trello without the drag drop feature where each list would be statues. ( let's skip that for now 😁) 

## new facility type

We should add a new facility type shifting to facility (code - 1300)

**Comment by MrRobz** [comment]
@bodhish , @vigneshhari , @tomahawk-pilot 
have a look at this mocks https://www.figma.com/file/BvqT8JH8FllE2s9kEUuteX/Care-shift-mocks
Tell me if they make sense and what we can improve.

**Comment by vigneshhari** [comment]
LGTM.
Btw Robin bro , ippazha aale kande 😅. Username kandit manasilayilla. Hi 😅

**Comment by bodhish** [comment]
@MalayaliRobz it looks good, the only change is see is on the trello like Board is that it will need more Columns based on status. 

pending, rejected,approved final_destination_confirmed, awaiting_vechicle, completed

The tabs on my mind look like this
![Screenshot from 2020-07-24 13-47-52](https://user-images.githubusercontent.com/14979190/88372828-4abe1500-cdb4-11ea-9e34-43f31bad3422.png)

**Comment by MrRobz** [comment]
Have build a lean down version shifting.  https://github.com/coronasafe/care_fe/pull/472

1. Did not go with the Trello approach as of now as it would need hitting API multiple times and felt complex to finish in 2 days. 
2. In patient page, if the patient has a shifting record associated, I was not able to show that data in the patient page as frontend didn't know if a shift is associated to that patient or not. @vigneshhari 
3. In shifting apps, status is in some places a no and some places string(like "PENDING") can we use string in all places. @vigneshhari 
4. Shifting PUT request is failing for me. Could you help me figure why @vigneshhari
