### ISSUE TITLE
Shifting: Changes 

### ISSUE THREAD

**Issue by aparnacoronasafe** [ohcnetwork/care_fe#479]
1) Shift patient button to move from consultation to the patient dashboard

2) https://care.coronasafe.in/shifting "Shifting approving facility" need not be shown on the patient card

3) Please make the drop-down menu to update status right on the patient card here https://care.coronasafe.in/shifting

4) Flag of "emergency" must be more noticeable. 

- [x]  Name of "Shifting approving facility" drop-down menu must show ONLY shifting facility, not all facilities.

6) Rework on incoming patients interface

**Comment by bodhish** [comment]
Incoming patients should be a tab on the shifting dashboard

**Comment by bodhish** [comment]
Fix https://github.com/coronasafe/care_fe/commit/3db38d2478c723fa4f9efde1858c456129c8e92b

lets not address the rest for v1 release

**Comment by aparnacoronasafe** [comment]
Need a search bar by patient name  and phone number in Shifting Tab.- VERY URGENT

**Comment by aparnacoronasafe** [comment]
Also allow option to update status right on the patient card

**Comment by aparnacoronasafe** [comment]
Have time stamp on shifting card. This is important to identify for the shifting team.

Can we have comments, atleast only the first line visible on the patient card itself

**Comment by aparnacoronasafe** [comment]
Can we have a notification appear for the incoming facility, with an audio alert

**Comment by aparnacoronasafe** [comment]
Also, can we have the patient card pushed for shifting later appear on top of the list rather than at the bottom in the shifting tab?

LIFO is what we need

**Comment by aparnacoronasafe** [comment]
Please add serial number to the lists in shifting tab.

In the patient shift form, please move the submit button from bottom right corner to top right corner. This was updating status and saving it becomes easier.

**Comment by bodhish** [comment]
@aparnacoronasafe don't add new feature requests as part of another issue. The original issue related to this thread is resolved
