### ISSUE TITLE
Add a confirmation message in Ambulance Enrollment Page

### ISSUE THREAD

**Issue by bodhish** [ohcnetwork/care_fe#48]
“I / We confirm and agree that the Ambulances enrolled in the Private Voluntary Online Ambulance Network by filling this online form will work under instruction and direction of the State Mission Director, National Health Mission, Kerala or officers / teams duly authorised by the State Mission Director, National Health Mission, Kerala."

**Comment by MathewtheCoder** [comment]
@bodhish So we have to have a checkbox showing this message at the end of this form right ? Can i work on this ?
![image](https://user-images.githubusercontent.com/10682672/77448434-cd3ec400-6e16-11ea-9503-a2edae38f1e2.png)

**Comment by bodhish** [comment]
Yes,

You can take it up. Please make sure the button is disabled unless they accept the terms.

**Comment by MathewtheCoder** [comment]
Okay sure

**Comment by SandeepThomas** [comment]
Hi @MathewtheCoder, sorry for not mentioning this earlier, but I'm actually working on this page right now.

**Comment by MathewtheCoder** [comment]
@SandeepThomas Oh if you have finished it then its okay. I have completed it now also.

**Comment by SandeepThomas** [comment]
I'm making some other changes also to this page including some fixes. Also I'm trying to add a dialog box instead of checkbox. 
@bodhish if you require checkbox, @MathewtheCoder can push his changes and I can integrate it into my code. please confirm.

**Comment by MathewtheCoder** [comment]
@SandeepThomas It's okay since its a very small change. Its better if you continue with it since you are working on the page.

**Comment by SandeepThomas** [comment]
Ah, ok. Thanks for confirming.

**Comment by bodhish** [comment]
a checkbox will be simpler right?

**Comment by SandeepThomas** [comment]
I was thinking of a confirmation dialog on clicking Save Details, can do a checkbox if that's only needed.

**Comment by SandeepThomas** [comment]
@bodhish Please close this issue.
