### ISSUE TITLE
List live, discharged and transfred patients on facility/patients

### ISSUE THREAD

**Issue by bodhish** [ohcnetwork/care_fe#483]
- [x] Show live patients as default choise on facility listing.
- [x] Add discharged tab (set filter discharged on the list api)
- [x] Add transferred tab (set filter transferred on the list api)

This is how i would love the UI to be like. All filters on the patients page should be compatible with the tabs
![Screenshot from 2020-07-30 01-34-33](https://user-images.githubusercontent.com/14979190/88847969-70f51200-d205-11ea-9fd9-2e9cd09e732a.png)

**Comment by dauntlessnomad** [comment]
@vigneshhari idunnulla api edarnnu ??

**Comment by vigneshhari** [comment]
Patient api il filters ond

**Comment by dauntlessnomad** [comment]
ok
