### ISSUE TITLE
Create a Kanban Flow for shifting

### ISSUE THREAD

**Issue by bodhish** [ohcnetwork/care_fe#484]
The shifting should have a Kanban flow to understand the data better>
- Drag and drop is not required

![Screenshot from 2020-07-30 03-21-42](https://user-images.githubusercontent.com/14979190/88857463-f1bb0a80-d213-11ea-9185-98a0421954c1.png)

**Comment by athulmanuel** [comment]
It must be visible in one view.  

When we search as per the tag ( approved/rejected/ etc), even if it is 'completed', the card will invisible in the view, have to slide).  That make the prices long.

**Comment by dauntlessnomad** [comment]
fixed
