### ISSUE TITLE
Other field for commorbidities

### ISSUE THREAD

**Issue by aparnacoronasafe** [ohcnetwork/care_fe#485]
https://care.coronasafe.in/facility/874bff56-2d55-4f13-8ef1-bba9a0745a21/patient/26a64ed8-73fe-4514-b729-0d43ff717e1b/update

An additional option "Others" to be added to comorbidities. An additional text field must appear for details.

**Comment by dauntlessnomad** [comment]
@vigneshhari  one more field in the patient register field

**Comment by dauntlessnomad** [comment]
Completedhttps://github.com/coronasafe/care_fe/commit/fd5010187587e69d946c42510a98bdcafb920a08

**Comment by dauntlessnomad** [comment]
https://github.com/coronasafe/care_fe/commit/fd5010187587e69d946c42510a98bdcafb920a08
