### ISSUE TITLE
'Transfer NOT allowed'  be changed before clicking shift.

### ISSUE THREAD

**Issue by athulmanuel** [ohcnetwork/care_fe#490]
At times the shift will be planned and request send but the card might not be in 'allowed transfer'. It creates confusion at the other end because they cannot import the care

**Comment by dauntlessnomad** [comment]
@vigneshhari do we have a solution for this. 
cc @bodhish

**Comment by bodhish** [comment]
It's handled by BE i guess

**Comment by bodhish** [comment]
solved
