### ISSUE TITLE
Add search by patient name on shifting and sample dashboards

### ISSUE THREAD

**Issue by bodhish** [ohcnetwork/care_fe#491]
Add search by patient name on sample dashboard 
Add search by patient name on test dashboard

**Comment by dauntlessnomad** [comment]
https://github.com/coronasafe/care_fe/commit/e44fcb4252135ebf84e403000ec09d1b0d06b0d9
https://github.com/coronasafe/care_fe/commit/39b2d1ea39f60bdb586618277820422372062340

**Comment by dauntlessnomad** [comment]
Done
