### ISSUE TITLE
jerk while selecting referral

### ISSUE THREAD

**Issue by athulmanuel** [ohcnetwork/care_fe#495]
while we select referral to another facility, there is severe jerking and not able to view.

**Comment by dauntlessnomad** [comment]
Is this in mobile view ??

**Comment by bodhish** [comment]
Desktop i guess. Try xl breakpoint in Chrome devtools

**Comment by athulmanuel** [comment]
In desktop. 
Not able to access CARE in iPhone. Not even chrome browser.
