### ISSUE TITLE
Filter by facility is not work for patients page

### ISSUE THREAD

**Issue by bodhish** [ohcnetwork/care_fe#501]
When a district admin visits `facility/facility_id/patients` all patients are shown.

Expected behavior. 
- [ ] Should show only patients on that facility.

**Comment by aparnacoronasafe** [comment]
Refer to #498 #499

**Comment by dauntlessnomad** [comment]
#498  #499

**Comment by dauntlessnomad** [comment]
@bodhish we can add a filter for that

**Comment by bodhish** [comment]
It would be good if the filter could be auto applied based on the url
