### ISSUE TITLE
Support Telemedicine in Care

### ISSUE THREAD

**Issue by bodhish** [ohcnetwork/care_fe#512]
- [x] consultation should have an option to assign from a list of doctors.
- [x] add actions for patients
- [x] add flag telemedicine in consultation
- [ ] sync all fields in consultation with the API. (allow adding prescription here - (the current one is part of discharge summary)
- [ ] Add a separate discharge form which allows editing of discharge_summary and advice ( https://github.com/coronasafe/care_fe/issues/513 )

**Comment by dauntlessnomad** [comment]
@bodhish can you list out the api;s per list.

**Comment by athulmanuel** [comment]
@bodhish @tomahawk-pilot  update on this please.. planing to decentralize this next week. tele medicine will be an integral part of it

**Comment by bodhish** [comment]
Closing this as most of it was done
