### ISSUE TITLE
Support pharmacy

### ISSUE THREAD

**Issue by bodhish** [ohcnetwork/care_fe#514]
Add a new tab pharmacy
- [ ] should list all prescriptions on the facility given to a patient. 
- [ ] it should have an option to print the prescription
- [ ] edit status of the prescription 

## Prescription Index

![Screenshot from 2020-08-10 02-14-21](https://user-images.githubusercontent.com/14979190/89741562-e2f41380-daaf-11ea-98b3-d5134f487c04.jpg)

## Prescription Print View
![Screenshot from 2020-08-10 02-16-10 (1)](https://user-images.githubusercontent.com/14979190/89741598-29497280-dab0-11ea-9692-10114766c07a.jpg)

**Comment by athulmanuel** [comment]
@bodhish--- in CARE?

**Comment by bodhish** [comment]
Yes, when we move telemedicine, pharmacy should also work right.

**Comment by athulmanuel** [comment]
@bodhish. Yup. And it must be fast.  The time is closing. Doctors are getting prepared  for tele Medicne from field. For that this is very essential.

**Comment by khavinshankar** [comment]
@bodhish where do we need to add this pharmacy tab?

**Comment by bodhish** [comment]
@khavinshankar lets work on it after the surge

**Comment by aparnacoronasafe** [comment]
@bodhish shall we get this scoped out for the current situation?

**Comment by bodhish** [comment]
Yep; its a good to have feature

**Comment by bodhish** [comment]
Will scope it as part of HMIS
