### ISSUE TITLE
Change to Triage

### ISSUE THREAD

**Issue by aparnacoronasafe** [ohcnetwork/care_fe#521]
https://care.coronasafe.in/facility/baf42ae1-3159-4a53-9f26-72ca9daccc1b/triage

Rename "patients in isolation" to "Suspects isolated"
Add "Total number of confirmed positives"

Make these fields visible on triage dashboard for facilities as well.

@tomahawk-pilot please assign at the earliest

**Comment by tomahawk-pilot** [comment]
Am sleeping

**Comment by dauntlessnomad** [comment]
@vigneshhari please add a total number of confirmed possitive in the api

**Comment by dauntlessnomad** [comment]
@vigneshhari 

- [ ] Add "Total number of confirmed positives"

please do this and let me know

**Comment by vigneshhari** [comment]
API Changes made

**Comment by aparnacoronasafe** [comment]
@tomahawk-pilot  I dont see this change in .Network

**Comment by dauntlessnomad** [comment]
Not deployed
