### ISSUE TITLE
Add pnotify for notifications

### ISSUE THREAD

**Issue by bodhish** [ohcnetwork/care_fe#53]
Browser notification for success message looks bad. 

https://www.npmjs.com/package/pnotify will be a good solution

**Comment by melvin2016** [comment]
let me work on this.

**Comment by melvin2016** [comment]
@bodhish Is this alert box for FacilityCreate.tsx?

**Comment by bodhish** [comment]
Ideally all alerts should be moved to notifications.

Facility create
Ambulance create. Etc

**Comment by melvin2016** [comment]
@bodhish I can't access the page for Facility create locally? are there any credentials which I need to get access to the page?

**Comment by bodhish** [comment]
Can you ping on slack so that others could help you
