### ISSUE TITLE
Change the colour of "Add Triage"

### ISSUE THREAD

**Issue by aparnacoronasafe** [ohcnetwork/care_fe#533]
https://care.coronasafe.in/facility/c2d37a3e-3b82-4a12-881f-5faca5a44134

Please change the colour of add triage button. 

Because in all the options that appear on top right corner of the page, add triage is the only thing hospitals are mandated to update everyday. A lot of people miss the option since it sits together with all these other options. Changing colour would make it stand out and make it easier for the user to locate it. 

@tomahawk-pilot

**Comment by bodhish** [comment]
Fixed in #536
