### ISSUE TITLE
Change in UI

### ISSUE THREAD

**Issue by aparnacoronasafe** [ohcnetwork/care_fe#534]
One major change repeatedly requested from the field is to have more things that appear on each screen. Right now there is a lot of negative space on the screen. To view more details or to access more function the user has to repeatedly click multiple times on various options which makes the experience more tedious and less efficient. 

The following are suggested :

1) Change the layout of the patient tab (https://care.coronasafe.in/patients). make it appear as a list. Its easier to browse and more patients can fit in a page.  [MOST IMPORTANT]

2) In the facility dashboard (https://care.coronasafe.in/facility/a31e6a24-0146-4043-b295-3a6c2fe7e095) reduce the size of total capacity cards. No. of doctors may be simply shown in a small table. Only the latest triage details may be made visible here with an option to expand it to see past details. The idea is all this must be visible to the user in one screen without having to scroll down.

**Comment by bodhish** [comment]
Fixed in #536
