### ISSUE TITLE
adding DOB and phone number in  Shifting card

### ISSUE THREAD

**Issue by athulmanuel** [ohcnetwork/care_fe#538]
since pull feature is not yet up in shift, we need these details in the card to pull the card in a usual way

![WhatsApp Image 2020-08-24 at 1 22 24 PM](https://user-images.githubusercontent.com/64475161/91021215-15a21e00-e611-11ea-9cc8-88717d4e062c.jpeg)

**Comment by dauntlessnomad** [comment]
we will do this in shifting patient homepage

**Comment by athulmanuel** [comment]
@tomahawk-pilot .. status

**Comment by dauntlessnomad** [comment]
will be deployed tonight

**Comment by bodhish** [comment]
@tomahawk-pilot add this inside the overlay

**Comment by tomahawk-pilot** [comment]
added to shifting details page.

**Comment by dauntlessnomad** [comment]
these details are already present inside the shifting details view
