### ISSUE TITLE
Downloading patient list 

### ISSUE THREAD

**Issue by athulmanuel** [ohcnetwork/care_fe#539]
while we download patient list, even if we enter from the login facility, the whole list comes. 

the whole list is not full, even if we download as admin

![total patients](https://user-images.githubusercontent.com/64475161/91021934-1a1b0680-e612-11ea-8a76-78b68c065ced.jpg)

![download pt list](https://user-images.githubusercontent.com/64475161/91021967-269f5f00-e612-11ea-9298-030135eba8d1.jpg)

**Comment by athulmanuel** [comment]
@tomahawk-pilot 
@bodhish 
please reopen issue. Tested and not satisfied

Still it comes to only 472 . Rest are missing.

and even now when we log in from separate facility

**Comment by dauntlessnomad** [comment]
Fixed
