### ISSUE TITLE
various admission status needed in CARE 

### ISSUE THREAD

**Issue by athulmanuel** [ohcnetwork/care_fe#540]
We need an admission status for each patient 
admission status - admitted stable in ward/ admitted stable in ICU/ admitted stable in gyneac ward/ admitted in peadiatric ward/   admitted on ventilator / referred/ discharged/ expired

**Comment by dauntlessnomad** [comment]
@athulmanuel need more info on this

**Comment by athulmanuel** [comment]
@tomahawk-pilot - i think we can take this by combining both type of bed admitted in and daily rounds status.

we might need to add these types of beds in the admission status 
![add gyne and pead](https://user-images.githubusercontent.com/64475161/91635164-bc245f80-ea13-11ea-977b-1b4c07a0a197.jpg)

**Comment by vigneshhari** [comment]
@tomahawk-pilot options added with the following Codes (30, "Gynaecology Ward"),(40, "Paediatric Ward")
