### ISSUE TITLE
Patient data format 

### ISSUE THREAD

**Issue by athulmanuel** [ohcnetwork/care_fe#541]
it would goof if we could have the download in the following format,. 

Patient ID | Patient Name | Patient Phone Number | Date Of Birth | Facility Name | Age | Gender | Local Body | District | State | Nationality | Disease Status | admission status | referred  or transferred to | Remarks | Number of people aged above 60 living with   the patient | Number of people who have chronic diseases   living with the patient | Blood Group | Is the Patient a Medical Worker | Confirmed Contact with a Covid19 Carrier | Suspected Contact with a Covid19 Carrier | Estimated Contact Date | Traveled to Any Foreign Countries in the   last 28 Days | Patient's Current Health Details | Already prescribed medication if any | Does the Patient Suffer from SARI | Patient's information received date | Date of Admission | Date of Onset of Symptoms | Symptoms at time of consultation | Category | Examination Details | Suggestion | Date of Consultation | Date of discharge/ expired

**Comment by bodhish** [comment]
@vigneshhari looks like this one is for the backend.

**Comment by athulmanuel** [comment]
@vigneshhari - status please

**Comment by athulmanuel** [comment]
would be needing minor changes in this list from time to time. 
if we don't update it time to time, it will affect the usability of people in the field and hence would not use our system

**Comment by vigneshhari** [comment]
Sorry! totally missed this, will get on this ASAP.

**Comment by athulmanuel** [comment]
Need the ward number after it is added and also the whole address as well

**Comment by vigneshhari** [comment]
@bodhish all changes pushed to staging, check and deploy

**Comment by athulmanuel** [comment]
could be name the download list with facility name or if its admin, then with admin name.

**Comment by athulmanuel** [comment]
Forgot to mention , 'Address' as well in the list.

**Comment by vigneshhari** [comment]
@bodhish review and close
