### ISSUE TITLE
feature - change from 'covid suspects' to 'Patient' 

### ISSUE THREAD

**Issue by athulmanuel** [ohcnetwork/care_fe#547]
We need to change the terminology from covid suspects to patient. we are mainly using CARE for positive patients, and even if we are entering suspects( with is a minority) they fall under the category of ' patients' . it is less confusing, 'Covid Suspects is very confusing. 
![change to patient details](https://user-images.githubusercontent.com/64475161/91149332-924bff80-e6d8-11ea-9c34-640d4a2150e7.jpg)

**Comment by bodhish** [comment]
Fixed
