### ISSUE TITLE
adding Domiciliary care in  Decision after triage

### ISSUE THREAD

**Issue by athulmanuel** [ohcnetwork/care_fe#548]
We need to add an option of 'Domiciliary Care' in the options of Decision after Triage

![add domiciliary care](https://user-images.githubusercontent.com/64475161/91156488-d55ea080-e6e1-11ea-9ab3-c8dfdb62821b.jpg)

**Comment by athulmanuel** [comment]
@tomahawk-pilot- status please

**Comment by vigneshhari** [comment]
@tomahawk-pilot Added option "DC" for Domiciliary Care, check swagger for more documentation.
