### ISSUE TITLE
Add a mandatory field for ‘ward’

### ISSUE THREAD

**Issue by athulmanuel** [ohcnetwork/care_fe#550]
Need to add 'ward' in the first demographic page while adding the patient details. It's should be after panchayath. 
It should be a mandatory field.

**Comment by athulmanuel** [comment]
@bodhish . need this ASAP

**Comment by vigneshhari** [comment]
Changes to API Pushed

**Comment by athulmanuel** [comment]
people are confusing with the ward number in their hospital...
could we change the fiel name from 'ward' to 'ward/division of respective LSGI'

actualy, the ideal situation will be that, the way each State is entered, then the districts will come up then the LSGI list will come up. so once the LSGI has been selected then the ward/division number must be asked.  

@tomahawk-pilot @bodhish 

later if we could develop a system where once we enter LSGI and ward number - the corresponding Field health facility  comes up.  I have asked to get the excel sheet of it. later add the MO and contacts according to this
