### ISSUE TITLE
Enable support for IOS devices 

### ISSUE THREAD

**Issue by bodhish** [ohcnetwork/care_fe#553]
The usage of `localstorage` for caching the login credentials blocks the login on IOS devices as the app doesn't have access to the local storage.

**Comment by aparnacoronasafe** [comment]
unable to login, when the credentials are entered and submitted, the fields just go blank again and page remains the same.

**Comment by aparnacoronasafe** [comment]
same issue persists

**Comment by bodhish** [comment]
@athulmanuel can you check on your phone?

**Comment by aparnacoronasafe** [comment]
unable to log-in. Once I enter the credentials, it wouldn't proceed
