### ISSUE TITLE
an option to attach a file

### ISSUE THREAD

**Issue by athulmanuel** [ohcnetwork/care_fe#556]
would need an option to enter a file ( either a document or a image or pdf) 

this function would be needed both in OP triaging as well as daily rounds and in Discharge summary

**Comment by athulmanuel** [comment]
Status please

**Comment by vigneshhari** [comment]
Since this is a big requirement, we will try to work on it over the weekend.

**Comment by athulmanuel** [comment]
@vigneshhari 👍

**Comment by athulmanuel** [comment]
@bodhish -- any way forward in this?
