### ISSUE TITLE
Accepting and card pulling- final step of shifting process

### ISSUE THREAD

**Issue by athulmanuel** [ohcnetwork/care_fe#559]
instead of clicking complete by shifting team, kindly make the last step by the receiving facility,.That is, once the card comes to the tab of 'TRANSFER IN PROGRESS' , these cards must be accepted and the receiving facility must be able to pull the card into their facility. 
 this is needed ASAP

**Comment by bodhish** [comment]
@vigneshhari do we have the api?

@gigincg could add a button that call the api and refreshes page?

**Comment by vigneshhari** [comment]
API was done long back

**Comment by athulmanuel** [comment]
@tomahawk-pilot @bodhish 
Status.
