### ISSUE TITLE
a pop up for Plasma pool before discharge

### ISSUE THREAD

**Issue by athulmanuel** [ohcnetwork/care_fe#560]
when a patient is being discharged, while they click the DISCHARGE button, a pop up should come with 3 options.

-- Willing to donate blood --
Ans : Yes
         No
         Not fit for donation

**Comment by athulmanuel** [comment]
@vigneshhari   status please ....

**Comment by vigneshhari** [comment]
@tomahawk-pilot @bodhish added two new boolean fields , "will_donate_blood" and "fit_for_blood_donation"

**Comment by dauntlessnomad** [comment]
i will do this today probably

**Comment by MrRobz** [comment]
@athulmanuel would a popup like this work? This comes while clicking on the discharge button.
@tomahawk-pilot 
![discharge](https://user-images.githubusercontent.com/21201812/93808439-97fe1c00-fc69-11ea-87f7-e78c4f4cac99.png)

Also @vigneshhari if the option "Not fit for donation" is selected should I send: 
"will_donate_blood":true,
"fit_for_blood_donation":false

or 
"will_donate_blood":false,
"fit_for_blood_donation":false

**Comment by athulmanuel** [comment]
👍

**Comment by MrRobz** [comment]
@athulmanuel, @tomahawk-pilot  now that you have filled this popup, How or from where would you want to get the list of patients who have given yes from blood donation. By downloading the CSV list of patients is it? Or new filter needed for this?

**Comment by vigneshhari** [comment]
You can make that two questions , willing to donate and fit to donate, that way we have data to call someone later on as well.

**Comment by athulmanuel** [comment]
@MalayaliRobz you could add to the main download file. 

Need not see in care.

**Comment by MrRobz** [comment]
> You can make that two questions, willing to donate and fit to donate, that way we have data to call someone later on as well.

Now that I think of it. Two questions seem redundant. If the patient was not willing to donate blood, "No" option would have be chosen. Only way I can see "not fit for donation currently" being chosen is when the patient is willing but is in not so good condition at the moment.

> you could add to the main download file.

@vigneshhari this comes automatically right?

**Comment by vigneshhari** [comment]
Yeap the download part i can handle.
