### ISSUE TITLE
lay out of patient list

### ISSUE THREAD

**Issue by athulmanuel** [ohcnetwork/care_fe#561]
while we take the patient list, kindly arrange it according to the time and date of admission.

preferably latest patient must be on top.

date and time tab just before the name

**Comment by bodhish** [comment]
@vigneshhari can we sort it at be?

**Comment by vigneshhari** [comment]
we already sort it by time, the latest will be at the top ( based on created time )

**Comment by athulmanuel** [comment]
Display of date and time ?
