### ISSUE TITLE
Facility name in a row. - NOT urgent 

### ISSUE THREAD

**Issue by athulmanuel** [ohcnetwork/care_fe#562]
it would be good if we could see the facility name while we click the patient list.
when we login from admin ID,  we are not able to view which facility we are currently viewing. 
also if there was a patient number display in each facility tile as well as in the facility home page it would be better

**Comment by dauntlessnomad** [comment]
every tile has the facility name along with the patient name
also in admin view. if you are coming to. the above view from a facility homepage then it will only have that facilities patients/

**Comment by athulmanuel** [comment]
@tomahawk-pilot    Got it
