### ISSUE TITLE
Can admin closed down any facility 

### ISSUE THREAD

**Issue by athulmanuel** [ohcnetwork/care_fe#563]
we are closing some of the CFLTC's that are being temporarily setup. Hence it would be good if we could delete a facility which is not functioning 
since its being inactive, it is a disturbance in our Dashboard

**Comment by vigneshhari** [comment]
we can make this superuser accessible only, otherwise we might see a lot of unwanted deletions.

**Comment by athulmanuel** [comment]
Steady decativate some facilities. 


I am creating a login flow, it would be good if we have different kind of admins.

**Comment by vigneshhari** [comment]
@bodhish district admin and state admin should suffice for this right?

**Comment by bodhish** [comment]
yes @vigneshhari

**Comment by athulmanuel** [comment]
@vigneshhari @bodhish -- status please

**Comment by bodhish** [comment]
@vigneshhari we should think abou this

**Comment by vigneshhari** [comment]
@bodhish Allowed soft delete for District Admin and above provided they have access

**Comment by bodhish** [comment]
Create a delete button for facilities. Show it only for District admins.

**Comment by shaileshaanand** [comment]
@vigneshhari @bodhish careapi returns 403 (Forbidden) even for District Admins, I have checked the backend code, it should allow deletion for DistrictAdmins please check.

Update: Superuser can delete facilities.

**Comment by shaileshaanand** [comment]
@aparnacoronasafe @amruthavijay88  Should I add any message (Eg. "You will not be able to access this facility.") to this confirmation popup?
![Screenshot from 2021-05-24 13-56-54](https://user-images.githubusercontent.com/26682202/119319328-ee5ba880-bc97-11eb-8cb2-dd1caede4ec9.png)

**Comment by bodhish** [comment]
Do add the message

**Comment by amruthavijay88** [comment]
Tested.
District admin is unable to delete a facility, says - ' you do not have permission to perform this action'.
