### ISSUE TITLE
Edit/ create Discharge summary even after discharge

### ISSUE THREAD

**Issue by athulmanuel** [ohcnetwork/care_fe#564]
at present while there are a lot of discharge at a time, the doctor is not able to give discharge summary for all patients at the time of discharge. Since they are not able to create discharge summary after discharging a patient, the patient card is in the facility even after the patient is being discharged, till the discharge summary is ready. this causes a lot of data discrepancy regarding the number of patients in a  facility.

If there is an option to enter discharge summary even after discharging the patient it would be far better. then they can discharge all the patients as they become negative and later give discharge summary.

**Comment by athulmanuel** [comment]
this is needed ASAP, as the discharge form facilities is being delayed and this is causing discrepancy in the patient 'live' data

**Comment by shivankacker** [comment]
Appears this issue has been solved
