### ISSUE TITLE
need to add Testing ID

### ISSUE THREAD

**Issue by athulmanuel** [ohcnetwork/care_fe#573]
need to add a field : 'Testing ID'

it must be mandatory for Discharge, i.e, if it not entered, the patient can not be discharged. 

this ID is for testing swab state wide details.

**Comment by vigneshhari** [comment]
added a field "test_id" in the consultation form, make the mandatory check-in FE itself.

**Comment by dauntlessnomad** [comment]
will be deployed tommorow night. 
done in staging

**Comment by athulmanuel** [comment]
@vigneshhari----  what is  FE?

**Comment by athulmanuel** [comment]
i checked it in testing. 
 
Testing ID has come in Op triage. 

Testing ID will not be available in the initial steps, so if we make it mandatory then the consultation can not be done. it will create a big issue. 

HOLD deployment.

**Comment by vigneshhari** [comment]
Will deploy and make it nonmandatory, FE stands for Front End ( Design and Input Related Stuff ) and BE stands for Back End ( Data Storing and things that users dont see )

**Comment by athulmanuel** [comment]
@vigneshhari 👍

**Comment by athulmanuel** [comment]
@vigneshhari -- has it been deployed?
