### ISSUE TITLE
SHIFTING details download

### ISSUE THREAD

**Issue by athulmanuel** [ohcnetwork/care_fe#575]
same as patient details from facility, we need to download the list from shifting team. 
need this ASAP.
all the shifts have been done through our Shift system, so was not able to send the data of shifts today. 

as of now all the fields in our cards.

**Comment by aparnacoronasafe** [comment]
@tomahawk-pilot please move this at the earliest

**Comment by dauntlessnomad** [comment]
@vigneshhari please send an email from be :wink

**Comment by vigneshhari** [comment]
What all data would you need in the CSV @athulmanuel

**Comment by athulmanuel** [comment]
Date| Time| Name| From | To | Upshift( yes/no) | Emergency Shift ( yes/no)| Vehicle Preference | Reason for shifting

**Comment by athulmanuel** [comment]
@vigneshhari 
@tomahawk-pilot 

      STATUS please

**Comment by vigneshhari** [comment]
Backend Changes are done, @gigincg  can you take a look at this?

**Comment by athulmanuel** [comment]
@gigincg @bodhish 

Status.

**Comment by gigincg** [comment]
We've added a board level download button. It's being tested in staging. Will reflect in next release.

**Comment by athulmanuel** [comment]
👍

Please make it fast. Ever since we have totally shifted to CARE for shifting , haven't been able to give data to the state
