### ISSUE TITLE
Facility Dashboard Enhancement

### ISSUE THREAD

**Issue by aparnacoronasafe** [ohcnetwork/care_fe#576]
https://care.coronasafe.in/facility/874bff56-2d55-4f13-8ef1-bba9a0745a21

Where triage summary appears, can we have a link against confirmed positives that takes the user straight to line list of positives?

Also, spelling error in "Confirmed Positives" in triage summary. Please correct the same.

Doctor list may be hidden or moved to the bottom since it is not relevant.

**Comment by bodhish** [comment]
Thats the view patient page right 🤔

That link in on the top of that page 🙄
