### ISSUE TITLE
Changes in "Add Triage" form

### ISSUE THREAD

**Issue by aparnacoronasafe** [ohcnetwork/care_fe#577]
Split the form into two sections:

OP Triage: 
        Total patients visited, 
	Patients in home quarantine
	Referral of suspect (OP Only)
	Referral of positive (OP Only)

IP Details:
                Total Positive (add a shortcut to the positive line list)
		Suspects isolated	
		Admitted (last 24 hrs)
		Discharged (last 24 hrs)
		Referred from IP (last 24 hrs)

suitable changes may be made in the facility dashboard triage summery as well. This may be summarised as two tables

**Comment by bodhish** [comment]
This is more like a new feature request right?

Could you create an issue for the missing field at care be

**Comment by bodhish** [comment]
closing in favor of the new issue
