### ISSUE TITLE
Advanced filter to sort patients

### ISSUE THREAD

**Issue by aparnacoronasafe** [ohcnetwork/care_fe#578]
The following filters may be added to sort patients based on the following factors. This is relevant to create reports.

1) Male/Female
2) Less than 10 yrs of age/ more than 60 years of age
3) Category (Asymptomatic, A, B, C)

**Comment by athulmanuel** [comment]
all this could be taken from download list

**Comment by vigneshhari** [comment]
@tomahawk-pilot All filters added in Backend

**Comment by bodhish** [comment]
Age has some issues. Moving it to a new issue  #803
