### ISSUE TITLE
Migrant Worker - YES/NO

### ISSUE THREAD

**Issue by athulmanuel** [ohcnetwork/care_fe#579]
Day by day, migrant workers are become positive in clusters. we are not able to differentiate them. 

The system for them is different, hence it is very important to differentiate them

same as we ask Health Worker - Yes/No.

we also need to to know whether they are - Migrant Worker --Yes/NO

**Comment by bodhish** [comment]
@athulmanuel the same information could be figured by checking the address of the patient.

Anyone with a other in state would possibly be a migrant worker

**Comment by athulmanuel** [comment]
Nope. Migrants workers don't include IT or upper middle class jobs. 

There is a special Project called Adithi Debo Bhava for them. 

We need to have a separate track and patient flow for these members. 

eg. if they have to be shifted to an FLTC, a separate FLTC will be needed. 

Already there are lot of them coming in clusters and have be declared as Special Domiciliary care centres.

**Comment by vigneshhari** [comment]
@tomahawk-pilot @bodhish,  "is_migrant_worker" added as a field in the patient API, defaults to False

**Comment by athulmanuel** [comment]
change the name to ' Guest workers' from Migrant workers.. the project's name is Aditi Devo bhava..  they are our guests. :)
