### ISSUE TITLE
Search by Phone No- : SHIFTING

### ISSUE THREAD

**Issue by aparnacoronasafe** [ohcnetwork/care_fe#581]
Please add a search by phone number feature in shifting tab

Add search by date too. This will enable the shifting team to also make reports of how many shifts took place in a day

**Comment by vigneshhari** [comment]
@tomahawk-pilot , patient_phone_number filter added in shifting , 
created_date and modified_date filters added , use it as follows
f = F({'X_after': '2016-01-01', 'X_before': '2016-02-01'}) where x is created_date or modified_date

**Comment by gigincg** [comment]
Added the requested filters. Tested to be working
