### ISSUE TITLE
ward / division for all Facilities in CARE

### ISSUE THREAD

**Issue by athulmanuel** [ohcnetwork/care_fe#589]
'ward/division of respective LSGI'  for each Facility in our CARE system .

this must be mandatory as same as for the patient data. 

most of the facilities have already been created, when they log in next time,  if a pop up comes to enter their respective ward/division it would be better.

this is needed for the upcoming LSGI Covid management team

**Comment by bodhish** [comment]
@vigneshhari could you check this

**Comment by vigneshhari** [comment]
Since the ward data is already in the api , can you just add a check in fe to show a warning for patient without one ? I cant do anything in be.

**Comment by bodhish** [comment]
@vigneshhari ward is missing in `/api/v1/facility/id` API

I don't think we are storing ward for facilities

**Comment by vigneshhari** [comment]
Do we have ward data? As a json somewhere?

**Comment by aparnacoronasafe** [comment]
Tested. Instead of ward name, can we have ward numbers?

Names are confusing. Also name, refers to locality whose boundaries are not as defined as wards. People may get confused.
