### ISSUE TITLE
Covid Management Center - New login type.

### ISSUE THREAD

**Issue by athulmanuel** [ohcnetwork/care_fe#590]
as part of decentralizing the present system of Breaking Bad News and transportation system, Covid Management Center.
This center will be functioning 24/7. we have initiated the transporting part in 55 LSGI (Local Self Governing Institution).

 for the proper functioning of this login, all the Facilities and patients should have entered their respective WARD/DIVISION

This login will be above the facility status.

![Covid management Center](https://user-images.githubusercontent.com/64475161/92300901-648a7480-ef7c-11ea-91e2-e3ae8c7503e1.jpg)

the above would be the flow where in - selected ward/division  in each LSGI will be assigned to certain Covid Management Center according the the area coming under the respective Field Health institution. ie, all the wards in Kerala are linked with a mother filed health institution, we are using this concept to decentralize the field covid management activities. 

 Covid Management Center (CMC) login needs 2 type of admins with - View only and another with full edit option. it also needs a transportation login- to manage the transportation from facilities under the CMC, this might be either from their own CFLTC or from home care or form other intuitions that comes  under CMC( for this they need not arrange trans-portion but view what is happening )

**Comment by athulmanuel** [comment]
on more add on. they also need to have a view only access to patient of their respective wards in hospitals which comes under other covid management centers

**Comment by athulmanuel** [comment]
@tomahawk-pilot @bodhish ----- stays please.

**Comment by athulmanuel** [comment]
status please

**Comment by vigneshhari** [comment]
View only access user created , @bodhish any other requirements ?

**Comment by bodhish** [comment]
@vigneshhari need an option to add multiple facilities to a user.

**Comment by vigneshhari** [comment]
@bodhish API already made , one api for adding users to a facility and one to remove from facility , only people with access to the facility can do this.

**Comment by athulmanuel** [comment]
@bodhish @vigneshhari --- status please.

**Comment by bodhish** [comment]
A new facility type is created and also a few other user types to manage the same.

**Comment by aparnacoronasafe** [comment]
new user type for CMC or panchayat level monitoring has not come. isn't that what's asked for in the issue?

**Comment by bodhish** [comment]
We have decided to move it to the facility type. 
We will not be adding a new user type CMC. (local body admin could be used for panchayat level monitoring)
