### ISSUE TITLE
need to show the shifting history of each CARD - NOT URGENT

### ISSUE THREAD

**Issue by athulmanuel** [ohcnetwork/care_fe#591]
it would be good if we could know where all the card has been refereed from .

Eg: when we open an option fro shifting summary. 

with this we could know were all the patient has been admitted at.

**Comment by bodhish** [comment]
This could be identified with consultations in patients. The list is missing a facility name, which could solve this issue

**Comment by vigneshhari** [comment]
we already have api for this, we can search for shifting records with just the patient filter and we can see all the shifts.

**Comment by bodhish** [comment]
Fixed
