### ISSUE TITLE
Need to download Triage Details - 

### ISSUE THREAD

**Issue by athulmanuel** [ohcnetwork/care_fe#592]
at the moment, 7 people are entering an excel sheet  by looking  the dash board, it would be good if they could download the triage details.  its not urgent but it would help them to ease the tedious process.

**Comment by bodhish** [comment]
Export for triage is avilable at dashboard.

Right @saanuregh?

**Comment by saanuregh** [comment]
It's available. But data for the current day will not be available until midnight, so data only till previous day is available.

**Comment by athulmanuel** [comment]
I think that must suffice the need because we have taken a decision freeze the data by midnight.

**Comment by athulmanuel** [comment]
they are getting it .. thank you
