### ISSUE TITLE
Adding OP/Triage consultation must be mandatory for entering a CARD

### ISSUE THREAD

**Issue by athulmanuel** [ohcnetwork/care_fe#595]
as of now, OP/Triage consultation is not mandatory for creating a card and most of them are not creating it. 
since it is mandatory for shifting, while the patient needs to be shifted they are entering it. but if the patient is admitted in the same facility, they are not entering it.

 we need to make it mandatory for creating   ASAP. it is creating a lot of issue. 

we had created this with the concept of creating a card while the patient walks into a facility and to enter op/triage consultation after seen by a doctor. 

NOW care is only being used for positive patients, hence it could be made into a single glow.

**Comment by bodhish** [comment]
We are currently redirecting the users to the consultation creation form right after the patient is created. 
It's a single flow now. The consultation not getting created as the users are not filling the second form. 

I don't think we could make it a single form as its a bit complex

**Comment by athulmanuel** [comment]
Yes, its the user problem

 it shouldn't not be a single form, but only if they fill the op/ triage consult the card can be created.
