### ISSUE TITLE
ADMIN log in with view only access

### ISSUE THREAD

**Issue by athulmanuel** [ohcnetwork/care_fe#596]
many are requesting admin level log in . 
at present the login is able to edit the card. 

while we give this id to many, it would be best if they have an id to view all the details and download but not able to edit any of the fields.

**Comment by bodhish** [comment]
@vigneshhari we will need a user type that will just have read-only privileges

**Comment by vigneshhari** [comment]
Adding to feature requests.

**Comment by vigneshhari** [comment]
Completed API, waiting for review and deployment

**Comment by dauntlessnomad** [comment]
@vigneshhari what are the fe changes required for this

**Comment by athulmanuel** [comment]
status?

**Comment by athulmanuel** [comment]
@bodhish   status
