### ISSUE TITLE
Similar to #540.. we need to add few more options

### ISSUE THREAD

**Issue by athulmanuel** [ohcnetwork/care_fe#597]
we need a bit more details on the type on bed admitted in 
at present there is ICU/ICU with ventilator
need to change that to---- ICU | ICU with oxygen support | ICU with invasive ventilator | ICU with NON invasive ventilator all the rest options 

this is needed for state- please do it ASAP

![Admission category option](https://user-images.githubusercontent.com/64475161/92471969-6e1f1100-f1f6-11ea-94cb-c1f7387d74bd.jpg)

#540

**Comment by vigneshhari** [comment]
We can't really delete an option because that would affect the existing patients and their histories, what should we move the existing patients under ICU with ventilator to?

**Comment by athulmanuel** [comment]
@vigneshhari ok

then no need to delete ICU with ventilator,  change 'ICU with Ventilator to 'ICU with Non Invasive Ventilator' 

anyways till now, no one has been in invasive ventilator in private hospitals and Govt, Medical College (GMC), Kalamasherry still haven't started to use CARE. only GMC had patients on invasive ventilator.

@vigneshhari could we do that?

**Comment by athulmanuel** [comment]
@vigneshhari status please.

**Comment by dauntlessnomad** [comment]
@vigneshhari api

**Comment by vigneshhari** [comment]
(3, "ICU with Non Invasive Ventilator"),
    (4, "ICU with Oxygen Support"),
    (5, "ICU with Invasive Ventilator")
@tomahawk-pilot pushed the API with these choice values

**Comment by athulmanuel** [comment]
@vigneshhari --- status please..

**Comment by vigneshhari** [comment]
I have pushed everything, waiting for @tomahawk-pilot

**Comment by athulmanuel** [comment]
@tomahawk-pilot ---  status.
