### ISSUE TITLE
Add few more details for POSITIVE  in first page

### ISSUE THREAD

**Issue by athulmanuel** [ohcnetwork/care_fe#600]
need 3 more details for patients with 'Disease Status' as POSITIVE - 
Date of test ( mandatory )
Type of Test : options 1. Antigen  2. RTPCR  3.CBNAT  4. TRUNAT ( not mandatory)
SRF ID  ( NOT mandatory ( might have to change later)
 
![Positive drop down](https://user-images.githubusercontent.com/64475161/92486945-489c0280-f20a-11ea-858a-e6288afc3ddf.jpg)

**Comment by athulmanuel** [comment]
change'DATE OF TEST' ------ to ' DATE OF SAMPLE GIVEN'

**Comment by athulmanuel** [comment]
@bodhish @tomahawk-pilot ... update

**Comment by athulmanuel** [comment]
@bodhish @tomahawk-pilot @vigneshhari 

Update please.

**Comment by dauntlessnomad** [comment]
@vigneshhari api aayo

**Comment by vigneshhari** [comment]
@tomahawk-pilot  fields are date_of_test , srf_id , test_type , everything is in the patient API 
Everything is optional now , will make it required after UI implementation
