### ISSUE TITLE
should not be able to shift with preview facility's op/traige consultation tab

### ISSUE THREAD

**Issue by athulmanuel** [ohcnetwork/care_fe#601]
at present, there is no way to make sure they enter op/triage consultation once the card is pulled into a new facility they present facility could shift the patient using the old facility's consult details.  Could we disable the shift button in the old op/triage consults.

**Comment by vigneshhari** [comment]
i will discharge the patient on moving the patient to the new facility, so that consultation is no longer editable. Is this okay?

**Comment by athulmanuel** [comment]
Yup. That would be great.

**Comment by vigneshhari** [comment]
This is done in staging, waiting for production deployment

**Comment by athulmanuel** [comment]
Great
