### ISSUE TITLE
EMERGENCY>>>>>>> Please disable refer to another facility in OP/TRIAGE Consultation.

### ISSUE THREAD

**Issue by athulmanuel** [ohcnetwork/care_fe#602]
we need to disable the refer to facility option in OP / TRIAGE consultation

once they chose refer to another hospital, and enter the hospital and save the card, the patient card gets shifted to that particular facility... IT IS DANGEROUS.

@bodhish @tomahawk-pilot @vigneshhari

**Comment by vigneshhari** [comment]
Referring will no longer work, The consultation will be saved, but the patient won't be transferred.
