### ISSUE TITLE
shifting detail between the Consultation details 

### ISSUE THREAD

**Issue by athulmanuel** [ohcnetwork/care_fe#603]
![Consultation cards](https://user-images.githubusercontent.com/64475161/92578275-4341c500-f2a9-11ea-8d80-2e439417e6eb.jpg)

if we could have shifting cards in between the the consultations in each facility,we could have a proper history of the patients.

**Comment by vigneshhari** [comment]
this would be hard to build in the UI. Adding to Feature Requests.

**Comment by athulmanuel** [comment]
ok.

will take it slow, not an emergency

**Comment by bodhish** [comment]
Added in patients Tab
