### ISSUE TITLE
Contact of Referring Facility

### ISSUE THREAD

**Issue by athulmanuel** [ohcnetwork/care_fe#604]
at present if there is any confusion or even for transporting team there was no specific contact number. if they use the number given for the facility it will be time consuming to connect to the correct person.. This must be a MANDATORY field.

  
![contact of refering facility](https://user-images.githubusercontent.com/64475161/92581727-aa617880-f2ad-11ea-82ff-89cabc0949bb.jpg)

**Comment by vigneshhari** [comment]
There is already a contact for every facility, entered in the facility page, we can just display it here, is that okay?

**Comment by athulmanuel** [comment]
it would be good if it is displayed. but that alone is not enough as it might be a main number and we wont be able to get to the person handling the patient. 

as you suggested, it would be good if we have the facility number displayed. but we also need this specific number. as asked.

**Comment by vigneshhari** [comment]
refering_facility_contact_name , refering_facility_contact_number , fields added in the shifting module
The facilities phone number and the patients emergency phone number are already in the api
