### ISSUE TITLE
the first step to  Covid Management System - part of #590

### ISSUE THREAD

**Issue by athulmanuel** [ohcnetwork/care_fe#605]
It is a part of the #590 issue. i came to know that the main problem with the issue is the view only option. 

as the first leg of the issue, we need to create a Covid19 Management Center login type with initial step as per the following image. 
![Covid management Center first step 1](https://user-images.githubusercontent.com/64475161/92619415-17413680-f2df-11ea-85fb-067014ea9761.jpg)

it must be a login between to admin and the facilities. 

so the Covid19 Management Center in each LSGI can have full access to the field facility ( corresponding PHC/CHC/Thauk/ General Hospital) in their area along with the FLTCs and also a tele medicine system for patients under Domiciliary care ( this could also be under the field facility.

**Comment by athulmanuel** [comment]
@bodhish

**Comment by athulmanuel** [comment]
@bodhish   status.

**Comment by bodhish** [comment]
Not yet started. Pending on user preview feature

**Comment by bodhish** [comment]
Covid Management System is now live
