### ISSUE TITLE
sifting status in CARD - NOT urgent 

### ISSUE THREAD

**Issue by athulmanuel** [ohcnetwork/care_fe#608]
it would be good if we have a shifting status in the CARD

![shifting status in CARD](https://user-images.githubusercontent.com/64475161/92744248-f04a3980-f39e-11ea-9c55-de2b12791f06.jpg)

**Comment by vigneshhari** [comment]
Adding to Feature Requests, @tomahawk-pilot be already supports requests like these

**Comment by dauntlessnomad** [comment]
@vigneshhari is this data in the patient api

**Comment by bodhish** [comment]
Fixed
