### ISSUE TITLE
Create a sigin up for corona care centers

### ISSUE THREAD

**Issue by bodhish** [ohcnetwork/care_fe#61]
route `/join`

This should be a copy of our facility onboard form with few changes. 
- [ ] Type - [educational institution, hotel, hostel, lodge] 

The join page should have details on `Guidelines for bed spacing`, etc.

**Comment by anandsimmy** [comment]
I can work on  this.. @bodhish  can you specify the tasks

**Comment by bodhish** [comment]
Sure, let's discuss this at our slack channel coronasafe_react

**Comment by anandsimmy** [comment]
@bodhish @tomahawk-pilot what about the guidelines to be added?

**Comment by dauntlessnomad** [comment]
Completed
