### ISSUE TITLE
Age Calculation is worng

### ISSUE THREAD

**Issue by athulmanuel** [ohcnetwork/care_fe#612]
the age that is displayed near the name is WRONG with respect to the date of birth entered. 

it is causing major confusions. please look into it ASAP

**Comment by vigneshhari** [comment]
could you please provide examples of this case, including screenshots of the issue.

**Comment by athulmanuel** [comment]
![WhatsApp Image 2020-09-12 at 11 44 28 PM](https://user-images.githubusercontent.com/64475161/93002626-f898a500-f555-11ea-8493-78741a2b7803.jpeg)
![WhatsApp Image 2020-09-12 at 11 44 29 PM](https://user-images.githubusercontent.com/64475161/93002631-fafaff00-f555-11ea-8543-ddf985cebd8a.jpeg)

**Comment by athulmanuel** [comment]
@vigneshhari @bodhish   this issue is create huge problems regarding taking decisions on transfer b

We need to resolve it ASAP

**Comment by bodhish** [comment]
I did check this account. Their exist 2 records where one is created by the positive team and another by fltc.

The age show along with the name is always corresponding to the date of birth in the record. Their should not be any miss match

**Comment by vigneshhari** [comment]
This issue happened because the DOB was edited for the patient, which was not supposed to happen, Now this is allowed, all patient age should be synced now.

**Comment by athulmanuel** [comment]
oh ok,, but at times it might need to be changed as some of the old age people wont know their DOB. 

hence might need to be changed

**Comment by vigneshhari** [comment]
Since this issue is solved, i am closing it. Age will be automatically updated now.
