### ISSUE TITLE
Filter not staying in Shifting - Enhancement

### ISSUE THREAD

**Issue by athulmanuel** [ohcnetwork/care_fe#613]
If we enter a filter and search in Shifting. And we select a particular card, on clicking on back, the filter disappears and again have to apply the filter. 

It's a tedious thing while searching

**Comment by bodhish** [comment]
@gigincg could you make the filter stay in the URL so that it stays.

**Comment by gigincg** [comment]
As a temporary fix, Shifting records are opened in a new tab. So the filters will remain.

Added isue to wish list to optimize behavior at a later stage

**Comment by athulmanuel** [comment]
Not just shifting. All the filters. 
So could you do this when all the places that has filters
