### ISSUE TITLE
SHIFTING SYSTEM - VERY URGENT - login views and edits

### ISSUE THREAD

**Issue by athulmanuel** [ohcnetwork/care_fe#616]
![Shifting System](https://user-images.githubusercontent.com/64475161/93175330-154afd80-f74d-11ea-92a3-c01b5551924c.jpg)

this must be the login status..

**Comment by athulmanuel** [comment]
this is the type of login  view system that is needed. now even all the failities can edit the process. and its confusing and not correct.

**Comment by vigneshhari** [comment]
This was initially designed and implemented this way, to avoid confusions we removed all restrictions, @bodhish should we add it back ?

**Comment by bodhish** [comment]
Yes. We removed it as we had a bad experience with sample management system. As shiting is stable now. We could add it back.

**Comment by athulmanuel** [comment]
yes, it was sad that they didn't use our sample testing system. most of the FLTC used it for some time. 

this is the key system in managing the patient load.

**Comment by athulmanuel** [comment]
please give this priority. 

it is becoming a key part in capacity management.

**Comment by aparnacoronasafe** [comment]
Test report: 
- It is possible to reject a shift request without giving any reason
- destination hospital can also see patient shifting request in pending
- origin facility can still see the card, even once its shifted approved.
-A card once approved can be rejected by the shifting team without stating any reason
-Only the destination facility can approve the destination. I don't think that is desirable.
