### ISSUE TITLE
a notification system for shifting system 

### ISSUE THREAD

**Issue by athulmanuel** [ohcnetwork/care_fe#617]
since shifting is a very live process, a notification bell should be available . and later if possible a SMS notification system.

**Comment by vigneshhari** [comment]
With the sheer number of shifts happening per day, it will get to >7000 SMS/day and that would cost quite a bit, + live notifications would take much longer to design and build, we can add this to feature requests

**Comment by bodhish** [comment]
@vigneshhari how about FCM for browser notifications?
