### ISSUE TITLE
Hospital Admin View

### ISSUE THREAD

**Issue by dauntlessnomad** [ohcnetwork/care_fe#62]
- [x]  Dashboard to see there own added hospitals

- [x]  ability to add new hospitals

- [x]  add and edit bed capacity

- [x]  add and  edit doctor capacity

Hospital Admin should only have access to the Hospitals he/she create. 
Some of the sub forms are already created but need to integrated based on the per user scheme. 
Apis are avaliable at https://dev.coronasafe.in/swagger

**Comment by jithinlal** [comment]
api page not found

**Comment by pranavek** [comment]
@jithinlal I believe this is the URL - https://dev.care.coronasafe.in/swagger/

**Comment by jithinlal** [comment]
i can take the add bed capacity and edit, but how can i start? can anyone help ?

**Comment by dauntlessnomad** [comment]
Completed
