### ISSUE TITLE
Change of Discharge TEXT

### ISSUE THREAD

**Issue by athulmanuel** [ohcnetwork/care_fe#621]
when ever we shift patient from facility to facility, they being discharged from each facility and admitted in the next. this will automatically happen. 
but when we click 'Discharge' - this mean from the entire active system. this must be renamed 

Suggestion - 'Discharge from CARE system'

We have to create a proper flow system for Discharge, especially after death, will create an issue separately

**Comment by bodhish** [comment]
Rename `Discharge` button to `Discharge from CARE system`
