### ISSUE TITLE
'Discharge from CARE' only if negative

### ISSUE THREAD

**Issue by athulmanuel** [ohcnetwork/care_fe#622]
once the name of 'Discharge' is changed to 'Discharge from CARE' 

once they click a pop up should come 2 option -as whether negative or not.
                                                                              shifting to other district.

**Comment by dauntlessnomad** [comment]
@vigneshhari need an api for this

**Comment by bodhish** [comment]
This should be clubbed with the PLASMA POOL request. #560

API is not required as the UI could call the patient Update API

**Comment by MrRobz** [comment]
@bodhish @athulmanuel 
are these the action items for this issue?
1. update text of discharge button to 'Discharge from CARE'
2. while user clicks on discharge button show popup with the option to update disease status.

shifting to other district? not clear what to do here?

**Comment by bodhish** [comment]
Let's skip the shifting to other district for now.
It would be great if the plasma pool popup could capture the status along with last tested date, srf_id. (all of it should be optional)
