### ISSUE TITLE
Disease status to be shifted from initial demographic data

### ISSUE THREAD

**Issue by athulmanuel** [ohcnetwork/care_fe#623]
Disease status entry must be changed from initial demographic data to OPTriage/Consultation and also to Daily rounds.

it must have the fields of #600  issue.

we had created a wonderful sample testing system, but now government order has come that, only HealthMon system should be used for sample testing system.  

but we need this result updating system to keep CARE streamlined. especially to know the date of retest. now all the facilities are keeping a separate sheet, its a tedious process.

**Comment by dauntlessnomad** [comment]
@athulmanuel healthmon site looks awesome 😉

**Comment by athulmanuel** [comment]
@tomahawk-pilot i know. It has already started to crash. Those fools won't understand.

**Comment by dauntlessnomad** [comment]
@vigneshhari need the api for this change

**Comment by vigneshhari** [comment]
I didnt understand, what change is required ?

**Comment by bodhish** [comment]
@vigneshhari 

We need a new model to capture the test status for a patient.
Everytime a test status is created it should update the patient.

This could help in capturing when a patient was tested positive when he was tested negative also helps in keeping the patient data uptodate with the correct status.

**Comment by vigneshhari** [comment]
We can use our existing sample management system for this right? we can set the current sample management system to directly update the test status on creation , wouldn't this do the job ?
