### ISSUE TITLE
Op Triage/ Consultation - change editing option 

### ISSUE THREAD

**Issue by athulmanuel** [ohcnetwork/care_fe#625]
at present the OP Triage / Consultation can be edited anytime and also create multiple consultations. 

This is can cause major confusion regarding the actual design.

our design would be that, the consultation has to be only created once in one admission, and also it should not be edited ( editing option could be allowed for first 15 mins), further updation should be encouraged through 'daily rounds'. might need to change the name. . 
daily rounds form needs to be changed accordingly.

**Comment by bodhish** [comment]
A better UI could possibly fix this issue.
