### ISSUE TITLE
Shifting form - change needed

### ISSUE THREAD

**Issue by athulmanuel** [ohcnetwork/care_fe#629]
Name of Shifting Approval Facility - (**Manadatory**) - Auto select to 'Shifting Control Room - EKM'

Type of Institution to be shifted  - Domiciliary Care         (as drop down) 
            ( **Mandatory**)                     First Line
                                                      Second Line
                                                      Apex Center
                                                      Non Covid Hospital  
                                                      Other Districts/ State

What Facility would you like to Shift to:  [same as now]
           (**Not Mandatory**)

Contact Person -- Name :............................   Phone Number : ...........................
(**Mandatory**)

Vehicle Preference          :      D Level Ambulance       (as drop Down)
All double chambered           Ambulance with EMT
 (**Mandatory**)                  Ambulance with out EMT
                                              Car
                                              Auto-rickshaw 

Rest the same...... Emergency / up-shift/ Reason and                    Comments (**Not Mandatory**)
(**Mandatory**)

**Comment by vigneshhari** [comment]
@athulmanuel is this requirement still required ?

**Comment by athulmanuel** [comment]
@vigneshhari yes. 

Also need to make 'Reason for sifting' as mandatory.

**Comment by bodhish** [comment]
Type of Institution to be shifted - 
Domiciliary Care
First Line
Second Line
Apex Center
Non Covid Hospital
Other Districts/ State

Vehicle Preference : 
D Level Ambulance (as drop Down)
All double chambered Ambulance with EMT
(Mandatory) Ambulance with out EMT
Car
Auto-rickshaw

**Comment by vigneshhari** [comment]
so for the type of institution can we re-use the same facility type enum we use in facility creation?

**Comment by bodhish** [comment]
@athulmanuel can we use the same facility type?

**Comment by athulmanuel** [comment]
@bodhish didn't get you.

**Comment by athulmanuel** [comment]
@bodhish got it. Ya. It must be ok. Though all types are not needed. It's basically to search which type of facility. It is not directly inline with our category.

**Comment by bodhish** [comment]
@vigneshhari let's reuse.

**Comment by vigneshhari** [comment]
API added

**Comment by bodhish** [comment]
```
VEHICLE_CHOICES = [
    (10, "D Level Ambulance"),
    (20, "All double chambered Ambulance with EMT"),
    (30, "Ambulance without EMT"),
    (40, "Car"),
    (50, "Auto-rickshaw"),
]

```

ReUse facility type enum

**Comment by aparnacoronasafe** [comment]
Shifting Approval Facility - Auto select to 'Shifting Control Room - EKM'- not done

**Comment by aparnacoronasafe** [comment]
Also, please have the "preferred facility type" before the destination facility field

**Comment by bodhish** [comment]
We won't be automating the section as it may not be the context in a month.

The destination field is optional, this is just an indicator. Its fine to be in different locations as it anyways mandatory.
