### ISSUE TITLE
View summery of daily rounds on consultation card on patient dashboard

### ISSUE THREAD

**Issue by aparnacoronasafe** [ohcnetwork/care_fe#631]
If daily rounds are added for a patient, we need some indication of it on consultation card on patient dashboard itself.

This is important for telemedicine

**Comment by aparnacoronasafe** [comment]
A badge saying daily rounds added today will suffice

**Comment by dauntlessnomad** [comment]
@vigneshhari do we have api for this

**Comment by vigneshhari** [comment]
Only one consultantation can be active for one patient at a time, in the patient details page , call the daily rounds api as well for the last consultantation and check the count , this should work. No need for an extra api.

**Comment by SandeepThomas** [comment]
@vigneshhari @bodhish there is no created date in the daily rounds api to show if daily rounds have been added today

**Comment by bodhish** [comment]
@SandeepThomas use the other date. Daily round could be created for other dates, that's one reason we don't have the created date in api

**Comment by SandeepThomas** [comment]
which one? @bodhish 
>  use the other date

**Comment by bodhish** [comment]
my bad. It was `temprature_measured_at` @vigneshhari could you expose that in backend api
