### ISSUE TITLE
Telemedicine ( in care) home management

### ISSUE THREAD

**Issue by aparnacoronasafe** [ohcnetwork/care_fe#632]
1) they identify cases assigned to each doctor by adding name of the doctor against patient name. And they use the filter by name feature to find list of cases assigned to them. 

But everytime they open a patient card and go back, the filter by name disappears 
Any way to identify family

**Comment by bodhish** [comment]
Filters should be preserved, it should not be cleared on refresh

**Comment by aparnacoronasafe** [comment]
Please make it the case everywhere there are filters. This is a request that has come in from all departments across the field
