### ISSUE TITLE
Kinds of beds in FLTCs

### ISSUE THREAD

**Issue by aparnacoronasafe** [ohcnetwork/care_fe#635]
There are a lot many kinds of beds in any FLTC, not just normal beds. 

Attaching a table that's used by the field team to keep track of bed count. 

If these details are not made available to them over the dashboard, they may not be able to draw the right conclusions. ![image](https://user-images.githubusercontent.com/67050716/93517643-632c5500-f949-11ea-88e5-29387b142185.jpeg)

**Comment by dauntlessnomad** [comment]
@saanuregh  please take care of this.

**Comment by bodhish** [comment]
closing in favor of #839
