### ISSUE TITLE
New user creation is possible without email ID

### ISSUE THREAD

**Issue by amruthavijay88** [ohcnetwork/care_fe#636]
**Describe the bug**
While creating a new user using Staff read only access, it lets us create new user without their email id.

**To Reproduce**
1. Go to 'care.coronasafe.in' and login
2. Click on 'Users' and choose Usertype. Enter complete details without email id.
3. Scroll down to the end and 'Save user, user will be saved.
4. Log off again and try to login using newly created username and click forgot password. 
5. Page will ask you to enter your username. Do that and click 'Send reset link'
6. Error - it says 'Password reset email sent'

**Expected behavior**
Email has to be mandatory, so an asterisk is must. Must not allow to save user without email Id.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [tried both windows 10& Mac OS]
 - Browser [chrome]

**Smartphone (please complete the following information):** - Did not test here.
 

**Additional context**

**Comment by dauntlessnomad** [comment]
thats an expected behaviour

**Comment by amruthavijay88** [comment]
Hey Syam, 
How will they be able to reset password if that's an expected behaviour? When we click forgot password, it says reset link sent to email id. As we're not giving email id, what email id is mentioned here?
