### ISSUE TITLE
New positive status is not reflected within patient thumbnail

### ISSUE THREAD

**Issue by amruthavijay88** [ohcnetwork/care_fe#639]
**Describe the bug**
When a 'suspected' patient is tested positive, in patient thumbnail, this change doesn't reflect. Even when you select 'positive' in 'filter by status', this new positive patient doesn't show up.

**To Reproduce**
1. Go to your facility, create a new patient card with status 'suspected'. Allow transfer and request sample test.
2. Click on Sample test, click 'Update sample test status and select approve. Once that's done, again select 'update sample test status' and click new status 'test completed'. Card turns red now and result shows 'positive' here.
3. Go to 'patients' on LHS, in live, look for this newly created patient. Can notice that in thumbnail it doesn't show positive.
4. On top right corner, select 'filter by status' as positive. Still you won't be able to see this new patient card, in patient line list below. 

**Expected behavior**
1. A patient tested positive, needs to show 'positive' in thumbnail.
2. In 'patients', when we 'filter by status', this newly positive patient's card needs to be displayed in line list. 

**Desktop (please complete the following information):**
 - OS: [windows 10]
 - Browser [chrome]

**Additional context**

**Comment by SandeepThomas** [comment]
@tomahawk-pilot @bodhish @vigneshhari 

disease_status: "SUSPECTED" for the above scenario. This require changes in the backend to provide updated disease_status based on the sample test.
