### ISSUE TITLE
Patient Address- shifting card

### ISSUE THREAD

**Issue by aparnacoronasafe** [ohcnetwork/care_fe#641]
Adress of the patient is relevant information for shifting, especially for patients being shifted from Home to facility.

Please make the patient address appear on the shifting card itself on the shifting tab (https://care.coronasafe.in/shifting) , for the convenience of the shifting team.

**Comment by dauntlessnomad** [comment]
@aparnacoronasafe this why we have a detail page. 
adding to much info into the card is counter productive

**Comment by bodhish** [comment]
Is it for sharing the details?
