### ISSUE TITLE
When patient is referred, when "s" is typed, can see the code.

### ISSUE THREAD

**Issue by aparnacoronasafe** [ohcnetwork/care_fe#646]
<img width="1303" alt="Screenshot 2020-09-21 at 12 16 45 PM" src="https://user-images.githubusercontent.com/67050716/93738971-cbf32600-fc04-11ea-801e-0362f8dd354e.png">

Can see the code in the dropdown.

**Comment by dauntlessnomad** [comment]
yes

**Comment by bodhish** [comment]
Test facilities created during security audit.
