### ISSUE TITLE
Consultation page- Referring patient 

### ISSUE THREAD

**Issue by aparnacoronasafe** [ohcnetwork/care_fe#647]
<img width="1303" alt="Screenshot 2020-09-21 at 12 16 45 PM" src="https://user-images.githubusercontent.com/67050716/93738971-cbf32600-fc04-11ea-801e-0362f8dd354e.png">

Can see the code in the dropdown, when "s" is typed in the refer to another facility field.

**Comment by bodhish** [comment]
Those are test facilities in staging.
