### ISSUE TITLE
Was able to create user with another district.

### ISSUE THREAD

**Issue by aparnacoronasafe** [ohcnetwork/care_fe#648]
Nihal was able to create a user with another district.

<img width="481" alt="Screenshot 2020-09-21 at 1 17 45 PM" src="https://user-images.githubusercontent.com/67050716/93743156-22646280-fc0d-11ea-8bc5-1876daedd855.png">

I tried recreating this, and I couldn't.

**Comment by bodhish** [comment]
Could you also share the user_id
