### ISSUE TITLE
Auto population in medical history- Patient details form

### ISSUE THREAD

**Issue by aparnacoronasafe** [ohcnetwork/care_fe#649]
Patient 1 was created, tick against cancer, in medical history.

Subsequently, when patient 2 was created, the field in medical history was auto-populated. There was a tick mark against cancer. 

Please rectify since it increases chances of error in the patient record.

**Comment by sadhee99** [comment]
Tested
Medical history is still auto-populated.
For eg, heart disease or hyper tension is automatically ticked for the next patient.
