### ISSUE TITLE
Dropdown to choose local body doesn’t work

### ISSUE THREAD

**Issue by amruthavijay88** [ohcnetwork/care_fe#657]
**Describe the bug**
While creating patient card, the dropdown for selecting local body doesn't work. 

**Screenshots**
![image](https://user-images.githubusercontent.com/67979586/93842291-f7811980-fcb3-11ea-9e10-b5ca733ad119.jpeg)

**Comment by amruthavijay88** [comment]
Unable to save patient details too.

**Comment by bodhish** [comment]
@amruthavijay88 could you re-test it?

**Comment by amruthavijay88** [comment]
Yes, this is fixed now.
