### ISSUE TITLE
no alert popping up while creating basic patients detail (staff read only)

### ISSUE THREAD

**Issue by nihal467** [ohcnetwork/care_fe#659]
when we are trying to submit basic patient details to the facility using a staff read only, there no alert coming mentioning that they have no access to this feature
![error 2](https://user-images.githubusercontent.com/57055998/93843184-c7874580-fcb6-11ea-9bfb-1579f8faa0fc.JPG)

**Comment by bodhish** [comment]
Unable to replicate.
