### ISSUE TITLE
No build folder

### ISSUE THREAD

**Issue by MiNtUm** [ohcnetwork/care_fe#66]
I've successfully built the development environment , however 'npm run build' is not generating any build folder

**Comment by dauntlessnomad** [comment]
hey @MiNtUm , 
npm run build will create a production build with a dist/ folder
you can just run npm run start to work. 
webpack is preconfigured  to proxy the backend staging server. 
Hope this helps

**Comment by MiNtUm** [comment]
Got it. Thanks :)
