### ISSUE TITLE
one of dropdown list in basic patient form is not working

### ISSUE THREAD

**Issue by nihal467** [ohcnetwork/care_fe#660]
the dropdown list under the section Ward/Division of respective LSGI in basic patient form is not showing any data
![error-11](https://user-images.githubusercontent.com/57055998/93843963-51d0a900-fcb9-11ea-9bfb-304bedb91b3b.png)

**Comment by bodhish** [comment]
Should be working now. Could you test it again?

**Comment by amruthavijay88** [comment]
This was tested, works fine now.
