### ISSUE TITLE
BUG: Cannot edit patient details

### ISSUE THREAD

**Issue by aparnacoronasafe** [ohcnetwork/care_fe#662]
Unable to edit patient details. When Submitted, no error is shown, but the change doesn't get saved.

**Comment by bodhish** [comment]
Please add in more info.

**Comment by aparnacoronasafe** [comment]
https://care.coronasafe.in/facility/undefined/patient/3353da7d-642a-4a4c-b53a-50b4a1ca83c8/update

Unable to update address. No error is shown

**Comment by bodhish** [comment]
How did you generate this linik?

**Comment by bodhish** [comment]
Patient was discharged
