### ISSUE TITLE
Shifting section filter by showing error alerts

### ISSUE THREAD

**Issue by nihal467** [ohcnetwork/care_fe#663]
https://care.coronasafe.in/shifting

when we are manually typing the date into the filter by, it is showing lots of alerts message 

![error-13](https://user-images.githubusercontent.com/57055998/93845037-028c7780-fcbd-11ea-9d03-ec7709a12564.png)

**Comment by bodhish** [comment]
Should be fixed by a commit from @SandeepThomas for another issue.
