### ISSUE TITLE
Karunya Arogya Suraksha Padhathi(KASP) option not available in shifting form

### ISSUE THREAD

**Issue by nihal467** [ohcnetwork/care_fe#664]
When we are creating a new shift form, the form is not showing KASP option to select.
![error-14](https://user-images.githubusercontent.com/57055998/93847257-138cb700-fcc4-11ea-85c0-e63095254043.png)

Once, we submit the form, by default KASP option is showing no.

**Comment by bodhish** [comment]
It's the expected behavior. Kasp is off by default.
