### ISSUE TITLE
Formula in ‘Facilities’ dropdown

### ISSUE THREAD

**Issue by amruthavijay88** [ohcnetwork/care_fe#665]
**Describe the bug**
While trying to create a new user, under dropdown 'Facilities', type any alphabet and you could see formulas popping up.

**Screenshots**
![image](https://user-images.githubusercontent.com/67979586/93847628-150aaf00-fcc5-11ea-82ec-d061c24198e4.jpeg)

**Comment by bodhish** [comment]
These are facilities in the system that were created for cybersecurity audit to check xml injection.
