### ISSUE TITLE
Blood group dropdown has ‘test type - UNK’

### ISSUE THREAD

**Issue by amruthavijay88** [ohcnetwork/care_fe#666]
**Describe the bug**
While trying to create a new patient card, in blood group dropdown, test category 'UNK' shows up. 

**Screenshots**
![image](https://user-images.githubusercontent.com/67979586/93848504-5ef49480-fcc7-11ea-8a50-3cb132a372d4.jpeg)

**Comment by bodhish** [comment]
That's UNK is added to allow creation of patient card when the blood group is unknown.
