### ISSUE TITLE
Please disable shifting through Old consultations: URGENT!!

### ISSUE THREAD

**Issue by aparnacoronasafe** [ohcnetwork/care_fe#667]
Bug reported:

Sunrise hospital reported that they had to urgently shift a patient card out, but when they tried initiating shifting, the notification said a shifting card is already created for the said patient. 

when we checked a shifting card had originated from another hospital to Kalammesry medical college on the same date. Since the sunrise hospital is not a related party there, they could not see the shifting card.

We realised that the shifting card was infact generated by the data entry personnel from Sunrise hospital, unaware of the mistake. 

Issue:
When we get such a problem, there is no way for the facility to rectify the mistake or even proceed further in management of patient without intervention from someone at the admin level. 

PLEASE DISABLE CREATION OF SHIFTING THROUGH OLD CONSULTATIONS.

This creates a lot of confusion especially if the shifting team had acted on such faulty shifting request. It causes utter confusion!!

**Comment by vigneshhari** [comment]
the consultation is not considered when creating a shifting, whatever consultation's button you click the patient's origin facility will be the facility he is in currently only, this issue won't happen.
Please replicate this issue in staging and confirm
