### ISSUE TITLE
Shifting View- change needed

### ISSUE THREAD

**Issue by athulmanuel** [ohcnetwork/care_fe#675]
the present view of ----- to do - doing - done ----------- is good for the admin view but with many information on the card it gets cramped. 

 with the new type of login access to the the shifting system where only certain logins can view the status of the patient, I would suggest to make the headings to a linear tabs and while we click a certain tab, the patient list comes as a usual list, sorted according to time created.

this view will be easy to have more patient list in a single view.

**Comment by bodhish** [comment]
@gigincg could you look at it?
