### ISSUE TITLE
Coloured Shifting cards

### ISSUE THREAD

**Issue by athulmanuel** [ohcnetwork/care_fe#676]
Same as we have done in tele medicine, it would be good if we had different color coding for patient cards according to their time. 

Eg: if a patient shift was requested by 2 pm, if it is lying in pending for more than 2 hours, it must be highlighted and fi possible brought up in the list. ---- the time could be set for differently for each tab as the time taken for each tab are different. 

ie : if the card is in pending, we could give 2 hours, but for destination approval, only 1 hour is needed, for arranging transportation only maximum half an hour is needed.

**Comment by bodhish** [comment]
we will start with a 2 hours color code for all.
