### ISSUE TITLE
a new tab in Shifting

### ISSUE THREAD

**Issue by athulmanuel** [ohcnetwork/care_fe#677]
some of the cases are kept on hold after receiving the request, at present it is kept in pending, making it a long list. 
but the cases in hold would have been solved the half way. so if there is an tab named - HOLD- view and access only for shifting center, they could put the card their and review it from time to time and rest of the pending cards would go in the normal flow. 

now the cases on HOLD are being searched from pending and the chances of missing are high.

**Comment by vigneshhari** [comment]
@bodhish can you start with the fe changes, the API is pretty basic, i will add an ON_HOLD status only changeable by the shifting center.

**Comment by vigneshhari** [comment]
API is completed and pushed to staging. On hold, status has the integer value 15.
(15, "ON HOLD"),

**Comment by vigneshhari** [comment]
This feature is already implemented, Review and close the issue, @aparnacoronasafe @amruthavijay88
