### ISSUE TITLE
entry in consultation- admission

### ISSUE THREAD

**Issue by athulmanuel** [ohcnetwork/care_fe#717]
if they are entering the data of a positive patient in consultation, then the entering faciltiy need to admit the patient .. might be a hospital or even a Covid management center. later they could refer him. 

at present we are promoting only positive patients enntry in CARE.  but could keep it open . so if the patient is positive then  the only option that has to come should be admission. 
only if the patient is negative or any other they need to show the other options. 

so we could freeze the option to admission .

![admission for everyone](https://user-images.githubusercontent.com/64475161/94025330-0364fc80-fdd6-11ea-9a12-bc2e508697cd.jpg)

@bodhish ---- would this flow be ok ?

**Comment by bodhish** [comment]
We can add a note above the field as an instruction to choose admission.

Choosing by default will include more work.
