### ISSUE TITLE
auto tele medicine if selected home isolation 

### ISSUE THREAD

**Issue by athulmanuel** [ohcnetwork/care_fe#718]
once they selected they home isolation in the admission status, the patient must be shifted into the tele medicine system of that facility. 
 this will be majorly used by the covid management center.  

![auto tele medicine ](https://user-images.githubusercontent.com/64475161/94027092-1b3d8000-fdd8-11ea-987a-890f67ad95bb.jpg)

**Comment by bodhish** [comment]
@vigneshhari could we validate if `is_telemedicine` flag is set for patients with `Home Isolation`

**Comment by bodhish** [comment]
Add validation in FE

**Comment by aparnacoronasafe** [comment]
tested in staging. Test failed.

I could save a consultation by adding "home isolation" while keeping the telemedicine option NO
