### ISSUE TITLE
Display of live patients in facility

### ISSUE THREAD

**Issue by athulmanuel** [ohcnetwork/care_fe#722]
Could we display live patient number in the home page of the facility or near the facility name , like age near the patient name

**Comment by vigneshhari** [comment]
Will add it to the dashboard as this is a computationally heavy task.

**Comment by bodhish** [comment]
@saanuregh 

Add `live` & `discharged` to dashboard once @vigneshhari changes the API

**Comment by bodhish** [comment]
@vigneshhari could you update the api

**Comment by vigneshhari** [comment]
"actual_live_patients" and "actual_discharged_patients" added in the facility capacity API to reflect actual patients count.

**Comment by saanuregh** [comment]
Is "actual_live_patients" and "actual_discharged_patients" exposed by any of the summary endpoints?

**Comment by vigneshhari** [comment]
facility capacity summary API, will be updated after the next summary ( after 5 mins )

**Comment by amruthavijay88** [comment]
Tested. Count of 'live patients' and 'discharged patients' are available in dashboard, but not in 'facility' details within CARE - as requested by Dr Athul.

**Comment by bodhish** [comment]
We will not be adding this in care. Dashboard is created to tackle these cases
