### ISSUE TITLE
Add spO2

### ISSUE THREAD

**Issue by athulmanuel** [ohcnetwork/care_fe#723]
In consultation updates we could omit temperature and add SpO2
It's more needed that keeping track of temperature

**Comment by bodhish** [comment]
capture SPo2 in daily rounds?

**Comment by vigneshhari** [comment]
daily rounds or consultation? 
Sp02 is Continuously monitored rather than at a given time right?

**Comment by vigneshhari** [comment]
added field spo2 ( Decimal Field ) to (daily rounds/Consultation Updates)
