### ISSUE TITLE
Additional list view in shifting. on header button click

### ISSUE THREAD

**Issue by dauntlessnomad** [ohcnetwork/care_fe#730]
list all shifting in a table view on header button click

**Comment by bodhish** [comment]
@tomahawk-pilot can we make this the default view in shifting?

And board can be triggered on click. 

We could reduce 4 network request per click. 😅

**Comment by bodhish** [comment]
Api's are not required. This just has to list one board at a time with list wise styling.

**Comment by bodhish** [comment]
Hey @MalayaliRobz any updates?

**Comment by MrRobz** [comment]
> Hey @MalayaliRobz any updates?

Still working on it. Hopefully would be done by tmrw!
