### ISSUE TITLE
Allow the admin to edit access of Staff to access desirable facilities.

### ISSUE THREAD

**Issue by aparnacoronasafe** [ohcnetwork/care_fe#736]
The District admin must have the power to edit which facility is accessible to each Staff-created in the district.

This feature may be added to the user management tab at https://care.coronasafe.in/users

@bodhish please review this issue and comment

@tomahawk-pilot, please deliver this at the earliest.

**Comment by vigneshhari** [comment]
API's for this is already present.

**Comment by bodhish** [comment]
@tomahawk-pilot 

Add Facility: users​/{username}​/add_facility​/users_add_facility
Remove Facility: /users/{username}/delete_facility/

**Comment by SandeepThomas** [comment]
@bodhish  @vigneshhari 

Assigned facilities needs to be added in List user api: /api/v1/users/

**Comment by vigneshhari** [comment]
Will Create this today,  cannot create it in the list users API as it is computationally expensive, will make another endpoint for listing facilities for a given user.

**Comment by vigneshhari** [comment]
GET /api/v1/users/<username>/get_facilities/

**Comment by vigneshhari** [comment]
This feature is already implemented, review and close this ASAP. @amruthavijay88 @aparnacoronasafe
