### ISSUE TITLE
Arrangement of Cards in Shifting Module

### ISSUE THREAD

**Issue by aparnacoronasafe** [ohcnetwork/care_fe#738]
In the shifting module, the cards are arranged as per LIFO rule. i.e. the last card appears on top. 

However, this is based on the time of the creation of shifting request. What we need is the time of the last modification of status. 

When the volumes are large it is important that when a card is moved to a new list, it appears on top irrespective of when the shifting request was created.

**Comment by vigneshhari** [comment]
Changes made in staging

**Comment by aparnacoronasafe** [comment]
Error "something went wrong" while trying to access the shifting tab. 

This happens both in facility log-in as well as shifting team log-in

**Comment by aparnacoronasafe** [comment]
Tested and rejected. Cards are still not arranged in LIFO

@vigneshhari

**Comment by bodhish** [comment]
We have a new ordering filter in shifting

**Comment by amruthavijay88** [comment]
Tested - seems to be working, but need @aparnacoronasafe to test on this as well.
