### ISSUE TITLE
Freeze consultation from previous facilities.

### ISSUE THREAD

**Issue by aparnacoronasafe** [ohcnetwork/care_fe#739]
It is still possible to add Consultation Updates (previous;y daily rounds) over consultation from a previous facility.

Please disallow the same. 

Also, shifting from a previous consultation is still allowed. the same was raised as a concern in issue #667

**Comment by vigneshhari** [comment]
Solved in Staging. Confirm and close issue.

**Comment by aparnacoronasafe** [comment]
Tested in staging. Approved.

**Comment by aparnacoronasafe** [comment]
Tested and approved
