### ISSUE TITLE
the review is based on op triage / consultation not 'consultation updates

### ISSUE THREAD

**Issue by athulmanuel** [ohcnetwork/care_fe#742]
at present the review is based on op consultation not " consultation update"

actually we need the review status for consultation updates not the firs triage/ consultation. 

the first review can be based on the op triage/consultation, but later it has to be changed according to the updates in ' consultation updated' 

we need to change it so to serve the purpose of the review badge.

**Comment by bodhish** [comment]
The review can now be assigned from `consultation update`
