### ISSUE TITLE
Result dissemination 

### ISSUE THREAD

**Issue by athulmanuel** [ohcnetwork/care_fe#743]
as a part of decentralization, we need to update each panchayath regarding the positive people in their panchayath, so that they can create the patient CARD in CARE.

 at present the method is tedious, 
we download data from health mon every 2 hours, the data that was 2 hours prior ( this is because there are changes in data on the live status ( the lab can change it for some short time of entry in case of mistake entry) ) 
so we download 8 am to 10 am data at 12 noon and then the data team filters it and gives to the team COVID POSITIVE TRIAGE and them enters in CARE.

as a part of decentralization, we need to give the cleaned data which is downloaded from Health Mon and give it to each panchayath so that they can call the patient, triage regarding home isolation or shifting and enter the card from each panchayat. 

for this if we could give each panchayat this data of the results of people who were tested from their panchayath through CARE, it will be really good and appealing.  

it could be disseminated through the COVID MANAGEMTN CENTERS login

tab could be TEST RESULTS -------------------- this must be DOWNLOADABLE for the panchayath.

we upload the CSV file every 2 hours form the central data team in the following data. 
[results display.xlsx](https://github.com/coronasafe/care_fe/files/5287334/results.display.xlsx)

in tis way panchayat would use CARE even to know the results.

there must be a filter to search by NAME and mobile number and WARD number  and address ( optional) .

**Comment by vigneshhari** [comment]
This is in Progress, should be done/Tested within 2-3 days

**Comment by bodhish** [comment]
The listing and show pages are now live.
Upload: work in progress

**Comment by bodhish** [comment]
This was delayed as the state gov have shifted from using `healthmon` to another software called `labsys` as health mon was not working as intended.
