### ISSUE TITLE
URGENT - IDSP request to add to patient details

### ISSUE THREAD

**Issue by athulmanuel** [ohcnetwork/care_fe#746]
Before i write this issue, let me tell you guys that it doesn't have any logic. 

I had gone to the surveillance unit to day as most of the decentralization has been blocked by them as they dont get the following data from CARE, so as to report from trivandrum . 

the yellow marked in the document file are the fields they need. 

i have discussed with @bodhish regarding the same. 

please try to get it in our system as soon as possible. 

[Flow for IDSP.docx](https://github.com/coronasafe/care_fe/files/5291564/Flow.for.IDSP.docx)

most of the things are already there, just that some small additions which might seem totally unnecessary.

Please guys help me..

**Comment by athulmanuel** [comment]
all these fields  must be added to the patient download list

**Comment by bodhish** [comment]
Add the following fields to  patient data and export
```
- village [:string]
- designation_of_health_care_worker [optional(:string)]
- instituion_of_health_care_worker [optional(:string)]
- transit_details [optional(:string)]
- frontline_worket [optional(string)]
- date_of_result (date)
- number_of_primary_contacts (int)
- number_of_secondary_contacts (int)
```

**Comment by aparnacoronasafe** [comment]
Tested. These fields do not appear in patient export. @bodhish @vigneshhari 

Patient basic details form is good.

**Comment by aparnacoronasafe** [comment]
Tested and approved
