### ISSUE TITLE
Linking of user to facility- BUG

### ISSUE THREAD

**Issue by aparnacoronasafe** [ohcnetwork/care_fe#749]
Steps to recreate the issue:

- Log-in using the district admin account. (in this case bodhi5)
- Create new user, 
**user type**- staff, 
**facility**- Athul's Hospital
**Username**- linktest

After successfully creating the user, when logged-in using the user ID (linktest), no facility found there.

@vigneshhari @bodhish

**Comment by vigneshhari** [comment]
This issue is now solved, so closing this issue. ( Deployed to Production )
