### ISSUE TITLE
"ward/Division of respective LSGI" Droplist is showing 0 for two respective local body in basic patient form

### ISSUE THREAD

**Issue by nihal467** [ohcnetwork/care_fe#755]
https://care.coronasafe.in/facility/005215fa-c20a-4409-aabf-4349dde4504d/patient

In Basic patient from, the "ward/Division of respective LSGI" Droplist is showing 0 for two respective local body : 
                         1. Koothattukulam Municipality 
                         2. Piravom Municipality.

                         
![Screenshot from 2020-10-02 20-38-36](https://user-images.githubusercontent.com/57055998/94939240-79144b00-04ef-11eb-8e4c-1d65e88edba3.png)
![Screenshot from 2020-10-02 20-37-58](https://user-images.githubusercontent.com/57055998/94939245-7ade0e80-04ef-11eb-8447-7c3537c471bf.png)

**Comment by bodhish** [comment]
We have added the ward details in production. Thier would be more Wards
