### ISSUE TITLE
Make Discharge End point Syncronous

### ISSUE THREAD

**Issue by vigneshhari** [ohcnetwork/care_fe#758]
Make both the patient API calls in the discharge modal in Patient Page to run synchronously, with the discharge happening last.

**Comment by MrRobz** [comment]
@vigneshhari 
I'll make the patient update request and discharge api one after the other as a hotfix. But the user experience is not so good, takes double time to discharge a patient.

If the discharge API could also take some patient data under say patient key and update the patient alone with discharge, it would be great.
OR 
Figure out a way fixing updating problems in the backend when concurrently calling patient patch and discharge api.
