### ISSUE TITLE
In Shifting, Empty card is generating data while we filter with patient name.

### ISSUE THREAD

**Issue by nihal467** [ohcnetwork/care_fe#761]
https://care.coronasafe.in/shifting?patient_name=Mohammed+nihal

The empty patient to be pickup section in shift is generating excel sheet data of patient in the awaiting destination approval section
 
![Screenshot from 2020-10-03 19-50-47](https://user-images.githubusercontent.com/57055998/94993943-0e781380-05b2-11eb-9866-295416c03cc4.png)

**Comment by vigneshhari** [comment]
Did not understand the issue, please explain in detail with steps to reproduce the issue in staging.

**Comment by bodhish** [comment]
Do review this issue again.
