### ISSUE TITLE
filter by date not working in SHIFTING

### ISSUE THREAD

**Issue by athulmanuel** [ohcnetwork/care_fe#764]
in shifting- filter by date is not working. it is always coming back to today's date

**Comment by bodhish** [comment]
@gigincg could you please check this

**Comment by YevheniySolovey** [comment]
Hi, do you have some demo user account for developers? I would like to contribute the project but I can't get in :)

**Comment by bodhish** [comment]
Hey @JeniaSolovey 
Thanks for showing interest, I have updated the [readme](https://github.com/coronasafe/care_fe/blob/develop/README.md#staging-api-credentails-for-testing)

**Comment by YevheniySolovey** [comment]
@bodhish thanks, now I can try to reproduce the issue and fix it. 👍
