### ISSUE TITLE
back option 

### ISSUE THREAD

**Issue by athulmanuel** [ohcnetwork/care_fe#765]
If we apply a filter and edit a card or shifting card, the only way to preserve the filter is be clicking back button, but when we click it, it goes back to the form which we where editing, making us click all the pages back to the main filter page. it makes things very tedious

**Comment by khavinshankar** [comment]
@bodhish for this issue can we store the selected filters in the localStorage?

**Comment by bodhish** [comment]
Sure. Do test local storage on IOS

**Comment by amruthavijay88** [comment]
Tested, seems to be working fine.
