### ISSUE TITLE
Report of Karunya Arogya Suraksha Padhathi

### ISSUE THREAD

**Issue by aparnacoronasafe** [ohcnetwork/care_fe#779]
Need an export option with details of people availing the Karunya Arogya Suraksha Padhathi

**Comment by bodhish** [comment]
@vigneshhari can you add a filter `is_ksap` in shifting?

**Comment by vigneshhari** [comment]
Added to the Shifting API.

**Comment by aparnacoronasafe** [comment]
@bodhi. 

The requirement is to obtain list of people shifting with KASP on a particular day. 

I don't think the filter serves the purpose

**Comment by vigneshhari** [comment]
@aparnacoronasafe can we filter people shifting on a particular day? and can we filter by KASP on top of that? , if so the requirements of this issue are resolved.

**Comment by bodhish** [comment]
apply day filter and kspa filter together. You will get the list
