### ISSUE TITLE
Streamlining transferring Patient Card

### ISSUE THREAD

**Issue by aparnacoronasafe** [ohcnetwork/care_fe#781]
There are 2 ways of transferring a patient card from one facility to another.

1) Through Shifting module: this is the longer shifting process, where the shifting control team, the transportation units participate in actually shifting a patient on the ground.

2) Importing card into another facility by entering Phone Number and date of birth: This process is used to transfer cards between facilities when no shifting as such happens on the ground. For eg: The Facility (virtual) called "Positive Triage Team" keeps making cards in care for all the persons who are declared positive by the state on a particular day. Then these cards are again shifted to another virtual facility called "Domiciliary Care" if such a patient is eligible to stay at home. Since there is no shifting on the ground, importing card by typing in phone number and DOB is preferred over using the shifting module. 

But because there are 2 ways of moving a patient card from one facility to another, we need to streamline it. 

ISSUE: sometimes, a shifting request may be under process in the shifting module but the card must have already moved to another facility through the 2nd method.

SOLUTION: As and when the card os a patient moves from one facility to another, the shifting request generated till then must automatically move to "Rejected"

**Comment by bodhish** [comment]
@vigneshhari can we add a comment on all the shifting request saying
```
The shifting request was auto rejected by the system as the patient was moved to XXX facility
```

**Comment by bodhish** [comment]
@vigneshhari

**Comment by amruthavijay88** [comment]
Tested, rejected.

**Comment by aparnacoronasafe** [comment]
tested in staging. approved.
