### ISSUE TITLE
Discharge Amendements

### ISSUE THREAD

**Issue by aparnacoronasafe** [ohcnetwork/care_fe#783]
When the pop-up window appears on discharge, There are 2 options to note as "Negative" "Recovery" and "Recovered" which is confusing. Please only keep 'Negative' as the option. 

Also, disallow discharge of positive patients.

Unless a patient is negative or expired, block discharge

**Comment by bodhish** [comment]
we won't create any blocks. The patient status can now be updated on discharge, I have removed the conditional blocking.

**Comment by amruthavijay88** [comment]
Tested -  
1."Recovery" and "Recovered" is still seen.
2. Positive patient can be discharged.

**Comment by bodhish** [comment]
Positive patients can be discharged from care if they are taken out of the district. 
I don't want to block it as its practically possible to take those actions.
