### ISSUE TITLE
Expired patients

### ISSUE THREAD

**Issue by aparnacoronasafe** [ohcnetwork/care_fe#784]
When a patient is marked as Expired, the same should be flagged in the patient list itself and the card must automatically move out of the live list

**Comment by bodhish** [comment]
Please update the patient status to expired while discharging

**Comment by bodhish** [comment]
Discharge Patients from care

**Comment by amruthavijay88** [comment]
Tested -when we update patient status to 'expired', it's not moved out of patient 'live' list yet.

**Comment by bodhish** [comment]
The link between a hospital and the patient has to be removed, its better to use the discharge from care flow.
