### ISSUE TITLE
Declared Positive 

### ISSUE THREAD

**Issue by aparnacoronasafe** [ohcnetwork/care_fe#785]
There must be a switch on the basic patient details form to mark if the patient is declared as COVID positive by the state. 

When turned to "YES", then a field for the date must appear with the default date set at that same day, but the date may be changed.

**Comment by vigneshhari** [comment]
In Short, we need a boolean field whether the patient is declared COVID positive by the state and a date that is different from the other positive dates we already have?

**Comment by vigneshhari** [comment]
Added Required Fields in Patient Model
