### ISSUE TITLE
Name/ Cluster of Contact 

### ISSUE THREAD

**Issue by aparnacoronasafe** [ohcnetwork/care_fe#790]
Please add an additional field in the patient details form.

If the patient is a contact. this additional field must come for "Name/ Cluster of Contact "

**Comment by bodhish** [comment]
@vigneshhari can you add this to patients.

**Comment by vigneshhari** [comment]
Added to Patient

**Comment by aparnacoronasafe** [comment]
@vigneshhari please make the change in export also

**Comment by vigneshhari** [comment]
Added to Export
