### ISSUE TITLE
Add bed type

### ISSUE THREAD

**Issue by athulmanuel** [ohcnetwork/care_fe#798]
add two more type
KASP beds
KASP ICU beds

**Comment by bodhish** [comment]
@vigneshhari a bit urgent

**Comment by vigneshhari** [comment]
@bodhish i am in kochi , dont have laptop , will add tmrw or tonight

**Comment by vigneshhari** [comment]
Api pushed

**Comment by bodhish** [comment]
```
(40, "KASP Beds"),
(50, "KASP ICU beds")
```

**Comment by aparnacoronasafe** [comment]
The new bed types must appear in the consultation sheet also to record admission into the bed types

https://care.coronasafe.in/facility/a029a3ee-6e6b-48f4-99fd-9a540105d8b5/patient/bd2aa6ed-5dfb-4e47-bde8-51d1d925abf4/consultation

Must also appear in advanced filter in patient tab "Last Admitted to"

**Comment by bodhish** [comment]
@aparnacoronasafe it's a different bed type altogether.
Ignoring.
