### ISSUE TITLE
Care - read only district admin- access to dashboard

### ISSUE THREAD

**Issue by aparnacoronasafe** [ohcnetwork/care_fe#799]
A read only district admin on CARE, when he logged in on dashboard, all values are shown as zero. 

@saanuregh please fix it! 

@bodhish

**Comment by bodhish** [comment]
@vigneshhari will it be an api issue?

**Comment by saanuregh** [comment]
Can't read only district admin call summaries endpoints?

**Comment by vigneshhari** [comment]
Now the summary endpoints are available to read-only admins as well.
