### ISSUE TITLE
Engaged label in shifting card. ASAP

### ISSUE THREAD

**Issue by athulmanuel** [ohcnetwork/care_fe#800]
If multiple people are handling the pending list, when one person has opened the card and dealing with it, others should know that it's already being dealt with. 

Ideally, it must be linked with the particular person. Like tele Medicne. This must happen for each tab in shifting.  

We need this ASAP.

**Comment by vigneshhari** [comment]
@athulmanuel if multiple users are created in the same shifting control facility then we can have an assigned to field to each shifting, is this what you require ?

**Comment by bodhish** [comment]
@vigneshhari an optional assigned field will work. We won't automate the assignment

**Comment by athulmanuel** [comment]
Yup. That's more than enough. Need to give this high priority

**Comment by vigneshhari** [comment]
@bodhish is_assigned_to_user field added in shifting ( defaulted to false )

**Comment by bodhish** [comment]
Can we make assigned_to an optional relation to the user. This will make the UI understand who is doing it. (github like assign flow)

**Comment by bodhish** [comment]
Done. 

![Screenshot from 2020-10-17 03-16-22](https://user-images.githubusercontent.com/14979190/96312008-583c1180-1028-11eb-98e1-d509962a850d.png)

**Comment by amruthavijay88** [comment]
Tested - rejected. In 'update shift request' this option 'assigned to' is showing, however, we aren't able to 'create shift request' without giving 'assigned to' - but button to choose the same isn't available there.

**Comment by bodhish** [comment]
@amruthavijay88 do test it again. The field is now optional.

**Comment by amruthavijay88** [comment]
Tested - now the issue in aforesaid comment is sorted. However, don't we need to keep 'assigned to' mandatory? 

Otherwise if people prefer not to update this field, creating this feature would be nullified know.

**Comment by bodhish** [comment]
It should be optional. It was a mistake.

Its an optional feature people could use

**Comment by vigneshhari** [comment]
But the shifting creating facility need not fill it right ?

**Comment by amruthavijay88** [comment]
@vigneshhari - no they don't need to.

@bodhish - okay 👍🏻
