### ISSUE TITLE
Admission type- in consultation update

### ISSUE THREAD

**Issue by aparnacoronasafe** [ohcnetwork/care_fe#801]
Please add a field "admitted to" with options 

- home isolation
- ward
- isolated room
- icu
- icu with ventilator 

Issue: when a patient is moved from isolated room to icu, no place to record the same in consultation update.

**Comment by aparnacoronasafe** [comment]
Also, this "admitted to" should appear in the export and the dashboard. 

The dashboard should have data from the update rather than the consultation

**Comment by aparnacoronasafe** [comment]
Unable to update consultation for any patient.

![image](https://user-images.githubusercontent.com/67050716/96449806-02878500-1233-11eb-9f22-973a2e14fd1b.png)

Steps to reproduce.
- log- in as a staff/ admin
- take a patients dashboard 
- click on update consultation details button on an existing consultation
- the action is barred and the above error message pops up as a notification

**Comment by bodhish** [comment]
@aparnacoronasafe looks like an iphone issue. do test again
