### ISSUE TITLE
Edit access to facility

### ISSUE THREAD

**Issue by aparnacoronasafe** [ohcnetwork/care_fe#810]
Any user linked to a facility, including staff, must have permission to edit facility details

@vigneshhari

**Comment by vigneshhari** [comment]
Will fix it with the next deployment.

**Comment by aparnacoronasafe** [comment]
![image](https://user-images.githubusercontent.com/67050716/96448296-ca7f4280-1230-11eb-9117-b82ab31e7487.png)

The issue is not fixed. 

Steps to reproduce.
- logged into care as an admin (bodhi5)
- created a new facility (Link Road hospital)
- created a new staff user (Radha) while linking her to the few facility (Link Road hospital) 
- logged in as the new staff (Radha) 
- opened the facility (Link Road hospital) and attempted to edit the facility details.
- the edits are not saved and the above error notification comes up. 

I believe it's because when an admin creates a facility, then a staff within the facility has no access to editing such facility details entered by the admin.

**Comment by bodhish** [comment]
@aparnacoronasafe it looks like an ios specific issue. Do test on laptop
