### ISSUE TITLE
Advanced patient filter: declared

### ISSUE THREAD

**Issue by aparnacoronasafe** [ohcnetwork/care_fe#813]
Please add a filter in patients tab to sort declared/not declared patients. Also, enable sorting by declared date.

**Comment by aparnacoronasafe** [comment]
@vigneshhari  Could you please move this soon?

**Comment by vigneshhari** [comment]
API Done and Pushed.

**Comment by aparnacoronasafe** [comment]
@bodhish please move this at the earliest.

**Comment by 7tena** [comment]
Can I work on this?

**Comment by bodhish** [comment]
Sure @7tena

**Comment by smartclash** [comment]
@aparnacoronasafe Me and @arpancodes have made it possible to filter by declared and not declared state. But we don't quite get what you mean by "enable sorting by declared date".

Does `Date of Result` and `Declared Date` mean the same thing?

Check the WIP Pull Request at #1090 

![2021-05-16_17-27](https://user-images.githubusercontent.com/16922883/118396213-192c7800-b66c-11eb-8b6f-9a1fca7bd7a0.png)

**Comment by smartclash** [comment]
@vigneshhari We need a parameter at `GET /patients` endpoint for `date_declared_positive`. It's a date.

Example, `date_of_result` request parameter at `/patients` endpoint

**Comment by amruthavijay88** [comment]
@vigneshhari - please guide

**Comment by vigneshhari** [comment]
Added Filters for date_declared_positive in Patient API
