### ISSUE TITLE
Revise LSG list

### ISSUE THREAD

**Issue by aparnacoronasafe** [ohcnetwork/care_fe#815]
There appears "Ernakulam district panchayat" in the list of LSGs.

Please remove the same.

**Comment by bodhish** [comment]
@aparnacoronasafe these are ops issues. We don't have to update anything on the code to get this done. Could you talk to @tomahawk-pilot and figure out a way to get this done.

**Comment by aparnacoronasafe** [comment]
Still can see Ernakulam
![Uploading Screenshot 2020-10-27 at 9.33.10 AM.png…]()
 district panchayat

**Comment by bodhish** [comment]
@aparnacoronasafe check my comment
