### ISSUE TITLE
Discharge: Bar positive discharges

### ISSUE THREAD

**Issue by aparnacoronasafe** [ohcnetwork/care_fe#817]
Please do-not allow COVID POSITIVE patients discharge from care

The only exception being transfers to another district. Please provide an option for the same. To be explained in next issue

**Comment by bodhish** [comment]
Its an ops issue. Please educate people. 😑

**Comment by athulmanuel** [comment]
@bodhish could we change the auto select option from POSITIVE to NEGATIVE in pop that comes begore discharge. or keep it as select and only if they select any of the options they can DISCHARGE from CARE

**Comment by bodhish** [comment]
@athulmanuel user will have to pick a `disease_status` to discharge the patient here-on.

**Comment by amruthavijay88** [comment]
Tested. Discharge status doesn't automatically show 'negative'. Still there is an option to choose whatever option available from dropdown and a positive patient may be discharged.

**Comment by bodhish** [comment]
We just don't want to choose a default value. This will ensure that the current status of the patient is correct when they are discharged. It can be positive or negative.
