### ISSUE TITLE
Transfer to another district

### ISSUE THREAD

**Issue by aparnacoronasafe** [ohcnetwork/care_fe#818]
Positive patients shifted to another district must be recorded separately in CARE.

It must be possible to view a list of such patients and also export list of such patients

**Comment by bodhish** [comment]
@vigneshhari what are the possibilities

**Comment by vigneshhari** [comment]
i can add a not equal query string filter for the receiving facility district, call that with the district and you have patients that are shifted out of the district

**Comment by athulmanuel** [comment]
@vigneshhari that is good idea. but there is a small problem. we wont know when they are negative and wont be able to discharge them hence. could be have a criteria added in discharge which stays " POSITIVE but shifted to OTHER District" something of that sort.
