### ISSUE TITLE
DISCHARGE CERTIFICATE: URGENT

### ISSUE THREAD

**Issue by aparnacoronasafe** [ohcnetwork/care_fe#819]
Discharge certificates must be issued through CARE

- Certificated issued by MO. The sign of MO may be uploaded to the system as an image to appear on the certificate. This will enable issuing the certificate in soft copy. 

- patients may be given access to their discharge certificates directly on CARE. There may be a link on the homepage, for patients to enter their name and phone number to get a soft copy of their discharge certificate. An OTP may be sent to their registered number for verification.

- Format of discharge certificate to be shared by @athulmanuel

**Comment by aparnacoronasafe** [comment]
@bodhish Feature request from Dr. Mathews. Please process at the earliest

**Comment by bodhish** [comment]
Digitally issued certificates usually do not have a signature.

This looks like we need a lot of parts to be updated to get this working, eta 2 weeks.

**Comment by vigneshhari** [comment]
if you have verification via care they what is the point of a physical signature?

**Comment by athulmanuel** [comment]
physical signature is not important. the print is the only important thing.  the treatment summary is the only separate part, the medication on discharge could be an option in all the daily rounds. general advice could be standard and anything special could be added as optional.

**Comment by vigneshhari** [comment]
so it's almost exactly like a discharge summary, @bodhish can we make it as an email ?

**Comment by bodhish** [comment]
@vigneshhari let's build another webapp consuming care as be. 

I do see that it would be useful and could be expanded with infinite possibilities. 

It would be our 1st point of contact with a public user. They can login, see their basic data, consulation data, testing data.

This would be useful for people in home isolation where they could regularly check their progress, results, etc

**Comment by aparnacoronasafe** [comment]
@bodhish sounds like a great idea!

**Comment by aparnacoronasafe** [comment]
irrelevant now
