### ISSUE TITLE
Patient Form

### ISSUE THREAD

**Issue by dauntlessnomad** [ohcnetwork/care_fe#82]
Generate a unique id  label instead of a text field for the patient name ..
also after submit a dialogue box showing the id and asking them to note it down as hard copy. 
Cyber security feature

**Comment by dauntlessnomad** [comment]
when the form to add is opened the name field should be auto-populated with a UID

**Comment by injas427** [comment]
Is anyone working on this issue? Otherwise I'll work on it

**Comment by dauntlessnomad** [comment]
Completed  . with minor change in APi
