### ISSUE TITLE
Need to change date format in downloads in shifting tab

### ISSUE THREAD

**Issue by amruthavijay88** [ohcnetwork/care_fe#821]
In shifting tab, when we download a particular category, the 'creation' date and 'modified' date is in a format that's difficult for users to sort. Would be nice to have date and time separately- so that it's easy to sort for users. 

Also, the mobile number format is different - is it purposely kept that way?

**Comment by bodhish** [comment]
@amruthavijay88 all the date time in the system are based on  ISO 8601 format. 

https://en.m.wikipedia.org/wiki/ISO_8601#:~:text=As%20of%20ISO%208601-1,minute%20between%2000%20and%2059.

This is a standard machine readable format so we will not be taking this forward. 

8601 format is supported in almost all tools that could be used for data processing.
