### ISSUE TITLE
ADd SRF ID filter to patients

### ISSUE THREAD

**Issue by aparnacoronasafe** [ohcnetwork/care_fe#822]
SRF ID to be made a mandatory field in patient details form. (Most urgent)

Please also build a search feature based in SRF ID

**Comment by bodhish** [comment]
This can't be made mandatory as their would be patients without an SRF id.

@vigneshhari could you add a filter?

**Comment by vigneshhari** [comment]
srf_id added as a get parameter in the list filter

**Comment by bodhish** [comment]
Have added SRF_ID as a filter to patients.

**Comment by amruthavijay88** [comment]
Tested - SRF ID as a search option may not help the field team, they need this for downloading file and comparing it with another sheet wherein SRF ID will act as vlookup search parameter.

**Comment by bodhish** [comment]
We will not be doing that. Please do file another issue with exact details on what they are trying to do,
