### ISSUE TITLE
Change Minutes  in Review

### ISSUE THREAD

**Issue by athulmanuel** [ohcnetwork/care_fe#825]
minutes in the Review time is very less userfriendly.
 could we change it to hours or better would be a drop down like in Tele Medicine- ie 3 hour/ 8 hours/ 24 hours

**Comment by vigneshhari** [comment]
@bodhish let the be still use minutes, change only required in the front end.

**Comment by bodhish** [comment]
Yep. Will add a drop down to select time in FE

**Comment by amruthavijay88** [comment]
Tested - review time is now seen from 30min, 1hr, 2hr, 3hr, 4hr upto 48hrs.
