### ISSUE TITLE
Resolve redirects in consultations page

### ISSUE THREAD

**Issue by bodhish** [ohcnetwork/care_fe#827]
**Describe the bug**
Resolve redirects in consultation page

**To Reproduce**
1. Go to https://care.coronasafe.network/facility/facility_id/patient/patient_id/consultation/consultation_id/
2. Click on: Inspec the request and see the `301`
3. These requests will break in ios devices. 

**Expected behavior**
The request should not be redirected. Adding a `/` at the end will resolve the issue.

**Comment by aparnacoronasafe** [comment]
@bodhish Please test. Too technical for me to understand the issue here

**Comment by bodhish** [comment]
Resolved
