### ISSUE TITLE
Update ambulance form

### ISSUE THREAD

**Issue by bodhish** [ohcnetwork/care_fe#83]
GoK wants to capture two More information:

Add a question in ambulance field which can 
1. I / we will provide services free of any charge.

2. I / we will require fees for providing service @ Rs. x.xx / KM 

(Kindly note CCC / GoK / CCC is not committing any fee payment at this time; this is only for information collection at this time)

**Comment by jithinlal** [comment]
i can take up this job

**Comment by jithinlal** [comment]
can i get a login credentials?
