### ISSUE TITLE
Web UI for the Public

### ISSUE THREAD

**Issue by aparnacoronasafe** [ohcnetwork/care_fe#830]
Some features needed in the Public facing Web UI,

Downloads for Care Patients: The patients already treated through CARE must be able to get
- "Treatment Summary": a gist of treatment, advice given to them while admitted in a facility, while availing teleconsultation services, or while being monitored in home management of COVID. This feature must be available to live patients as well.
- "Discharge Summary": The discharge summary already generated must be available to download for patients here.

**Comment by bodhish** [comment]
@vigneshhari can you add an endpoint to email discharge summary

**Comment by bodhish** [comment]
Its a work in progress version. The development is paused as we lack clarity on the certificates

**Comment by bodhish** [comment]
I have created a rescript project for the same. Let me now if you guys are interested to contribute

**Comment by aparnacoronasafe** [comment]
Only point No. 3 remains relevant. Issue edited accordingly

**Comment by nihal467** [comment]
@aparnacoronasafe is this issue this relevant

**Comment by bodhish** [comment]
Closing this till we have a good plan.
