### ISSUE TITLE
Re-Design Patients landing page

### ISSUE THREAD

**Issue by divyaabelchada** [ohcnetwork/care_fe#835]
**Currently, it is displayed as horizontal cards with badges, it'll be easier for users to view data in a tabular - organized format
Here is a suggestion ->**
@bodhish 
![Patients](https://user-images.githubusercontent.com/48395125/96854925-b0847080-1479-11eb-9f50-f2cf85cf3384.png)

**Comment by bodhish** [comment]
@divyaabelchada how will it look on the mobile? 

We switched to a card like approach to support mobile. Would be great if you could also consider the designs mobile first.

**Comment by divyaabelchada** [comment]
> @divyaabelchada how will it look on the mobile?
> 
> We switched to a card like approach to support mobile. Would be great if you could also consider the designs mobile first.

Yeah.. ok I'll look into it
