### ISSUE TITLE
Revamping Facility Dashboard

### ISSUE THREAD

**Issue by aparnacoronasafe** [ohcnetwork/care_fe#839]
https://dashboard.coronasafe.network/app/district/capacity

*1)* The tiles on the facility dashboard needs to change to:-

<img width="570" alt="Screenshot 2020-10-23 at 8 11 52 PM" src="https://user-images.githubusercontent.com/67050716/97017907-19e4ac00-156c-11eb-951d-38778435fedb.png">

*2)* And the filter by facility type, on top of the tiles, the list needs to be amended

The options in the list must be (please remove other facility type options)

- Pvt. Hospital 
-  GOVT hospitals ( bring all govt. Hospitals as a subset of this list. When the user selects government hospitals, all these below types should be auto-selected. But the user should have the option to subsequently select one or few among the list below)
                                    - CHC, 
                                    - Taluk Hospital, 
                                     - Women and child health centre, 
                                    -general hospital, 
                                     -district hospital, 
                                      -Govt. Medical college hospital, 
                                       -Apex Covid care centre, 
- FLTC
- SLTC
- DCC
- Covid Management Centre (Home Care)
- Shifting centre
- Telemedicine 

*3)* Once these changes are made, we can make the facility dashboard public

@bodhish this is a feature request from Mathews sir. Please act upon it immediately

**Comment by bodhish** [comment]
@aparnacoronasafe i see new bed types and missing bed types. Please create sub issues so that it's handled.

**Comment by bodhish** [comment]
@saanuregh do update the UI to match this.

**Comment by aparnacoronasafe** [comment]
@saanuregh @bodhish Can we have a tentative date of delivery? Dr. Mathews is personally following up with this. This change is very much needed. Please do the needful at the earliest.
