### ISSUE TITLE
Create IDSP Report through CARE

### ISSUE THREAD

**Issue by aparnacoronasafe** [ohcnetwork/care_fe#843]
IDSP requires excel export from CARE with the following columns:-

https://docs.google.com/spreadsheets/d/1Kd-rAcnc5zV8gzS9zijMwVLTZ_ZwLuIPYev0rsHU_hg/edit?usp=sharing

@bodhish In the above sheet, I have also mentioned where the info can be fetched from. Please review the same

**Comment by bodhish** [comment]
Please use the patient export. All the data is avilable. Don't want to work on a custom export as it doesn't add any value as all the data is avilable via the current export.

**Comment by bodhish** [comment]
Where did you get this request from?

**Comment by bodhish** [comment]
This looks like the download from external results.
