### ISSUE TITLE
Build Export on External Results

### ISSUE THREAD

**Issue by aparnacoronasafe** [ohcnetwork/care_fe#849]
Please build an option to export data from External results.

This will be very useful for the officer at the periphery.

@gigincg would you have the time to work on this one?

**Comment by aparnacoronasafe** [comment]
All info given in the external result may be exported
- name
- age
- result
- SRF ID
- Gender
- Address
- ward
- LSG
- Mobile Number
- Repeat?
- Patient Status
- Sample Type
- Test Type
- Sample collection date
- Result Date
- Source
- Patient Category

**Comment by vigneshhari** [comment]
API Pushed

**Comment by aparnacoronasafe** [comment]
Please remove the "ID" appearing in the first row. If it is the CARE internal id, showing it will cause confusion

**Comment by aparnacoronasafe** [comment]
@vigneshhari The export feature only exports the data in the current page.

There are already 3 pages of external results in staging, but export option lets be download these individual pages only and not the entire data.
