### ISSUE TITLE
Revise LSG List

### ISSUE THREAD

**Issue by aparnacoronasafe** [ohcnetwork/care_fe#853]
The LSG in CARE need not list Block Panchayats. Only Grama Panchayats, municipalities and corporations must appear here.

@athulmanuel to attach a revised final list of LSGs.

**Comment by aparnacoronasafe** [comment]
[PANCHAYATH.xlsx](https://github.com/coronasafe/care_fe/files/5500941/PANCHAYATH.xlsx)

Final List of LSGS. 
The existing block panchayats needs to be hidden 

@vigneshhari

**Comment by vigneshhari** [comment]
I hardly get time to push code changes, I'll give you the creds, someone will have to manually clean the data.

**Comment by aparnacoronasafe** [comment]
@vigneshhari @bodhish why is this in "Review pending?

Can we find someone who knows a bit of tech also to do this?
