### ISSUE TITLE
Filter by assigned person: SHIFTING

### ISSUE THREAD

**Issue by aparnacoronasafe** [ohcnetwork/care_fe#854]
In the shifting module, there must be a filter to sort cards assigned to any particular person.

Otherwise, even after the moderators assigns shifting to a patient, it may skip their attention

@vigneshhari @gigincg

**Comment by vigneshhari** [comment]
API changes have been pushed

**Comment by bodhish** [comment]
Please add this to advanced filters

**Comment by amruthavijay88** [comment]
Tested, declined.
User name is not available in filters.

**Comment by aparnacoronasafe** [comment]
<img width="254" alt="Screenshot 2021-05-16 at 11 38 40 PM" src="https://user-images.githubusercontent.com/67050716/118407785-ea2ff980-b69f-11eb-8403-78772b6120af.png">

Is this the new field added to filter?

The addition should have been "Assigned Staff" with dropdown showing list of all shifting staff and doctors

**Comment by aparnacoronasafe** [comment]
@khavinshankar 

<img width="627" alt="Screenshot 2021-05-17 at 12 32 31 AM" src="https://user-images.githubusercontent.com/67050716/118409298-709c0980-b6a7-11eb-85a1-2cc9951c3d68.png">

https://care.coronasafe.in/shifting/98dce657-e68d-4212-bc4a-5d438d0da1e0/update


This is the dropdown required to appear on the filter

Bodhi has for now hidden the filter for deployment. Please fix ASAP

**Comment by khavinshankar** [comment]
@aparnacoronasafe @amruthavijay88 @bodhish 
for selecting the **assigned_to** staff, we also need to know which **facility** he/she belongs to, 
![Screenshot from 2021-05-17 08-06-52](https://user-images.githubusercontent.com/29787772/118426043-18d1c280-b6e8-11eb-8dba-47319edb5768.png)

so
- 1st we need to select the facility of the respective staff
![Screenshot from 2021-05-17 08-07-43](https://user-images.githubusercontent.com/29787772/118426163-559db980-b6e8-11eb-9bdf-9349eb4b2fc7.png)

- and the we can select the staff
![Screenshot from 2021-05-17 08-09-02](https://user-images.githubusercontent.com/29787772/118426102-32730a00-b6e8-11eb-97c5-e78f6064387f.png)

**Comment by aparnacoronasafe** [comment]
@bodhish please make the filter available on stage so that I can test it.

Also, I don't understand why you need to capture which facility the staff is from to select the staff?? only the staff linked to that particular shifting centre will have access to the Shifting Kanban board right. So let's just show all staff linked to the facility to which the logged-in credential is attached to.  @khavinshankar

**Comment by bodhish** [comment]
Use the same scope that we use in the shift update form

**Comment by amruthavijay88** [comment]
@khavinshankar - is this issue pending from your side?

**Comment by khavinshankar** [comment]
@bodhish I actually did do it very similar to the shift update form, 

in shift update form, 
![Screenshot from 2021-05-23 07-51-18](https://user-images.githubusercontent.com/29787772/119246154-db17e280-bb9c-11eb-9a56-ce67ef50e44b.png)
The **assigned to** staff list is fetched based on **name of shifting approving facility**.



---
### we can also fetch users based on username(without the facility info), to implement it here 

#### either we need
- to edit  **/api/v1/shift/** such that assigned_to takes username(string) instead of id(number)
or
- a new api **/api/v1/users/:id** (GET   /users​/{id}​/  )

@bodhish need your thoughts

**Comment by bodhish** [comment]
You could use the user list api with name filter 😅.

**Comment by amruthavijay88** [comment]
tested, failed. 
when assigned staff is filtered, concerned patient's data isn't displayed in Kanban board

**Comment by aparnacoronasafe** [comment]
cannot find the doctor "ammu sathianathan" in the dropdown

**Comment by khavinshankar** [comment]
@amruthavijay88  there are many users with same name, so you might have selected the user with no patients assigned.

try searching `test-doc` and select `Ammu Sathianathan`

**Comment by khavinshankar** [comment]
@aparnacoronasafe the search works based on username, 


try searching `test-doc` and you'll get `Ammu Sathianathan`

**Comment by amruthavijay88** [comment]
@khavinshankar - I created a new staff, who belongs to a new shifting facility. Filter wasn't displaying a patient who was assigned to this staff - could you check.

**Comment by khavinshankar** [comment]
> @khavinshankar - I created a new staff, who belongs to a new shifting facility. Filter wasn't displaying a patient who was assigned to this staff - could you check.

@amruthavijay88  It seems to work fine.

**Comment by aparnacoronasafe** [comment]
@khavinshankar  . What is your rationale behind having a search by username? 

I believe it will be easier for the user to just by name 

Please make the change

**Comment by khavinshankar** [comment]
@vigneshhari need a parameter to filter users (GET api/v1/users/)

1. `search_text` similar to the one in the facility (GET api/v1/facility/)
![image](https://user-images.githubusercontent.com/29787772/120313189-48dbb100-c2f7-11eb-8171-a36146cb760f.png)

### or

2. `full_name` currently in users (GET api/v1/users/) there are `first_name` and `last_name`, we need a parameter to search with the full name

**Comment by vigneshhari** [comment]
added search_text in users api as well

**Comment by amruthavijay88** [comment]
@khavinshankar
