### ISSUE TITLE
Discharge Summary additions

### ISSUE THREAD

**Issue by aparnacoronasafe** [ohcnetwork/care_fe#856]
Two things must appear on the discharge summary.

- As of now the only date of admission is visible in the discharge summary. We need both "DATE OF ADMISSION TO CARE" and "DATE OF ADMISSION TO THE CURRENT FACILITY" to appear on the discharge summary. 

- The following newly added fields to the patient basic details form ( https://care.coronasafe.in/facility/3447b03d-7522-4525-9e14-58d7628b1e9e/patient) must also appear on the discharge summary
1. Disease status 
2. SRF ID
3. Date of result

This is a priority- @bodhish

**Comment by bodhish** [comment]
This should be updated in the backend. (care repo)

**Comment by shaileshaanand** [comment]
@vigneshhari   Where is the "Date of admission to current facility" stored?

**Comment by shaileshaanand** [comment]
[patient_discharge_report.pdf](https://github.com/coronasafe/care_fe/files/6484748/patient_discharge_report.pdf)
This is the current progress, I can't find "Date of admission to current facility" so it is not present in this version.
@aparnacoronasafe @amruthavijay88  @vigneshhari

**Comment by vigneshhari** [comment]
As discussed we need the investigation report and the prescriptions also to be present in the discharge summary, @aparnacoronasafe add this to the issue as well.

**Comment by vigneshhari** [comment]
data of admission is the created date of the consultation object.

**Comment by shaileshaanand** [comment]
> data of admission is the created date of the consultation object.

Okay, the first consultation right?

**Comment by shaileshaanand** [comment]
@vigneshhari I cannot find what value we have to show for Prescriptions, It is a json field.
The Prescriptions already come under medication in the summary.
