### ISSUE TITLE
Changes in Consultation Form

### ISSUE THREAD

**Issue by aparnacoronasafe** [ohcnetwork/care_fe#857]
https://care.coronasafe.in/facility/95144e53-e9a8-42de-a67c-fdcab3eff992/patient/fa3e84df-73d2-4dec-9094-4802f06a65f0/consultation

Because all patients within care are treated as admissions, can we disable

- Decision after Consultation
- Admission (YES/NO)

**Comment by bodhish** [comment]
Its created to handle both cases, I don't want to restrict the scope. 
If you could create an issue explaining the actual problem, we could figure out creative solutions.
