### ISSUE TITLE
Doctor's Interface for Telemedicine within CARE

### ISSUE THREAD

**Issue by aparnacoronasafe** [ohcnetwork/care_fe#858]
Please build a doctor's interface for telemedicine within CARE

The doctor who logs in must be able to see the list of patients assigned to him/her

There must be alerts and notifications for review.

**Comment by vigneshhari** [comment]
Alerts and notifications are hard to build, the rest have already been built

**Comment by bodhish** [comment]
@aparnacoronasafe alerts and Notifications are not part of the system. will have to implement that from scratch. Can you add a separate issue for that?
