### ISSUE TITLE
Patient dashboard 

### ISSUE THREAD

**Issue by aparnacoronasafe** [ohcnetwork/care_fe#859]
Change the UI of the Patient dashboard.

- No. of days since tested positive must be visible prominently on top.
- Tracing details need not be placed so prominently.
- Consultation details to be visible on top.

**Comment by athulmanuel** [comment]
This is needed for them to use CARE in periphery. 

A flag should come that says the it's time to retest, i.e day count appears and when it crosses 10, an alert. If a retest is done then every alternative day the alert should come
