### ISSUE TITLE
Filter by No. of days of being infected : Patient tab

### ISSUE THREAD

**Issue by aparnacoronasafe** [ohcnetwork/care_fe#860]
In advanced filters in patient tab, add a filter to sort patients by no. of days since they tested positive.

**Comment by vigneshhari** [comment]
that is the same as a date filter with the date of result and patient status right?  declared date in between the same day and status as positive?

**Comment by aparnacoronasafe** [comment]
@vigneshhari yes. we need a filet by date of test on advanced filter

**Comment by vigneshhari** [comment]
Added date_of_result filter in patient

**Comment by smartclash** [comment]
@divyagar The field is not working. Checked on our staging server, it didn't work there too.

**Comment by divyagar** [comment]
@vigneshhari I think there is some backend issue because I tested using postman also this filter is not working.

**Comment by vigneshhari** [comment]
This is a date range filter and not a date filter, check how date range filters work and try again.

**Comment by aparnacoronasafe** [comment]
Again, the same issue with date range observed. unable to select just 1 day.

This is listed as a separate issue
