### ISSUE TITLE
Addition to Consultation updates

### ISSUE THREAD

**Issue by aparnacoronasafe** [ohcnetwork/care_fe#861]
Add the following to consultation update form (https://care.coronasafe.in/facility/95144e53-e9a8-42de-a67c-fdcab3eff992/patient/fa3e84df-73d2-4dec-9094-4802f06a65f0/consultation/1a929e96-4667-4a0a-b884-bfdf2d491e6a/daily-rounds)

- Prescription module
- Telemedicine module
- Field for diagnosis.

These fields are already available in the consultation form (https://care.coronasafe.in/facility/95144e53-e9a8-42de-a67c-fdcab3eff992/patient/fa3e84df-73d2-4dec-9094-4802f06a65f0/consultation )

**Comment by vigneshhari** [comment]
what do you mean by telemedicine module ?

**Comment by bodhish** [comment]
@aparnacoronasafe

**Comment by aparnacoronasafe** [comment]
The fields at the end of consultation form pertaining to telemedicine 

![image](https://user-images.githubusercontent.com/67050716/104601018-bddb8080-569f-11eb-80cb-7954fbdb02bd.jpeg)

**Comment by bodhish** [comment]
@aparnacoronasafe is it still required

**Comment by vigneshhari** [comment]
@bodhish all these are already added

**Comment by aparnacoronasafe** [comment]
no change required
