### ISSUE TITLE
Disable multiple consultation during the same admission.

### ISSUE THREAD

**Issue by aparnacoronasafe** [ohcnetwork/care_fe#862]
Once Issue #861 is closed,

The add consultation button for a patient may be disabled after one consultation is filed by the particular facility during that particular admission. 

To add any more details by the hospital, "update consultation" must be used.

**Comment by vigneshhari** [comment]
Do you just want to give an error saying that the consultation must be closed before starting a new one? or automatically discharge the last consultation on moving to the next one?

**Comment by aparnacoronasafe** [comment]
when a user tries to file a second consultation, a message must appear " A consultation is already filed for this patient. To add more details, please file a "Consultation Update".


DO NOT automatically discharge. this will lead to a lot of fake discharges and readmissions getting logged.

**Comment by aparnacoronasafe** [comment]
@vigneshhari

**Comment by bodhish** [comment]
can a patient create multiple consultations in the same facility when one exists?

**Comment by vigneshhari** [comment]
@aparnacoronasafe this issue is solved in the backend, @bodhish the front end shows both consultation created and consultation error in this case, show the error only.

**Comment by bodhish** [comment]
Updated

**Comment by amruthavijay88** [comment]
Tested. Two comments;

1. Error says "Consultation - Exists please - Edit Existing Consultation". Punctuation issues here.
2. When you click - 'view consultation' and click 'update details', it lets you edit existing consultation- without capturing current date. So, new symptoms will be added - under the old consultation date.

**Comment by aparnacoronasafe** [comment]
tested
