### ISSUE TITLE
Tag time in consultation updates

### ISSUE THREAD

**Issue by athulmanuel** [ohcnetwork/care_fe#863]
When we click on view consultation updates, not able to know when the ' consultation update' was done. [![image](https://user-images.githubusercontent.com/64475161/97874473-08a35880-1d3f-11eb-8d60-040101dbc977.jpeg)]()

The time taken that is shown here is temperature. Could remove that and make this time tag

**Comment by vigneshhari** [comment]
both the created time and updated time are being sent in the API

**Comment by aparnacoronasafe** [comment]
tested. approved.:-)
