### ISSUE TITLE
Rename bed type “ICU WITH OXYGEN SUPPORT”

### ISSUE THREAD

**Issue by aparnacoronasafe** [ohcnetwork/care_fe#866]
To "oxygen bed"

**Comment by bodhish** [comment]
@vigneshhari when you do this inform @saanuregh to update the keys

**Comment by vigneshhari** [comment]
ADMIT_CHOICES = [
    (None, "Not admitted"),
    (1, "Isolation Room"),
    (2, "ICU"),
    (3, "ICU with Non Invasive Ventilator"),
    (4, "Oxygen Bed"),
    (5, "ICU with Invasive Ventilator"),
    (20, "Home Isolation"),
    (30, "Gynaecology Ward"),
    (40, "Paediatric Ward"),
] 
These are the new keys now, @bodhish  @saanuregh

**Comment by saanuregh** [comment]
This only concerns the patient summary right and not the availability types right?

**Comment by vigneshhari** [comment]
Yeap

**Comment by saanuregh** [comment]
Fixed in https://github.com/coronasafe/dashboard/commit/4c73178829a5ed9ac0d466f4c6b10bc1defbe8a2
