### ISSUE TITLE
Minor enhancement in patient dashboard: Address

### ISSUE THREAD

**Issue by aparnacoronasafe** [ohcnetwork/care_fe#874]
In patient dashboard, when the address of a patient is long, the whole address is not text wrapped and hence is not visible.

for reference please look at the patient dashboard, address column
https://care.coronasafe.in/facility/17235b15-ac9c-49f7-9e84-0f14e7889ff2/patient/50bf9416-7c3c-4dfd-875f-b42ad63ece15

**Comment by ajil-paul** [comment]
This issue is solved

**Comment by aparnacoronasafe** [comment]
Tested. issue resolved
