### ISSUE TITLE
OP Consultation

### ISSUE THREAD

**Issue by aparnacoronasafe** [ohcnetwork/care_fe#875]
https://care.coronasafe.in/facility/17235b15-ac9c-49f7-9e84-0f14e7889ff2/patient/50bf9416-7c3c-4dfd-875f-b42ad63ece15/consultation/cbd20463-bb7d-40b7-a275-386f64b69b60/update

When decision after consultation is set at "OP Consultation" and not an admission, then the card automatically moves to the discharge list and the shift option is disabled. 

This is not desirable because of the following edge case:

KMC takes in COVID patients for consultation, if found healthy and stable, instead of admitting there, they are shifted to an FLCT. In such case, when KMC receives the patient in OP section, and when they enter the consultation card, if they mention OP Consultation, then the shift option becomes disabled. Currently, they are falsely noting it as admission and then immediately shifting out the patient.

**Comment by bodhish** [comment]
I have conveyed this possibility when we implemented the other flow.

The solution here to mark admission and shift our the patient. Shifting will only work for patients in IP don't mix it with OP. It's not configurable anymore. 

Disabling auto discharge for OP will have even more complicated outcomes

**Comment by bodhish** [comment]
I am closing the issue as nothing could be done here.
