### ISSUE TITLE
Notification for Tele-medicine module in CARE

### ISSUE THREAD

**Issue by aparnacoronasafe** [ohcnetwork/care_fe#880]
Currently, any patient admitted within any facility may still get teleconsultation from another team of doctors at the request of the admitting facility.

Such a doctor will see the patient details and can file consultation updates for the patient. 

**Feature Requirement**
When the tele-consultation doctor files a consultation update for the patient, the admitting facility must get a notification so that they may check the consultation and do the needful promptly. 

This is an urgent requirement. A special team of doctors are identified and placed in PVS hospital to give additional consultation and support to SLTCs that lack specialists.

**Comment by aparnacoronasafe** [comment]
@vigneshhari can you please look into this?

**Comment by bodhish** [comment]
The first version is now live. 
Please test it. I am moving this to review so that we could get it tested. 

The notification will be generated for all users in a facility when a patient is created and updated. 
( we are yet to work on push notifications. need some help from @tomahawk-pilot here)
