### ISSUE TITLE
Change in dashboard

### ISSUE THREAD

**Issue by aparnacoronasafe** [ohcnetwork/care_fe#884]
![WhatsApp Image 2020-11-24 at 10 12 45 PM](https://user-images.githubusercontent.com/67050716/100129008-fe402e80-2ea6-11eb-8af5-49bec5f2e581.jpeg)

Rename COVID Ventilators as "COVID ICU beds with Ventilator"

@saanuregh

**Comment by dauntlessnomad** [comment]
@saanuregh

**Comment by saanuregh** [comment]
Fixed in https://github.com/coronasafe/dashboard/commit/33058ac05221bfec6970eca28c4709f089e7725b

**Comment by aparnacoronasafe** [comment]
tested. approved
