### ISSUE TITLE
Disease status Amendment

### ISSUE THREAD

**Issue by aparnacoronasafe** [ohcnetwork/care_fe#885]
in basic patient details form (https://care.coronasafe.in/facility/6e401539-e27f-4aff-a626-c9d42427ffd7/patient/92fef811-2e9c-4b7e-8403-ae178e8ed23b/update), under the disease status, make the following changes

- delete RECOVERY (or to save all the entries with the option, merge it with RECOVERED)
- Merge NEGATIVE into RECOVERED. (because we only deal with COVID positive cases now, it is pointless to have both Recovered and Negative as options. A lot of times, a recovered patient is accidentally marked as negative) 

@AJIL-PAUL Could you please take a look?

**Comment by bodhish** [comment]
@vigneshhari can we do a data migration?

**Comment by smartclash** [comment]
Frontend change done, #989. Data migration pending.

**Comment by aparnacoronasafe** [comment]
solved in another issue
