### ISSUE TITLE
Lab Module: Investigations 

### ISSUE THREAD

**Issue by aparnacoronasafe** [ohcnetwork/care_fe#897]
A module for recording lab results needs to be created in CARE

[CIAL CSLTC IP CHART FINAL XL SHEET .pdf (1).xlsx](https://github.com/coronasafe/care_fe/files/5749937/CIAL.CSLTC.IP.CHART.FINAL.XL.SHEET.pdf.1.xlsx)

The table above contains list of all the tests usually done. 

The final visual presentation of it must be in a table with the Rows representing the different tests and the columns showing different dates on which the tests where done. This format will help doctors to compare the values.

SUGGESTIONS:
- The option to add these lab results may be placed next to where there is option to Upload files.
-  It would be a good idea to give the district admin power to edit the list of tests. NOT ESSENTIAL.

@bodhish This feature will be very cruicial in using care for the Post COVID camps begining 2nd of January.

**Comment by aparnacoronasafe** [comment]
![WhatsApp Image 2021-04-03 at 4 54 54 PM](https://user-images.githubusercontent.com/67050716/113535330-ba95c800-95f0-11eb-8d71-802393168e42.jpeg)

![WhatsApp Image 2021-04-03 at 4 54 53 PM](https://user-images.githubusercontent.com/67050716/113535324-b5d11400-95f0-11eb-934e-935da357ac3e.jpeg)

![WhatsApp Image 2021-04-03 at 4 54 54 PM (1)](https://user-images.githubusercontent.com/67050716/113535328-b9649b00-95f0-11eb-8396-a00b6c5fd2f5.jpeg)



The above is the final format of the investigation module with measuring unit and max and min values.

The Section on URINE ROUTINE must have a short text field against all headings

**Comment by aparnacoronasafe** [comment]
@vigneshhari please note

**Comment by bodhish** [comment]
Fixed and merged
