### ISSUE TITLE
Bug: date on KASP referral letter is incorrect

### ISSUE THREAD

**Issue by aparnacoronasafe** [ohcnetwork/care_fe#898]
A bug is noticed only in a few cases. NOT THERE IN TESTING

Patint SASI, age 45, admitted in Sanjoe Hospital, 

He was admitted to the hospital on 28th Dec, 2020 but when a shifting was initiated on 29th Dec, with KASP flag, the KASP referral letter shows admission date as 29th Dec, 2020.

@bodhish

**Comment by aparnacoronasafe** [comment]
@amruthavijay88 please test

**Comment by peeyush14goyal** [comment]
@aparnacoronasafe @bodhish @amruthavijay88  Is it a duplicate issue of #1157 ?

**Comment by aparnacoronasafe** [comment]
yes, @peeyush14goyal  . this is a stale issue. closing
