### ISSUE TITLE
Add Facility (Hospital) Page

### ISSUE THREAD

**Issue by mkrishnan-codes** [ohcnetwork/care_fe#9]
Form should have the below inputs.
Hospital name, district, Contact number, Address, Geolocation

Existing page for ref - https://dev.care.coronasafe.in/facility/create/

**Comment by injas427** [comment]
I'm working on it

**Comment by anandsimmy** [comment]
do we have any sample  credentials ?

**Comment by anandsimmy** [comment]
> I'm working on it

I'm also working..can you push your changes

**Comment by injas427** [comment]
> > I'm working on it
> 
> I'm also working..can you push your changes

I've already pushed the changes and it's available in develop

@tomahawk-pilot Can you please check and close this issue
