### ISSUE TITLE
Update tailwindcss to v2

### ISSUE THREAD

**Issue by bodhish** [ohcnetwork/care_fe#909]
We may need to update postcss to support v2

**Comment by amruthavijay88** [comment]
@smartclash - what's the update on this issue?

**Comment by smartclash** [comment]
Dependent on issue https://github.com/coronasafe/prescription-builder/issues/21, that needs to be fixed first then followed by https://github.com/coronasafe/prescription-builder/issues/19 to finally upgrade this project into Tailwind v2.

**Comment by aeswibon** [comment]
Tailwind has been upgraded to v3
