### ISSUE TITLE
Vaccination

### ISSUE THREAD

**Issue by aparnacoronasafe** [ohcnetwork/care_fe#913]
Please add a flag for vaccination in patient details

Also add a field to mention the CoWin reference number . It is a 14 digit number. This field must NOT be mandatory. 

@bodhish please do the needful

**Comment by bodhish** [comment]
@vigneshhari could make the backend change?

Add covin_id string.

Everyone with a covin_id should be considered as vaccinated.

This should go to the patients model.

Add a serch by covin_id
Add a boolean filter vaccinated

**Comment by vigneshhari** [comment]
Backend Changes Done
