### ISSUE TITLE
“Discharge from CARE” must be disabled when consultation is not filed

### ISSUE THREAD

**Issue by aparnacoronasafe** [ohcnetwork/care_fe#914]
When a facility had not filed consultation, discharge button must be disabled.

Currently, a facility can discharge a patient from care with never recording an admission in the first place.

**Comment by bodhish** [comment]
Can you add the steps to replicate this issue.

**Comment by aparnacoronasafe** [comment]
Transfer patient to a new facility. DONOT file consultation at the new facility. 

Discharge patient from care.

**Comment by khavinshankar** [comment]
@aparnacoronasafe @bodhish this is already functional, (https://care.coronasafe.in/facility/41c73414-e95e-4e50-b0b9-84bafb3b7440/patient/4fa6238b-2e37-4249-a7c9-61636a6ddcb3)

**Comment by aparnacoronasafe** [comment]
tested in staging

**Comment by amruthavijay88** [comment]
Tested, discharging without adding consultation in new facility isn't possible.
