### ISSUE TITLE
Creating patient by importing from external result.

### ISSUE THREAD

**Issue by aparnacoronasafe** [ohcnetwork/care_fe#925]
when logged in as staff,

When importing patient details from external results, (page: https://care.coronasafe.in/facility/c8afab90-25e9-46b3-b923-8cdb5dc828a9/patient), once the user types in the external result ID and submits, a "NOT FOUND" error message pops up on the top right corner.

This only happens for Staff level user and not the admin level user.

**Comment by vigneshhari** [comment]
Staff users do not have permission to access the data. This is by design and not a bug.

**Comment by aparnacoronasafe** [comment]
i agree @vigneshhari
