### ISSUE TITLE
inter-district shifting

### ISSUE THREAD

**Issue by aparnacoronasafe** [ohcnetwork/care_fe#928]
In shifting form, 
https://care.coronasafe.in/facility/25164286-8e40-41a0-9e6a-d46af0cd24e9/patient/0d9861e6-2a5c-4a4d-b48c-20f99c4abdd1/shift/new

in the field for "What facility would you like to assign the patient to", only the facilities within the district is shown in the dropdown menu. 

Please show a list of all facilities there.

This is to enable shifting from Lakshadweep to Ernakulam through CARE.

**Comment by vigneshhari** [comment]
Not a Backend Issue. @bodhish check fe

**Comment by bodhish** [comment]
Lakshadweep is a new state. This is not Inter district shifiting. It's inter-state. 

@vigneshhari I think it's an API issue. 

let's not touch this for now.

**Comment by nihal467** [comment]
@aparnacoronasafe is this issue still relevant

**Comment by sainak** [comment]
@nihal467 we can close this as we have a detailed issue filed for this: #1091
