### ISSUE TITLE
Simplifying Creation of patient card from external result.

### ISSUE THREAD

**Issue by aparnacoronasafe** [ohcnetwork/care_fe#930]
On the external result, (https://care.coronasafe.in/external_results) there must be an option against each entry to create a patient card for the said entry.

Currently, a patient card may be created by going to the patient form, (https://care.coronasafe.in/facility/6e401539-e27f-4aff-a626-c9d42427ffd7/patient) and importing details from the external result by entering the external result ID. But this flow is difficult for the user. 

@tomahawk-pilot

**Comment by divyagar** [comment]
@aparnacoronasafe Do you want this option in the external results table or inside each entry detail?
I mean somewhere in here:
![Screenshot (194)](https://user-images.githubusercontent.com/42246254/118142792-57395a00-b428-11eb-9c08-c5ddcf788468.png)

**Comment by arpancodes** [comment]
Hey @aparnacoronasafe , after clicking on the option against each entry in the list should the patient card be directly created or we should redirect to the patient creation form with fields filled up with the patient's info so the admin can edit the details as currently being done when we import external result during patient creation?

**Comment by aparnacoronasafe** [comment]
The later.

Because a few necessary fields in the patient creation form are essential fields to create a patient, the formal is not possible.

**Comment by aparnacoronasafe** [comment]
Test failed: User, even if he doesn't have access to a facility can still create c ard there

the facility pop up window shows all facilities, rather than the facilities that the user has access to

**Comment by arpancodes** [comment]
@vigneshhari I need API clarification I am using the prebuilt component FacilitySelect which I assumed was fetching the facilities according to the authorization.

**Comment by bodhish** [comment]
Should be fixed now @aparnacoronasafe

**Comment by aparnacoronasafe** [comment]
tested
