### ISSUE TITLE
KASP Empanelment 

### ISSUE THREAD

**Issue by aparnacoronasafe** [ohcnetwork/care_fe#941]
**Is your feature request related to a problem? Please describe.**
Some facilities within CARE are KASP empanelled. This information is not captured anywhere. 

**Describe the solution you'd like**
The district admin must be able to see a list of all facilities that are KASP empanelled. All users must be able to see that any facility is KASP empanelled.

**Additional context**
KASP is "karunya arogya sureksha pattadhi" is a scheme by the government where the empanelled hospitals will reserve a few beds for the poor. These beds can be availed by the beneficiary ( the health department issues a KASP referral form to the deserving) to get treatment at the hospitals whereby the expenses towards such treatment will be met by the state.

**Comment by bodhish** [comment]
@vigneshhari can we do this in priority?

**Comment by vigneshhari** [comment]
Isnt this already there ?

**Comment by aparnacoronasafe** [comment]
@vigneshhari no. Only KASP beds are captured.

**Comment by divyagar** [comment]
@aparnacoronasafe Is this field required?

**Comment by vigneshhari** [comment]
@aparnacoronasafe what else is needed ?

**Comment by vigneshhari** [comment]
make it default false
