### ISSUE TITLE
"Last admitted to": advanced filter: allow multi-select

### ISSUE THREAD

**Issue by aparnacoronasafe** [ohcnetwork/care_fe#943]
**Is your feature request related to a problem? Please describe.**
In the patients tab there is an advanced filter called "last admitted to". the options given are Ordinary bed, ICU, Ventilator etc. When the officials want to see all patients admitted to ICU and Ventilator, they are forced to view it separately, by applying the filter first to view patients in ICU and then again applying the filter to view patients in the ventilator. 

**Describe the solution you'd like**
Allow for multi-select of the options in the dropdown so that the user can multi-select both ICU and Ventilator to view list of all patients either in the ICU or the Ventilator.

**Comment by vigneshhari** [comment]
The API is implemented for this , UI is pending.

**Comment by khavinshankar** [comment]
@vigneshhari, the backend is throwing an error **last_consultation_admitted_to - Enter a number.**, I think the backend is expecting a number but for multiselect option array of numbers is sent to the backend. Is it something that has to be changed in frontend (like the format in which data is sent to BE) ?

**Comment by vigneshhari** [comment]
i made another filter called `last_consultation_admitted_to_list` use that and pass a comma-separated string to the BE

**Comment by aparnacoronasafe** [comment]
tested
