### ISSUE TITLE
Vaccination: Info on Dose and type

### ISSUE THREAD

**Issue by aparnacoronasafe** [ohcnetwork/care_fe#945]
CARE captures the information on whether a patient is vaccinated or not in the Create Patient form itself. It appears as a question with Yes/No option. 

However, we need to capture 
1- whether the patient has had the 1st dose alone or both the doses of the vaccine. 
2- Information regarding the type of vaccine availed is also relevant. An additional question may be added with a dropdown of the vaccine types available, which currently is CoviSHIELD and Covaxin.

**Comment by dauntlessnomad** [comment]
do we have an api for this.

**Comment by khavinshankar** [comment]
@divyagar or @shaileshaanand Is the API part ready for this?

**Comment by amruthavijay88** [comment]
@khavinshankar , @divyagar , @khavinshankar - Please update as to where this is pending - asap please.

**Comment by khavinshankar** [comment]
@amruthavijay88 As far as I know both front-end part and back-end part is done.

**Comment by divyagar** [comment]
PRs for both backend and front end are there. Review is pending.

**Comment by dauntlessnomad** [comment]
hey @divyagar and @khavinshankar  
please refrence the issue number on prs for tagging./

**Comment by bodhish** [comment]
@aparnacoronasafe any reason for holding this

**Comment by amruthavijay88** [comment]
Syam suggests to fix linting issues @shaileshaanand

**Comment by shaileshaanand** [comment]
I have fixed linting issues in PR #1050

**Comment by amruthavijay88** [comment]
@tomahawk-pilot - could you please review this?

**Comment by amruthavijay88** [comment]
Tested, verified.

**Comment by aparnacoronasafe** [comment]
@shaileshaanand @divyagar 

The only input values here must be 1 or 2. Please add validation

CoWin ID and type of vaccines must be optional field as some patients may not have that information readily available 

Also, where is this saved information made visible? The information does not appear on the patient dashboard. 

Even when I reopen the update details form of the patients, the prefilled fields are visible only when i click on "yes" for vaccinated.

**Comment by divyagar** [comment]
@aparnacoronasafe The validation is already done. User can only enter 1 and 2 as values if `Is patient vaccinated` field is selected as `yes`

**Comment by amruthavijay88** [comment]
tested - no of dozes are not displayed with radio buttons yet.

**Comment by amruthavijay88** [comment]
Tested - verified that radio buttons are available for vaccine dose. Saved information is also visible now, when one clicks update details within patient card.

**Comment by aparnacoronasafe** [comment]
The saved info on Vaccination including doses must be visible on the patient dashboard without having to click on update info

**Comment by gigincg** [comment]
@divyagar when we add a new field to the form always remember to display it on the UI.

**Comment by amruthavijay88** [comment]
@divyagar - please could you confirm on status.

**Comment by amruthavijay88** [comment]
Tested, vaccination dose doesn't show up on patient dashboard yet.

**Comment by amruthavijay88** [comment]
Tested, verified.

**Comment by aparnacoronasafe** [comment]
tested
