### ISSUE TITLE
Info on Vaccinated: Patient dashboard

### ISSUE THREAD

**Issue by aparnacoronasafe** [ohcnetwork/care_fe#946]
**Is your feature request related to a problem? Please describe.**
The information regarding vaccination does not appear on the patient dashboard

**Describe the solution you'd like**
The information must appear on the patient dashboard (https://care.coronasafe.in/facility/c2d37a3e-3b82-4a12-881f-5faca5a44134/patient/c3e9e64c-635e-4998-a669-5cc7ec1a4d22) next to the blood group.

It must also include information regarding dosage.

**Comment by dauntlessnomad** [comment]
is it present in the api ? @vigneshhari

**Comment by vigneshhari** [comment]
I remember bodhi adding an icon in the dashboard, long back, i believe that the api already supports this.
