### ISSUE TITLE
Typo on consultation form

### ISSUE THREAD

**Issue by aparnacoronasafe** [ohcnetwork/care_fe#947]
<img width="749" alt="Screenshot 2021-04-21 at 4 09 36 PM" src="https://user-images.githubusercontent.com/67050716/115540766-fb156700-a2bb-11eb-8542-8d860849f782.png">

The last section in the consultation form is the telecmedicine section. Here in drop down to assign a telemedicine doctor, the text says "Assign a shifting staff"

Please correct it to "Assign a doctor"

**Comment by bodhish** [comment]
@aparnacoronasafe test this in staging

**Comment by aparnacoronasafe** [comment]
tested!
