### ISSUE TITLE
permission issue- assigning doctor through Telemedicine

### ISSUE THREAD

**Issue by aparnacoronasafe** [ohcnetwork/care_fe#948]
**Describe the bug**
I Assigned a patient "Thara R N" on CARE staging to a doctor names Ammu Sathianathan (with user id test-doc). When i logged in from the doctors credentials to check out the status of the patient, I can see the patient details, but I caanot open the last consultation filed. An error message on "permission denied" popped up on the top right corner.

**Expected behavior**
The telemedicine doctor must be able to view all previous consultations of the patient to treat and give due care to the patient

**Comment by vigneshhari** [comment]
@aparnacoronasafe refrain from using any kind of PII data in a github issue.

**Comment by vigneshhari** [comment]
Issue has been solved and deployed to production
