### ISSUE TITLE
Saving an external result

### ISSUE THREAD

**Issue by aparnacoronasafe** [ohcnetwork/care_fe#951]
**Is your feature request related to a problem? Please describe.**

Most people that use external results do not have super-fast internet connections. 
So sometimes when they Upload a CSV file in the required format onto the CARE external result tab, upload page ( https://care.coronasafe.in/external_results/upload)  and click on "SAVE", they are unsure whether they did click the "SAVE" button or not. If they click again, then the list gets saved twice.

Nowadays because of an increasing number of daily new positive cases, the CSV files that get uploaded has hundreds of entries. If the file gets saved twice, then the data entry person has to open the external results and individually delete each entry.

**Describe the solution you'd like**
The suggestion from the user was to change the colour of the button. now the button is dark green, and when clicked, it turns into a darker green for a moment. This is not very noticeable. The users suggested that the colour of the button be changed to something lighter and when clicked it must change for a moment to a very contracting and darker colour so that the user is sure that he has already clicked the save button and must patiently wait a few minutes before clicking again.

This is only a suggested solution. you are free to choose any logical solution to overcome the problem.

**Describe alternatives you've considered**
An alternate could be to disallow saving the same CSV twice.

**Comment by ProCode2** [comment]
On it. Disabling the button as well as changing the colour until one save is completed.
