### ISSUE TITLE
telemedicine module: Doctor's access

### ISSUE THREAD

**Issue by aparnacoronasafe** [ohcnetwork/care_fe#958]
We have a telemedicine module inside care.
the reason for having this module is here:
- There may be patients in small healthcare facilities with no specialist doctors.
- When these patients become severely sick, There may not be enough resources to shift the pstient to a hospital with specialist doctors.
- Instead, the patient remains in the small healthcare facility, and he is put under telemedicine with a specialist doctor sitting elsewhere. 
- This was, the patient is admitted in a facility and gets around the clock medical attention
- He also gets the advanced care of a specialist through CARE.

The feature is explained as under:
Patient A is admitted in facility X. While the facility files consultation for the patient, telemedicine is enabled, and a Doctor P is assigned. 
Now when doctor P logs into CARE, he can view the card and consultations of the patient.

**Is your feature request related to a problem? Please describe.**
The problem is if the health status of the patient suddenly changes drastically, and facility X files a new consultation form and forgets to re-do the telemedicine section in the latest consultation, Doctor P suddenly loses access to the patient's details.

**Describe the solution you'd like**
The telemedicine section must always be auto-populated with the last settings/entries. 

This was the data entry person at facility X will have to take an effort in removing the access of the doctor P as and when the requirement ends. Access of Doctor P will not be revoked by mistake. 

**Describe alternatives you've considered**
The above solution is just a suggestion. Find the best way to solve the problem described above.

@vigneshhari Please comment on the proposed solution

**Comment by vigneshhari** [comment]
Sounds good , @bodhish the front end can automatically query the last consulatations doctor and fill it up as needed , there is no backend changes required.
