### ISSUE TITLE
Edit option for Investigation module

### ISSUE THREAD

**Issue by aparnacoronasafe** [ohcnetwork/care_fe#961]
@divyagar @developedBySJ @shaileshaanand 

We need an edit option for the investigation module.

Please make sure the user that has entered the values alone can edit it later, not any other user.

**Comment by aparnacoronasafe** [comment]
Hey @divyagar @shaileshaanand @developedBySJ 

Whats the update on this?

**Comment by amruthavijay88** [comment]
@developedBySJ - says this will be done by 14th May.

**Comment by amruthavijay88** [comment]
Tested, edit option is made available for investigation module, however, another user is able to made edits too.

**Comment by amruthavijay88** [comment]
@divyagar - please check.

**Comment by aparnacoronasafe** [comment]
feature tested. 

Once an update to the investigation is saved, the user is taken to a blank page.

But this happened when saving new investigation also. so i have filed it as a bug. hence closing the issue
