### ISSUE TITLE
Consultation Update filed by an external specialist: Telemedicine

### ISSUE THREAD

**Issue by aparnacoronasafe** [ohcnetwork/care_fe#962]
We have a telemedicine module inside care.
the reason for having this module is here:

There may be patients in small healthcare facilities with no specialist doctors.
When these patients become severely sick, There may not be enough resources to shift the patient to a hospital with specialist doctors.
Instead, the patient remains in the small healthcare facility, and he is put under telemedicine with a specialist doctor sitting elsewhere.
This is so that the patient is admitted in a facility and gets around the clock medical attention while He also gets the advanced care of a specialist through the telemedicine module of CARE.

The feature is explained as under:
Patient A is admitted in facility X. While the facility files consultation for the patient, telemedicine is enabled, and a Doctor P is assigned.
Now when doctor P logs into CARE, in the patients' tab, he can view the card and consultations of the patient.

**Is your feature request related to a problem? Please describe.**
Once doctor P views the patients clinical details, he needs to record his consultation in a consultation update. 
The consultation update filed by an external expert must be prominently flagged as an external consultation update. Otherwise, the facility X may find it confusing. it will be hard for them to distinguish theirs and experts consultation update. 

**Describe the solution you'd like**
The consultation update filed by the external specialist must appear in a different colour and must show who the consultation update is from. 
The consultation card on the patient dashboard must also have a flag that it contains a consultation update from an external expert.

**Comment by bodhish** [comment]
@vigneshhari @aparnacoronasafe This issue must be closed. The specialist should not have an option to create a consultation inside a facility that they don't have access.

**Comment by aparnacoronasafe** [comment]
@bodhish now that the external specialist will be filing a consultation update, we need the same to be flagged differently. 

I have modified the issue accordingly.

**Comment by dauntlessnomad** [comment]
@vigneshhari do we have an api that can serve this request ?

**Comment by aparnacoronasafe** [comment]
hey @sam9111 @Sandra3657 could you post an update here, please?

**Comment by Sandra3657** [comment]
We need some help with the API for the consultation update.  @vigneshhari

**Comment by bodhish** [comment]
@vigneshhari what's your take on this?

**Comment by vigneshhari** [comment]
there will be a flag in consultation and consultation update when an assigned doctor last updated the patient consultation/Consultation Update/DailyRound.

**Comment by bodhish** [comment]
okay

**Comment by vigneshhari** [comment]
@Sandra3657 @sam9111 
There are two new flags in the Consultation Update API : last_updated_by_telemedicine and created_by_telemedicine
There is one new flag in Consultation API : last_updated_by_telemedicine
All flags are read-only and updated automatically.

**Comment by sam9111** [comment]
Can we get sample login details for the external specialist to test? @aparnacoronasafe

**Comment by Sandra3657** [comment]
Finished the FE. Waiting for API.

**Comment by vigneshhari** [comment]
The API is fixed now.

**Comment by amruthavijay88** [comment]
Tested - when a homecare patient is assigned to a doc is outside the facility, it is tagged in a different color, whereas the regular daily consultation is updated normally.

![image](https://user-images.githubusercontent.com/67979586/119271346-cbd97900-bc1e-11eb-8371-7b5f0e283b99.png)

**Comment by aparnacoronasafe** [comment]
tested
