### ISSUE TITLE
Notification: Telemedicine

### ISSUE THREAD

**Issue by aparnacoronasafe** [ohcnetwork/care_fe#963]
We have a telemedicine module inside care.
the reason for having this module is here:

There may be patients in small healthcare facilities with no specialist doctors.
When these patients become severely sick, There may not be enough resources to shift the pstient to a hospital with specialist doctors.
Instead, the patient remains in the small healthcare facility, and he is put under telemedicine with a specialist doctor sitting elsewhere.
This was, the patient is admitted in a facility and gets around the clock medical attention
He also gets the advanced care of a specialist through the telemedicine module of CARE.

The feature is explained as under:
Patient A is admitted in facility X. While the facility files consultation for the patient, telemedicine is enabled, and a Doctor P is assigned.
Now when doctor P logs into CARE, in the patients tab, he can view the card and consultations of the patient.

**Is your feature request related to a problem? Please describe.**
When the external expert (doctor P) files a consultation for the patient, facility X must get notified of it, so that they may make appropriate changes in the treatment as per the consultation. Similarly, when facility X files a consultation/consultation update recording a change in the health status of the patient, Doctor P must get notified of it, since the patient is under his supervision as well. 

**Describe the solution you'd like**
A Notification bar is already built onto the UI. however, more work needs to go into making the notifications functional. 
@bodhish @vigneshhari Please add more technical details about the same.

**Comment by vigneshhari** [comment]
The notification is already built in the backend, it has to be implemented in the frontend only.

**Comment by bodhish** [comment]
@vigneshhari just the push is missing on the FE in my understaing. Is there anything else pending?

**Comment by vigneshhari** [comment]
Nope nothing else pending

**Comment by aparnacoronasafe** [comment]
TESTED.
