### ISSUE TITLE
Add prescription module to "Consultation update"

### ISSUE THREAD

**Issue by aparnacoronasafe** [ohcnetwork/care_fe#968]
Please add the prescription module to consultation update

**Comment by vigneshhari** [comment]
the field is `medication_given`.

**Comment by bodhish** [comment]
This is a super simple change. Copying the prescription component from consultation should be enough

**Comment by khavinshankar** [comment]
@vigneshhari the route `/consultation/{consultation_external_id}/daily_rounds/` is giving `500 Internal Server Error`

**Comment by vigneshhari** [comment]
I am making a new feature in the notification, probably that's why it's broken, it should be working now

**Comment by aparnacoronasafe** [comment]
@bodhish 

The prescription module is added. but the saved prescription doesn't show up anywhere.

**Comment by khavinshankar** [comment]
@aparnacoronasafe where do we need to show the prescription, is it ok to show it somewhere over here `/facility/:id/patient/:id/consultation/:id/daily-rounds/:id` (https://care.coronasafe.in/facility/ac195b3e-a537-4748-98cb-d78c25a8c0a8/patient/cef26e88-ce9a-48be-ae2b-a8ce91b85416/consultation/986f8ed4-d53d-4632-9a80-f1bf6831ecf6/daily-rounds/427)

**Comment by aparnacoronasafe** [comment]
@khavinshankar yes Khavin

Please place it there

**Comment by aparnacoronasafe** [comment]
Tested and ready to merge with production
