### ISSUE TITLE
Telemedicine doctor: can file fresh consultation

### ISSUE THREAD

**Issue by aparnacoronasafe** [ohcnetwork/care_fe#969]
**Describe the bug**
A telemedicine doctor is able to file a fresh consultation for any patient he has access to

This is not desirable.

The doctor must only be allowed to file consultation update

**Comment by vigneshhari** [comment]
@aparnacoronasafe wasn't this solved and verified ? close this

**Comment by aparnacoronasafe** [comment]
tested
