### ISSUE TITLE
Inventory Module for Oxygen

### ISSUE THREAD

**Issue by aparnacoronasafe** [ohcnetwork/care_fe#974]
Please add the following items to the inventory module:

- Gaseous Oxygen
- Liquid oxygen

Unit measure for both is liters

**Comment by khavinshankar** [comment]
@aparnacoronasafe these both are already in the inventory,
![Screenshot from 2021-04-25 22-32-08](https://user-images.githubusercontent.com/29787772/116002291-b587cf80-a616-11eb-9d92-3a68322f6d2c.png)
![Screenshot from 2021-04-25 22-33-27](https://user-images.githubusercontent.com/29787772/116002304-c7697280-a616-11eb-8e39-12bfcc256c05.png)

**Comment by bodhish** [comment]
Updating the scope for the issue.

Create facility-level summary and district level summary for oxygen utilization. 
This can be added to the dashboard where a user should be shown the mileage / time until empty for each facility and district
