### ISSUE TITLE
Bed type: Admitted to: consultation

### ISSUE THREAD

**Issue by aparnacoronasafe** [ohcnetwork/care_fe#975]
The consultation form is where we capture the data on what bed type the particular patient is admitted. currently, there is one question "admitted to" with a dropdown menu.

instead of that field, we now need four separate questions.

1) The first question must be "What bed is the patient admitted to" and the options are (dropdown)
- Home Isolation
- Isolation ward (male)
- Isolation ward (female)
- isolation room
- 'Oxygen Bed (male)
- 'Oxygen Bed (female)
- ICU

2)Is the patient admitted to a COVID reserved bed? YES/NO

3) Is the patient admitted to a KASP bed? YES/NO

4) The second question is, "what are the supportive devices utilized?":
The dropdown menu must show options based on the answer given in the first question.
- Home isolation: None, Oxygen concentrator, 
- Isolation ward: none, Oxygen concentrator, BiPAP, CPAP, 
- isolation room: none, Oxygen concentrator, BiPAP, CPAP, 
- Oxygen Bed: None, NRBM,BiPAP, CPAP, HFNC
- ICU: none, Oxygen concentrator, BiPAP, CPAP, invasive ventilator, NRBM, HFNC

Splitting this into 2 questions allows us to capture data to the details and allows us to recall and view the exact data that is required in any given point of time 

@vigneshhari  Please review the issue

**Comment by khavinshankar** [comment]
@vigneshhari currently the backend(`/api/v1/consultation/`) only takes `admitted_to`, but for the above feature, one more field is needed, something like `admitted_to_supportive_utility`

**Comment by vigneshhari** [comment]
The backend design is still under review, will update the issue once we complete priority items.

**Comment by aparnacoronasafe** [comment]
@amit-kr-debug @khavinshankar I have edited the issue. The isolation wards for males and females must be captures separately.
