### ISSUE TITLE
New Dashboard UI for Facilities Tab

### ISSUE THREAD

**Issue by joelsajichacko** [ohcnetwork/care_fe#999]
You can inspect the design [here](https://www.figma.com/file/5vTeIYUU4ikk02XaPmN4rg/Raksha-Covid?node-id=274%3A0)
Fonts used: Poppins and Roboto 
A "Filter by " option is included in the New UI

![Facilities Tab](https://user-images.githubusercontent.com/45791338/116580736-49b4a800-a931-11eb-81f3-2dcc58882106.jpg)

**Comment by divyagar** [comment]
@bodhish @tomahawk-pilot Work is completed. Please review.

**Comment by bodhish** [comment]
Holding this for a while

**Comment by aparnacoronasafe** [comment]
not deployed in staging yet! whats happening here?

@bodhish ?

**Comment by aparnacoronasafe** [comment]
@bodhish please review.

cant see this is staging
